### ISSUE TITLE
Install/update alpha versions Curse

### ISSUE THREAD

**Issue by skmzarn** [AcidWeb/CurseBreaker#1]
I found your program to be quite amazing, but I found out that you cannot get alpha versions from wowace.com/projects, where addon authors put up their beta/alpha version from Curse. I would love this as an option. Thanks!

**Comment by AcidWeb** [comment]
It is not connected with WowAce. CurseForge also support alpha versions. Currently CurseBreaker just ignore alpha versions. Not sure if, when and how that will change.

**Comment by skmzarn** [comment]
Yes, I know, it is not connected to WowAce, that's what I want to be able to get alphas. I didn't express myself good enough. You're right though, it can be accessed to alphas via CurseForge, but I think that's up to the addon author if that's the case or not, otherwise you need to get to the project site to get alphas. This is the only thing that keeps me from not using your program, because I need to get betas and alphas for some addons.

It is really awesome that you can get updates from both curse and wowinterface, which is a big plus. Thanks for your time.
