### ISSUE TITLE
Addon from WoW Interface get overwritten by a different addon

### ISSUE THREAD

**Issue by bbnn12** [AcidWeb/CurseBreaker#100]
currently have this addon installed: https://www.wowinterface.com/downloads/info24349-SpankysMarkingBar.html#info
for some reason every time i do an import install or update it gets overwritten by this addon: https://www.curseforge.com/wow/addons/markingbar

**Comment by AcidWeb** [comment]
Well it is detected as "Marking Bar" as use the same directory name as "Spanky's Marking Bar". `import` check only CurseForge for addons.
After import `uninstall` it and `install` version from WoWI.

**Comment by bbnn12** [comment]
will it still auto update or i'd have to manual update it?

**Comment by AcidWeb** [comment]
It will still auto-update.
