### ISSUE TITLE
Problem with Curseforge addons

### ISSUE THREAD

**Issue by Miteshu** [AcidWeb/CurseBreaker#101]
When trying to install an addon from Curseforge i get the following error:

RuntimeError: Failed to parse addon data: not well-formed (invalid token): line 41, column 85

It does not matter which addon i try. Installing from wowinterface or elvui works though.

**Comment by Miteshu** [comment]
So, i found out what the problem is:

Using autocomplete on cf:"addonname" will make it cf:cf:"addonname". Just using the addon name without cf: lets the addon install correctly.

**Comment by AcidWeb** [comment]
Yeah there is something wrong with parsing the colon character.

**Comment by AcidWeb** [comment]
OK. Found the cause.
