### ISSUE TITLE
[Feature request] Disable auto-update of CurseBreaker

### ISSUE THREAD

**Issue by Neurotoxin001** [AcidWeb/CurseBreaker#102]
Can you please make it possible to disable the automatic update of the program? Or at least ask if I agree to make an automatic update before starting the automatic update.

**Comment by AcidWeb** [comment]
No. I consider not updating stuff as anti-pattern. I rather force feed users with updates like Windows 10.

**Comment by Neurotoxin001** [comment]
> I rather force feed users with updates like Windows 10.
But even in W10 we can disable auto-updates via group policy.

**Comment by AcidWeb** [comment]
OK. What is your usercase when you don't want to run latest version of this tool?

**Comment by Neurotoxin001** [comment]
> OK. Under what circumstances you don't want to run latest version of this tool?

I'm just want to check it on virustotal before update

**Comment by AcidWeb** [comment]
Starting from next release auto-updater will be disabled if application will detect `CURSEBREAKER_VARDEXMODE` environment variable.

**Comment by Neurotoxin001** [comment]
I put `CURSEBREAKER_VARDEXMODE` in environments, but cursebreaker is still trying to auto update.
![image](https://user-images.githubusercontent.com/39812401/92082382-24d15a80-edcd-11ea-9ec0-7d632751b05e.png)

**Comment by AcidWeb** [comment]
This feature was implemented in v3.9.4. So it will block next updates.
