### ISSUE TITLE
Auto-complete when typing a list for the install command

### ISSUE THREAD

**Issue by malicyn** [AcidWeb/CurseBreaker#104]
When doing the install command, it is sometimes neccessary to list a number of addons, for instance DBM with older content or HandyNotes with different plugin modules.  When using `install` the initial addon you type will provide a dropdown and filter as you type.  If you add a comma to add a second addon, no suggestion for auto-fill/completion is given.

**Suggested Enhancement**
Have the suggestion and auto-completion function be usable after adding a comma to the install command to easily string together multiple addons without having to either construct the install string outside or doing the installs one at a time.

**Comment by AcidWeb** [comment]
Help is outdated. Just use space instead of a comma - prompt will start new auto-completion.
