### ISSUE TITLE
Feature request: Function to update plater scripts/mods from wago.io

### ISSUE THREAD

**Issue by Beet4** [AcidWeb/CurseBreaker#105]
Hi!

Awesome work on this application, currently switching from the Twitch app before it closes down. :)

Plater and the WeakAuras companion app was recently updated to support updating scripts, mods and profiles for plater from wago.io similiar to how the companion app and CurseBreaker updates WeakAuras from wago.io. 

I would love to have the ability to have the same function in CurseBreaker. That would mean there was no more use for the WeakAuras companion app at all. 👍 

From the Plater discord:

Plater Nameplates
- Now has full support to WeakAuras-Companion app, you can update your mods/scripts AND profiles directly from wago.io as you already do with your WA Auras!
Get the app here: https://weakauras.wtf/ and Get auras and mods from the amazing mod creators community at wago.io

**Comment by AcidWeb** [comment]
It is on my TODO list. But it is a major headache.

**Comment by Beet4** [comment]
> It is on my TODO list. But it is a major headache. And fact I never used Plater is not helping :-P

Cool! :) Let me know if you need help with testing or anything.

**Comment by cont1nuity** [comment]
If you need help on Plater.lua parsing, let me know.
But we discussed this... Rework first. :)
