### ISSUE TITLE
Uninstalling an addition for an addon uninstalls the main addon instead

### ISSUE THREAD

**Issue by Beet4** [AcidWeb/CurseBreaker#106]
When uninstalling additions to other addons that start with the same name uninstalls the main addon instead. For example Elvui Adibags uninstalls Elvui and Handynotes: Visions of N'Zoth uninstall Handynotes. See screenshots below.

![image](https://user-images.githubusercontent.com/38279393/88339162-dc3c7100-cd39-11ea-8dbc-7abc01e750e8.png)

![image](https://user-images.githubusercontent.com/38279393/88339204-ea8a8d00-cd39-11ea-881f-8fc847c4d87e.png)

**Comment by AcidWeb** [comment]
🤦
