### ISSUE TITLE
Better handling of removed CurseForge projects.

### ISSUE THREAD

**Issue by btnmasher** [AcidWeb/CurseBreaker#107]
For some reason or another, an addon I use was removed from CurseForge. To where it went I do not know, but it's become a blocker for updating my addons via CurseBreaker (Something about project can't be parsed). The only option is to run an `uninstall` command to "de-register" it from CurseBreaker. However, I want to keep using the addon. If I had ran the `uninstall` command without having the wherewithal to first make a copy of it I would've lost access to it completely. Copying it back, it's just treated as an unknown addon and is ignored properly.

I suggest that in the event of an addon disappearing in this way and leaving CurseBreaker unable to update, that there should exist a command to "unregister" that addon from automatic updates without uninstalling/deleting it entirely.

**Comment by AcidWeb** [comment]
Yeah. It should handle deleted (and renamed) projects better. Fortunately it is edge-case.

**Comment by JunZuloo** [comment]
The ability to switch update source from CF to say, wowi would also be appreciated, maybe not completely necessary at this point in time. But worth looking into if CF gets moved a different URL now that it's been sold to OverWolf. also nice if an addon removed from cf can be added back in after having been "unregistered".

**Comment by AcidWeb** [comment]
There are multiple technical difficulties to properly detect deleted or renamed CF projects.
Implementing proper switching between sources is not worth the effort.

I probably add a flag to `uninstall` command to keep files intact after removing the addon from CB database.
And I'm still thinking about better handling of missing projects in general - they should not block update process.
