### ISSUE TITLE
 Altoholic-Retail (Teelo's Fork) not updating

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#109]
Over a month and 8 versions out of date:
https://i.imgur.com/xBkT387.png

**Comment by AcidWeb** [comment]
Upload here yours `CurseBreaker.json`

**Comment by teelolws** [comment]
My bad. I'll be updating WoWI more often now.

**Comment by MrUzagi** [comment]
Would it be an idea to include the source in the output so it's easier to see where CurseBreaker is actually looking for new versions? Either by prepending the name with "cf:", "wowi:" etc, or inserting a column before the addon name.

Come to think about it, it might be useful to be able to have more than one source for an addon that might be updated sporadically in different places. But I imagine that might be an edge case as well.

**Comment by AcidWeb** [comment]
I definitely not planning to add pulling addon from multiple sources at once - it is a bottomless rabbit hole.

I think that original issue was solved so I'm closing this ticket.

**Comment by teelolws** [comment]
Multiple sources can be annoying, but I agree that putting a shorthand of the source in the chatlog would be helpful.
