### ISSUE TITLE
TukUI\ElvUI

### ISSUE THREAD

**Issue by evereskan** [AcidWeb/CurseBreaker#11]
First of all, I want to thank you for great program. Use it on daily basis and it is gorgeous. But I can not figure out how to download this type addon from TukUI https://www.tukui.org/addons.php?id=3 what command should I use to get it from Tuk ? Right now I only can get Elvui\Tukui and not other addons on their site tho, So I don not this is issue, or I simply can not find how, if it not possible, can this feature can be requested ? I know many addon from Elvui (expect Elvui and Tukui obviously) are on cursepage and can be downloaded via this beautiful programm. But some are only available through their site.
Thank you in advance

**Comment by AcidWeb** [comment]
Currently it is not supported. It might change in the future.

**Comment by evereskan** [comment]
Thank you for answer. Will wait for this feature
