### ISSUE TITLE
Colors and progress bars missing with 3.7.0

### ISSUE THREAD

**Issue by Jeremy7600** [AcidWeb/CurseBreaker#110]
Colors are gone and there are no progress bars anymore:

![image](https://user-images.githubusercontent.com/62718826/88461399-a9dd6180-ce68-11ea-8934-a7953785f6a1.png)

**Comment by AcidWeb** [comment]
I presume you fixed it? What cause that?

**Comment by Jeremy7600** [comment]
Unsure what caused it. These were my 1st symptoms: extra characters when typing, no auto-complete (didn't know I was missing autocomplete cause I didn't know it was a feature). You couldn't recreate the extra characters issue so I just kept using it. Then with 3.7 the colors and progress bars went away. I refreshed windows (installed it in place on top of itself) and all the issues are gone.
