### ISSUE TITLE
[v3.9.0] "Press any key to continue..." after auto-updating all addons has few minutes delay, related to WTF backup not showing

### ISSUE THREAD

**Issue by MrAntrophy** [AcidWeb/CurseBreaker#115]
Ever since v3.9.0 the window that lists all addons that were updated doesn't have "Press any key to continue..." after automatic update is finished, I tried to have it opened for some time and after 4-5 minutes it reappears, until then you have to force close the window (using X).

WTF backup text went missing completely as well so I think the problem is related to that. See screenshot for reference.

Stuck on status window with nothing going on for 5 minutes:
![d4SYkJI](https://user-images.githubusercontent.com/34379991/89099646-2d5efb80-d3f1-11ea-8e0b-2e061a857c07.png)

After 5 minutes of waiting "press any key to continue..." reappears without any sign of WTF backup:
![reappeared](https://user-images.githubusercontent.com/34379991/89099703-8169e000-d3f1-11ea-8160-c51c3864829c.png)

**Comment by AcidWeb** [comment]
Not related with CurseBreaker at all. Wago is working very slowly today. Multiple very slow attempts cause this delay.

I will close this bug after it this issue will be resolved.

**Comment by AcidWeb** [comment]
It should be solved now.
