### ISSUE TITLE
avoid installing 9.0 addons on the retail 8.3 client

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#116]
Please try to avoid installing 9.0 addons on the retail 8.3 client.

I just had to downgrade Litemount from the 9.0. alpha version.

**Comment by AcidWeb** [comment]
In current state of CF API you can't reliably detect that.

**Comment by AcidWeb** [comment]
Closing this as there is no way to implement this without parsing entire addon archive. Version detection in API endpoints is just crippled by bugs.
