### ISSUE TITLE
Feature request: In automatic mode, sort updated addons to be at the bottom

### ISSUE THREAD

**Issue by comiluv** [AcidWeb/CurseBreaker#118]
Automatic mode shows addon list identical to that you can see what status command reports, but this makes reading through addons list bothersome to see which addon is updated and whats not.
To improve this, it can be done in 2 ways:
1. Sort updated addons to be at the bottom of the status report in automatic mode.
2. Option to hide Up-to-date addons in status report in automatic mode

**Comment by AcidWeb** [comment]
`toggle_compact_mode`

**Comment by comiluv** [comment]
Man, all the improvement idea I though idea seems be already included! Great app
