### ISSUE TITLE
Problem when installing classic addons

### ISSUE THREAD

**Issue by alexqu0822** [AcidWeb/CurseBreaker#12]
For classic wow , when updating, error printed :
Failed to parse addon data. There is some issue with the website or this addon don't have release for your client version.

How could I solve it?

**Comment by AcidWeb** [comment]
Which addon?

**Comment by alexqu0822** [comment]
All addons....
DBM Atlas Dominos Detail Bagnon WA Recount .... and many others.
Did a 200ms lag influence?

**Comment by AcidWeb** [comment]
Send me e-mail with your `CurseBreaker.json` file.

**Comment by alexqu0822** [comment]
{
    "Addons": [],
    "Backup": {
        "Enabled": true,
        "Number": 7
    },
    "CurseCache": {},
    "Version": "2.3.1",
    "WAAPIKey": "",
    "WAAccountName": "",
    "WACompanionVersion": 0,
    "WAUsername": ""
}

**Comment by AcidWeb** [comment]
You have no addons installed. So how update is failing?

**Comment by alexqu0822** [comment]
I war installing addons not updating. :P

CB> install cf:deadly-boss-mods
0/1 |                                                                                             |

Failed to parse addon data. There is some issue with the website or this addon don't have release for your client version.
CB> install cf:questie
0/1 |                                                                                             |

Failed to parse addon data. There is some issue with the website or this addon don't have release for your client version.
CB> install cf:recount
0/1 |                                                                                             |

Failed to parse addon data. There is some issue with the website or this addon don't have release for your client version.

**Comment by AcidWeb** [comment]
Everything is working correctly on my end.
Check if https://addons-ecs.forgesvc.net/api/v2/addon/334372 is working for you.

**Comment by alexqu0822** [comment]
I deleted all files of breaker.
It works now~~~
Thank u for ur working!
