### ISSUE TITLE
Can't install addons from GitHub with classic-only releases

### ISSUE THREAD

**Issue by ankrause** [AcidWeb/CurseBreaker#122]
Using the CLI to install an addon from GitHub for the Classic client doesn't work if the addon publisher doesn't include "-classic" in the released zip file.

Version: 3.9.1

Tried using both:
```
CB> install gh:Aviana/LunaUnitFrames
0/1 | ───────────────────────────────────────────────────────────────────────────────────────── |
RuntimeError: Failed to parse addon data: Invalid URL 'None': No schema supplied. Perhaps you mea
http://None?
```

```
CB> install https://github.com/Aviana/LunaUnitFrames
0/1 | ───────────────────────────────────────────────────────────────────────────────────────── |
RuntimeError: Failed to parse addon data: Invalid URL 'None': No schema supplied. Perhaps you mea
http://None?
```

This particular addon publisher releases a zip file (and source files) called "LunaUnitFrames.zip". Since this addon is only for classic, they do not add "-classic" to their zip file to differentiate between a release for retail vs a release for classic.

The current logic for selecting which zip file to install from GH makes sense, but only in the case where the addon is either retail only or supports both retail and classic with separate zips.

In this instance, I would expect CurseBreaker to trust that the user is installing an addon from GitHub that supports classic and to select the one and only zip file for installation.

Additionally, this error is pretty vague for this scenario. It essentially fails because "None" is returned by the release asset selection logic and passed to the method that attempts to download/install the zip file. The HTTP implementation then throws this error because "None" is not a URL. CurseBreaker should probably throw/return a friendly message if it can't find a suitable zip to install.

**Comment by AcidWeb** [comment]
Logic to support this type of scenario is already implemented - It will fallback to retail ZIP if no classic release will be detected. But apparently there is a bug in GitHub payload parsing. And in this case is not detecting any release. I will investigate it.

Additionally you should be aware that "author" of LunaUnitFrames is a man who have no respect for any code licensing and this addon is based on "borrowed" code. That why he is banned on every WoW addon related page and he is distributing his work over GH. I would reconsider supporting this type of individual.

**Comment by ankrause** [comment]
Explains why it's not anywhere except GitHub, good to know, thanks.
