### ISSUE TITLE
switching to beta and then updating fails

### ISSUE THREAD

**Issue by cpjet64** [AcidWeb/CurseBreaker#126]
already have PUG Hero installed from curseforge and use the command toggle_dev PUG Hero then ran update 

CB> toggle_dev PUG Hero
Addon switched to the beta channel.
CB> update
0/130 | ─────────────────────────────────────────────────────────────────────────────────────── |
RuntimeError: Failed to parse addon data: Expecting value: line 1 column 1 (char 0)
CB>

**Comment by cpjet64** [comment]
i closed cursebreaker and reran the update command and it was successful.

**Comment by AcidWeb** [comment]
Sound like random issue with CF API. Let me know if that will appear again.
