### ISSUE TITLE
Error when attempting to run on Archlinux

### ISSUE THREAD

**Issue by Zeinder** [AcidWeb/CurseBreaker#127]
Traceback (most recent call last):
\u256d\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256e
\u2502 File "CurseBreaker.py", line 724, in <module>                             \u2502
\u2502 File "CurseBreaker.py", line 54, in start                                 \u2502
\u2502 File "CurseBreaker.py", line 241, in print_header                         \u2502
\u2502 File "rich/console.py", line 879, in print                                \u2502
\u2502 File "rich/console.py", line 448, in exit                             \u2502
\u2502 File "rich/console.py", line 426, in _exit_buffer                         \u2502
\u2502 File "rich/console.py", line 993, in _check_buffer                        \u2502
\u2570\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256f
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 5-32:
range(256)
[38473] Failed to execute script CurseBreaker

**Comment by AcidWeb** [comment]
You running binary version yes? You using non utf-8 enviroment?

**Comment by Zeinder** [comment]
LANG=en_US.ISO-8859-1
LC_CTYPE="en_US.ISO-8859-1"
LC_NUMERIC="en_US.ISO-8859-1"
LC_TIME="en_US.ISO-8859-1"
LC_COLLATE="en_US.ISO-8859-1"
LC_MONETARY="en_US.ISO-8859-1"
LC_MESSAGES="en_US.ISO-8859-1"
LC_PAPER="en_US.ISO-8859-1"
LC_NAME="en_US.ISO-8859-1"
LC_ADDRESS="en_US.ISO-8859-1"
LC_TELEPHONE="en_US.ISO-8859-1"
LC_MEASUREMENT="en_US.ISO-8859-1"
LC_IDENTIFICATION="en_US.ISO-8859-1"
LC_ALL=

**Comment by AcidWeb** [comment]
Yeah. `ISO-8859-1` is definitely not supported. You can try to run the application from sources but you should rather switch entire system to UTF-8 locale.

This is not an issue with application.

**Comment by Zeinder** [comment]
Getting the locale to change is arguing with me, but I managed to get it to at least be set for that terminal window. Seems to be working now.
