### ISSUE TITLE
Runtime Error: Failed to Parse Addon Data

### ISSUE THREAD

**Issue by lucasnbraga** [AcidWeb/CurseBreaker#128]
Gives me a code 3358, I cannot understand what addon that is and so i cannot fix it.

└────────────────────────────────────────────────────┘
RuntimeError: Failed to parse addon data: 3358
The project could be removed from CurseForge or renamed. Uninstall it (and reinstall if it still
exists) to fix this issue.

**Comment by bloodstrike** [comment]
Just had this start happening myself, came here to report it.

**Comment by AcidWeb** [comment]
What command returned that error? It should display project name not ID.
https://addons-ecs.forgesvc.net/api/v2/addon/3358

Last few hours CF API have some issues and calls fail randomly.

**Comment by lucasnbraga** [comment]
just the status command, randomly like @bloodstrike commented it stopped showing.

I have no idea why, maybe one addon hosted on curseforge had issues? Strange that the name was not returned in order to identify it

**Comment by AcidWeb** [comment]
But it is working right now?

**Comment by lucasnbraga** [comment]
Yes it has since stopped, but makes me wonder if there was something wrong on curseforge's end that we could identify via the error code.

Thanks for the reply

**Comment by AffectiveGnome** [comment]
Im getting this issue too, allow error code 305235.
Is there a way to mass reinstall ?

**Comment by AcidWeb** [comment]
Show entire error.

**Comment by AffectiveGnome** [comment]
RuntimeError: Failed to parse addon data: 305235
The project could be removed from CurseForge or renamed. Uninstall it (and reinstall if it still
exists) to fix this issue.

Have the following installed;
cf:all-the-things,cf:auctionator,cf:azeroth-auto-pilot,cf:can-i-mog-it,cf:deadly-boss-mod
s,cf:deadly-boss-mods-mop,cf:details,cf:gtfo,cf:handynotes,cf:handynotes-battle-for-azeroth-treas
ures,cf:handynotes-mechagon-nazjatar,cf:handynotes-universal-explorer,cf:handynotes-visions-of-nz
oth,cf:handynotes_draenortreasures,cf:handynotes_legiontreasures,cf:immersion,cf:leatrix-plus,cf:
my-role-play,cf:omni-cc,cf:rarescanner,cf:sexymap,cf:tomcats,cf:tomcats-tours-mechagon,cf:tomtom,
cf:world-quests-list

**Comment by AcidWeb** [comment]
CF API still have issues. Just wait few hours.

**Comment by AffectiveGnome** [comment]
wilco.

thanks for the response!

**Comment by AcidWeb** [comment]
I confirmed the issue with CF API. It stopped providing data about some addons. Rest of calls can randomly fail too. It definitely looks like technical problem on their side.

Additionally I need to investigate why CurseBreaker is not providing full project name in error message.
