### ISSUE TITLE
Symbolically linked folder not used by CB. 

### ISSUE THREAD

**Issue by ZyborgRSA** [AcidWeb/CurseBreaker#129]
I currently use a Symbolically linked folder to backup my WTF folder to github however CB does not see the linked folder. Was trying to clean up orphaned LUAs but CB wasn't finding any in my linked folder. Checked the backup as well and the folder is not in the backup. Not sure if there are limitations on the app seeing into links or not.

**Comment by AcidWeb** [comment]
Windows or Linux?

**Comment by ZyborgRSA** [comment]
Apologies, this is on Windows

**Comment by AcidWeb** [comment]
Well this type of issues are not a suprise. Not sure if I will fix it.

**Comment by AcidWeb** [comment]
Both features were just simply ignoring the links. It will be fixed in next release.
