### ISSUE TITLE
RuntimeError: Failed to parse addon data / Missing updates

### ISSUE THREAD

**Issue by AcidWeb** [AcidWeb/CurseBreaker#130]
For the last 48h CurseForge API has some issues that cause random failures of addon updates.
Additionally even if call is successful there is no guarantee that it contain current data.

We can only wait for a fix. As nature of these issues doesn't allow us to implement any workaround.

**Comment by Valmere** [comment]
Could this also be why it isn't updating DBM for WoW Classic? Their latest release is 1.13.56 but CurseBreaker is still showing 1.13.55 as up-to-date, even after using force update.

**Comment by AcidWeb** [comment]
Yes. CF API currently can return different version data for different people.

**Comment by runew0lf** [comment]
Also having an issue, Clique, Postal and Scrap are all erroring for me!

**Comment by AcidWeb** [comment]
You can only wait and try later.

**Comment by AcidWeb** [comment]
Apparently most of errors is gone but API still can deliver out-of-date payloads.

**Comment by runew0lf** [comment]
Not recieved any errors in the last 2 days buddy, looks like it was on twitch's end

**Comment by AcidWeb** [comment]
Well it was on Twitch end. That was certain from the beginning. But yes - it looks like everything returned to normal. I will disable warning tommorow.
