### ISSUE TITLE
Bypass auto-update

### ISSUE THREAD

**Issue by jgwallace3** [AcidWeb/CurseBreaker#131]
OK. Under what circumstances you don't want to run latest version of this tool?

_Originally posted by @AcidWeb in https://github.com/AcidWeb/CurseBreaker/issues/102#issuecomment-662411628_

**Comment by AcidWeb** [comment]
If you have doubts about security of binaries that are created by me feel free to run it from sources or make your own.

**Comment by jgwallace3** [comment]
Wow. Didn't realize it had posted that, Meant to elaborate.

With the issue of not currently being able to connect to curseforge, I attempted to try to an older version (a regression test) to see if it was my connection or the software.

If anyone sees a change in behavior from your program, wouldn't you want them to be able to compare to previous results?

**Comment by AcidWeb** [comment]
Starting from next release auto-updater will be disabled if application will detect `CURSEBREAKER_VARDEXMODE` environment variable.

**Comment by jgwallace3** [comment]
TY
