### ISSUE TITLE
Won't update addons

### ISSUE THREAD

**Issue by genezizs** [AcidWeb/CurseBreaker#132]
soo, i've had this installed for about 2 days!  and for the life of me, it won't fetch updates at all for me! 

As of now, i know there are atleast 2 updates availible for DBM and Details!  

CB says that DBM 8.3.30 is up to date! but infact the correct patch is 8.3.31 ( keeps telling me ingame that an update is availible)

For details!  CB says that 8.3.0.7354.141 is up to date, but DetailsRetail.8.3.0.7356.141  is the correct one! ( keeps telling me ingame that an update is availible)

i'm pretty sure there are other updates availible too! i just havent checked them all yet!  is this a thing? like, is CB really slow at fetching updates?  or is there something up on my end?   it installs addons just fine, and everything else works!  if i run a Force_update (addon name)  it does infact grab the correct update! but it seems like that's a really hard way of going about stuff! if i have to do that on every single update :o

**Comment by ZyborgRSA** [comment]
Is it giving you the failed to parse addon data error? Curse API is giving issues at the moment as per the Pinned Issue, not sure if it's been resolved but I've been having same issue.

**Comment by ZyborgRSA** [comment]
Looks like I'm no longer giving issues, ignore me :)

**Comment by genezizs** [comment]
i had those too! but they solved themselves!  but addons are deffo not updating at all! ):  hopefully it gets fixed! :D

**Comment by AcidWeb** [comment]
It is also caused by #130. Even if API call is successful you not always get current data.
