### ISSUE TITLE
Orphans command reporting files in use as orphaned

### ISSUE THREAD

**Issue by bartuszekj** [AcidWeb/CurseBreaker#133]
The `orphans `command appears to be reporting some files that are currently used by certain addons. Namely, the file reported below is in active use by the Prat addon:

```
CB> orphans
Directories that are not part of any installed addon:
CustomCorruptionIcons
WeakAurasCompanion

Files that are leftovers after no longer installed addons:
Account\<AccountNumber>#1\<RealmName>\<CharacterName>\SavedVariables\Prat-3.0.lua
Account\<AccountNumber>#1\SavedVariables\Prat-3.0.lua
CB>
```

I verified that the timestamps and contents of both instances of the Prat-3.0.lua files listed above are being updated during/after each wow session.

**Comment by AcidWeb** [comment]
This clearly a bug. I will fix it in next release.
