### ISSUE TITLE
Feature Request: Info <modname>

### ISSUE THREAD

**Issue by runew0lf** [AcidWeb/CurseBreaker#134]
What this would do is pull down a description of the mod (should be available from the api) and display it for the user

**Comment by AcidWeb** [comment]
I will think about it.

**Comment by AcidWeb** [comment]
Nah. Same problem as changelogs. Too much re-parsing is needed to make them readable or to make them look as author indented. This feature is simply not worth the required work.

Generally CB was never intended as tool to browse addons.

**Comment by runew0lf** [comment]
yeah i looked at changelogs before in the curse api, its very inconsistent
and is generally a free for all in there!, i see what you mean with the
description too. It was just a thought that popped into my head!
