### ISSUE TITLE
Github Installation method Results in RuntimeError: Failed to parse addon data:

### ISSUE THREAD

**Issue by BrianMiltonJr** [AcidWeb/CurseBreaker#135]
Hello! I'm developing a WoW addon and just fell in love with your application. I wanted to make sure your application supported my addon. Also have you looked into a rewrite with NodeJS or Deno? I think it would be a fun project! Anyway onto my problem!!

Whenever I run `install gh:BrianMiltonJr\AutoResurrect` it doesn't even find the release even though it does exist. But whenever I use `install https://github.com/BrianMiltonJr/AutoResurrect/releases/tag/v0.0.1-alpha` or `install https://github.com/BrianMiltonJr/AutoResurrect/releases` It just Fails to Parse Addon Data. I have a feeling it has something to do with how the strings are being parsed. I'm currently working on swapping it to use whatever the Python3 Equivalent of a NodeJS buffer is.

But even if you make it through parsing the URL, it looks to be that you only want to download assets from a release on github Not the actual zip/tarball that is generated automatically. Is this a design philosophy, or did it just happen to end up that way since GH is probably not one of the higher priorities if I had to imagine. I could understand for Binaries and maybe compiled/transpiled this working well, but for WoW addons there's really no need. Since it's all JIT. I tried minifying just so I would have something on my assets, but the script still crashed (Probably cause i'm working in it now)

I know this is more of asking you about the project and reporting a couple bugs, but i'm really interested in this project and would love to get my toes wet. Sorry if it seems that I am trashing your work or sounding really rude. I have been up a while working, and decided to relax writing wow addons and stumbled across your application. I really love the whole vibe of it (Besides the Python part, but I can learn to breathe in it).

Thank you for reading, i'm currently right now working on changing the GH flow. Please let me know if there's some reason why it's like this or not! Have a great day!!!!!

(Ps you should look into NodeJS / Deno. You seem like a big Python person, but Goddamn you can write some pretty neat lean functions.)

**Comment by AcidWeb** [comment]
I answered you on Discord.
