### ISSUE TITLE
all addons showing as "Modified"

### ISSUE THREAD

**Issue by Kazlehoff** [AcidWeb/CurseBreaker#136]
When i started my computer today, all my addons were showing thusly.

is this due to the silly API thing

![image](https://user-images.githubusercontent.com/52207847/90337130-7b0d6380-dfae-11ea-9959-86f3f6e58db4.png)

**Comment by AcidWeb** [comment]
No. Some external source modified all directories in bulk.

**Comment by Kazlehoff** [comment]
interesting. thanks. i'll look at reinstalling them

**Comment by Kazlehoff** [comment]
How can i reinstall my addons without uninstalling them first?

install cf:dbm-voicepack-vem -i failed to parse addon data (assuming -i is in the wrong place)
install -i cf:dbm-voicepack-vem addon already installed

**Comment by Kazlehoff** [comment]
using force_update to reinstall all my addons seems to have fixed the issue.

this morning, i plugged an extra HDD into my system to clone my 2TB HDD to a replacement drive. at no point was my Games ssd touched. but when i rebooted, i noticed i had to run repairs on wow, battle.net, and steam. very interesting. in any case, all seems right with the universe once more. thank you for your assistance, and great app :) 🥇
