### ISSUE TITLE
Addon in curseforge not showing releases in cursebreaker

### ISSUE THREAD

**Issue by cpjet64** [AcidWeb/CurseBreaker#138]
Just uploaded a addon as a release version to curseforge but when i go to install it with cursebreaker it says it doesnt have any releases. 

https://prnt.sc/u7pvh3

https://www.curseforge.com/wow/addons/adibags-keystones/files

**Comment by AcidWeb** [comment]
That is quite normal. It may take several hours to propagate new file. It is affecting Twitch Client too.

It is already working.
