### ISSUE TITLE
Just started crashing

### ISSUE THREAD

**Issue by pilotstew** [AcidWeb/CurseBreaker#140]
Worked without issue until updating today. Now crashing with error on Arch Linux:

UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-73: ordinal not in range(128)

Python Traceback:

\u256d\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256e
\u2502 File "CurseBreaker.py", line 738, in <module>                                                    \u2502
\u2502 File "CurseBreaker.py", line 57, in start                                                        \u2502
\u2502 File "CurseBreaker.py", line 253, in print_header                                                \u2502
\u2502 File "rich/console.py", line 902, in print                                                       \u2502
\u2502 File "rich/console.py", line 447, in __exit__                                                    \u2502
\u2502 File "rich/console.py", line 425, in _exit_buffer                                                \u2502
\u2502 File "rich/console.py", line 1022, in _check_buffer                                              \u2502
\u2570\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256f

**Comment by AcidWeb** [comment]
Upload yours `WTF/CurseBreaker.json`. When exactly you see that error?

**Comment by pilotstew** [comment]
Error shows up on launch

[CurseBreaker.zip](https://github.com/AcidWeb/CurseBreaker/files/5152642/CurseBreaker.zip)

**Comment by AcidWeb** [comment]
Can't replicate this issue. Show me output of `locale` command from console that is used to start CB.

**Comment by pilotstew** [comment]
That was the issue. Corrupted locale. Reran locale-gen and CurseBreaker is back. 

Thank you sir and thank you for this incredible work.

**Comment by AcidWeb** [comment]
👍
