### ISSUE TITLE
Failed to find release for your client version.

### ISSUE THREAD

**Issue by MichaelBLaursen** [AcidWeb/CurseBreaker#141]
I'm trying to figure out how to install addons that doesn't have a -Classic tag on their source. So I assume this is the cause of the issue when trying to install or important addons like "GatherMate2" or "Trinket-Menu" which both returns this error:

RuntimeError: Failed to parse addon data: GatherMate2.
Failed to find release for your client version.

How to install these kind of addons?
I tried to use the -i parameter to ignore client version. But then I get a message saying the project is removed from CurseForge, which GatherMate2 shouldn't be.

**Comment by AcidWeb** [comment]
Exactly what command you trying to execute.

**Comment by AcidWeb** [comment]
https://www.curseforge.com/wow/addons/gathermate2-classic
https://www.curseforge.com/wow/addons/trinketmenuclassic
