### ISSUE TITLE
Cannot run on Linux after latest update

### ISSUE THREAD

**Issue by aapoalas** [AcidWeb/CurseBreaker#143]
After CurseBreaker updated itself (re-downloading didn't help) the program cannot run, instead it exits with the following stacktrace:

> Traceback (most recent call last):
> \u256d\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256e
> \u2502 File "CurseBreaker.py", line 738, in <module>                                                    \u2502
> \u2502 File "CurseBreaker.py", line 57, in start                                                        \u2502
> \u2502 File "CurseBreaker.py", line 253, in print_header                                                \u2502
> \u2502 File "rich/console.py", line 902, in print                                                       \u2502
> \u2502 File "rich/console.py", line 447, in __exit__                                                    \u2502
> \u2502 File "rich/console.py", line 425, in _exit_buffer                                                \u2502
> \u2502 File "rich/console.py", line 1022, in _check_buffer                                              \u2502
> \u2570\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u256f
> UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-97: ordinal not in range(128)
> *** You may need to add PYTHONIOENCODING=utf-8 to your environment ***
> [2453] Failed to execute script CurseBreaker

Setting `export PYTHONIOENCODING=UTF-8` does not actually allow the program to run.

**Comment by AcidWeb** [comment]
You are not using UTF8 locale. Duplicate #140.
