### ISSUE TITLE
Unhandled exception in event loop:

### ISSUE THREAD

**Issue by Beastbludd** [AcidWeb/CurseBreaker#145]
Getting this very randomly when installing addons or doing 'status' 

> Unhandled exception in event loop:
>   File "asyncio\proactor_events.py", line 768, in _loop_self_reading
>   File "asyncio\windows_events.py", line 808, in _poll
>   File "asyncio\windows_events.py", line 457, in finish_recv
> 
> Exception [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
> Press ENTER to continue...

**Comment by AcidWeb** [comment]
No idea what cause that.

**Comment by Beastbludd** [comment]
Seemed to have happened after I updated Windows 10 to the new 2004 version, I'll go back to previous version see if it fixes it.

**Comment by AcidWeb** [comment]
No need. I use 2004 for long time.

**Comment by Beastbludd** [comment]
I have reimaged my HDD to previous version and redownloaded Cursebreaker, have been unable to replicate the error since so not sure what was going on but sorry if I wasted your time, issue seems to be on my end rather than with Cursebreaker, keep up the great work 💯

**Comment by AcidWeb** [comment]
Reopening this as apparently more than one person had this issue. Need to investigate.

**Comment by AcidWeb** [comment]
https://bugs.python.org/issue39010#msg362076
