### ISSUE TITLE
Automatic update on 'modified' addons

### ISSUE THREAD

**Issue by Benzoyl** [AcidWeb/CurseBreaker#147]
Thank you for such great and convenient tool.

1. Is there a way for modified addons to be updated automatically as others without using forced_install command?
2. Is there a way to set different update conditions for each addon? For instance, turn on automatic update on unmodified/modified addon A but not unmodified/modified addon B.

**Comment by AcidWeb** [comment]
No. Entire point of addons with modified status is disabling autoupdating of them.

**Comment by Benzoyl** [comment]
I see. Thank you very much. I just wanted to know because for certain addons I need to overwrite fonts only for language purpose, and Cursebreaker and font overwrite are automated by using windows scheduler.
