### ISSUE TITLE
Many addons - scroll issue

### ISSUE THREAD

**Issue by V1P3R** [AcidWeb/CurseBreaker#148]
I have a plethora of addons to update and the Cursebreaker client will only scroll back a couple of screens, so I cannot check the status of all my addons upon update. Can you increase the scroll maximum-history, please?

Thanks!

**Comment by MaxMcBurn** [comment]
oh yes, that would be nice!!
+1

**Comment by AcidWeb** [comment]
That limitation there is for reason.

I highly suggest to switch to https://github.com/microsoft/terminal
