### ISSUE TITLE
Self update on MacOS using CURSEBREAKER_PATH

### ISSUE THREAD

**Issue by bloodstrike** [AcidWeb/CurseBreaker#151]
I have CurseBreaker installed in /usr/local/bin/ and have set CURSEBREAKER_PATH to '/Applications/World of Warcraft/\_classic\_/'. When CurseBreaker self-updates, the original file is deleted from /usr/local/bin/, but the new file is installed to /Applications/World of Warcraft/\_classic\_/. It would be helpful if when updating, Cursebreaker is left where it was installed.

Additionally, the new version is not set as executable by default - not sure if this is related.

**Comment by AcidWeb** [comment]
Strange. It should be marked as executable by default.

**Comment by AcidWeb** [comment]
Yeah. macOS updater is not correctly with `CURSEBREAKER_PATH` set. That cause both issues.
It will be fixed in next release (so it will start to work correctly in two).
