### ISSUE TITLE
Allow force_update to behave like regular update command

### ISSUE THREAD

**Issue by eyriewow** [AcidWeb/CurseBreaker#153]
Currently the `force_update` command differs in behavior from the `update` command which is unintuitive, in my opinion.

When run without any arguments the `update` command will try to fetch updates for every currently installed addon while the `force_update` command will not work at all unles provided with an addon name.

This can be especially annoying in [situations like the one I just ran into](https://i.imgur.com/mI4zA9W.png) where half my addons showed up as modified (without me actually having modified anything).

**Comment by AcidWeb** [comment]
First of all - something modified them. If they switched to modified state it means that something changed directory contents after it was installed by CB. This is not an error.

Generally you are right but during normal usage of application you should not need to execute `force_update` in bulk. It will think about adding proper option with additional confirmation.

**Comment by eyriewow** [comment]
> First of all - something modified them. If they switched to modified state it means that something changed directory contents after it was installed by CB. This is not an error.

You're correct of course.   

The AddOns showed up as modified because I use git to manage my WoW interface and recently added a new branch to work on my UI for Shadowlands. I assume switching between branches triggered something that CB recognized as the AddOns having been modified. 

What I meant was I didn't make any deliberate modification so running a bulk `force_update` on every installed addon would not be a problem for my particular case here. I do recognize that this could be an issue for people who *do* actually deliberately modify their AddOns. So I think an additional "Are you sure you want to do this Y/N" prompt would be appropriate.

**Comment by AcidWeb** [comment]
Yeah that could trigger modified status.
