### ISSUE TITLE
Cannot uninstall addon with special characters in name

### ISSUE THREAD

**Issue by jsmylnycky** [AcidWeb/CurseBreaker#154]
Hello!

I was trying to uninstall an addon (PersoLootRoll) but it just instantly finishes and doesn't actually get rid of it.

When I autocomplete the uninstall command, it resolves to: 

`uninstall "PersoLootRoll (PLR, Personal Loot Roll)"`

I'm assuming one of the special characters in that string is conflicting with the uninstall command.

Thanks :)

**Comment by AcidWeb** [comment]
Eh. It should work with quotation marks - that why I added them. I will check it out.

**Comment by AcidWeb** [comment]
It will be fixed in next release. Quotation marks will not be required.
