### ISSUE TITLE
WeakAuras updating regardless of client version

### ISSUE THREAD

**Issue by marco-kretz** [AcidWeb/CurseBreaker#155]
Hey!

At first thanks for your hard work, love the application :)

A bug I noticed:

I just run the updater and it updated some of my WAs to the corresponding 9.0.1 version which broke my UI. I had to go to wago.io and install the older 8.3 version of it. Is there any setting and/or function to respect the client version when updating WAs?

**Comment by AcidWeb** [comment]
Can't do anything about it. If somebody updated BFA aura with SL version there is no way to detect it.
