### ISSUE TITLE
Request: Bypass 5 second auto-update

### ISSUE THREAD

**Issue by Saxayone** [AcidWeb/CurseBreaker#156]
Would rather bypass the auto-update and check things manually.
With Shadowlands coming I somewhat expect at least a few broken addon updates and would rather pick and choose what gets updated each time.
This way I can also auto-open when I start-up w/o having to worry about every addon auto-updating.

**Comment by AcidWeb** [comment]
You can press any button to enter interactive mode. Execute `status` command to check addon state and then manually update them with `update` command.

Also due to nature of 9.0 changes it is much more likely that not updated addons will be broken than updated ones.

**Comment by Saxayone** [comment]
I know how to do it, was asking if there was a way to just automatically goto the manual side w/o having to do the press button every time I start up cursebreaker. I've never liked automatically updating all my addons.
Already had cursebreaker update all my addons and get rid of all my custom edits to various addons.

**Comment by AcidWeb** [comment]
Yeah as documentation states it reinstalls all addons during initial import. But now if it detect any manual changes it will automatically block auto-update of any modified manually addon.

Anyway - No. Currently there is no way to automatically switch to interactive mode. I will add it in one of upcoming releases.
