### ISSUE TITLE
Task Scheduler

### ISSUE THREAD

**Issue by nucce1** [AcidWeb/CurseBreaker#157]
Hi.

I would like CurseBreaker version 3.9.5 to start every morning at 05:30:00 and autoupdate my addons.

There is just one problem.
The row "Press any key to continue . . ." makes the program never exit, which leaves the process hanging in the background.

Could you remove the "Press any key to continue . . ." from the program? Atleast when its not executed in interactive mode.

Other than that, great software! 👍 

Full Regards/Magnus

**Comment by AcidWeb** [comment]
Run it like this: `CurseBreaker.exe headless`

**Comment by nucce1** [comment]
Thank you mate, I don't know how I didnt understand this from reading the first page. Tried with --help /? and alla other switches I could think of. 

Thank you for the fast reply! 

Full Regards/Magnus
