### ISSUE TITLE
Support for https://git.tukui.org/ custom projects?

### ISSUE THREAD

**Issue by nucce1** [AcidWeb/CurseBreaker#158]
Hi.

I'm missing support for git.tukui.org custom projects, like example: https://git.tukui.org/Luckyone/ProjectAzilroka.git
Once again, great software. 

Full regards/Magnus

**Comment by AcidWeb** [comment]
Most of projects there are in form that can't be used directly plus they don't provide releases like GitHub ones. So full support for it is no-go.
