### ISSUE TITLE
2.5.0 "Failed to parse addon data."

### ISSUE THREAD

**Issue by Reversan** [AcidWeb/CurseBreaker#16]
Upgraded to 2.5.0 (automatically)
Since then, when trying to install any CF addon "Failed to parse addon data. There is some issue with the website or this addon don't have release for your client version."

**Comment by AcidWeb** [comment]
It is not connected with update. Something on CF side is working not as expected. I will check it later.

**Comment by AcidWeb** [comment]
It will be fixed in 2.5.1 release.
