### ISSUE TITLE
UI is broken in the alacritty 

### ISSUE THREAD

**Issue by disshishkov** [AcidWeb/CurseBreaker#160]
Additional linebreaks are added if run inside https://github.com/alacritty/alacritty
![image](https://user-images.githubusercontent.com/946095/94848301-7f8dbe80-042c-11eb-9743-fe38a53879e9.png)

Windows 10 2004
CurseBreaker v3.10.1

**Comment by disshishkov** [comment]
Is a resize necessary? How about a start option which will disable the resize?

**Comment by AcidWeb** [comment]
I made some tests and apparently this is not only resize fault. Can alacritty usage can be detected from shell level in some what? Environment variable or something?

**Comment by AcidWeb** [comment]
OK. I got it. I will try to fix it in next release but no promises.
