### ISSUE TITLE
Error "RuntimeError: Failed to parse addon data: 'changelog'

### ISSUE THREAD

**Issue by Coonaps** [AcidWeb/CurseBreaker#161]
![Screenshot from 2020-10-02 14-28-17](https://user-images.githubusercontent.com/55458327/94923119-a515d900-04bb-11eb-9f64-bd8739dc49c6.png)
Getting the above error after updating to latest version. Any ideas?
Thanks for this great tool, I like it a lot!

**Comment by AcidWeb** [comment]
Please upload yours `WTF/CurseBreaker.json`

**Comment by Coonaps** [comment]
[CurseBreaker-json.zip](https://github.com/AcidWeb/CurseBreaker/files/5317983/CurseBreaker-json.zip)
Done

**Comment by AcidWeb** [comment]
OK. I will push fix soon.

**Comment by Coonaps** [comment]
Thank you. This has to be the fastest response in customer service history :-)
