### ISSUE TITLE
Silently update when launched with headless

### ISSUE THREAD

**Issue by bloodstrike** [AcidWeb/CurseBreaker#164]
When launched with the headless option, could the auto-update complete without intervention?

I wrote a small Automator script in macOS to run CurseBreaker, wait for it to finish, and then run WoW, but when CurseBreaker updates and waits for a keystroke everything breaks.

Also - this is slightly related (but not entirely, I can make a different issue if you'd like) and way less important, when run with headless, the current script outputs the output table to CurseBreaker.html, but it appends each time. This leads to a bigger and bigger CurseBreaker.html file. I personally don't see the need to append each run rather than just overwrite the html file with the latest results, but you/others might feel differently. Perhaps an option to toggle saving the entire history? 

The only reason I even noticed this is that I'm currently parsing that file to find out if anything got updated and create a notification with automator. When the file gets big, it takes automator a long time to parse the file looking for the latest update. To fix it for me, I just trash the html file each run, so that it only has the latest results.

**Comment by AcidWeb** [comment]
It already [do that](https://github.com/AcidWeb/CurseBreaker/blob/master/CurseBreaker.py#L228). Maybe fact entire binary is restarted after the process is breaking your automation?

Logging is running in append mode as most of users don't check state of this applications after every headless mode run. I will think about adding option.

**Comment by bloodstrike** [comment]
hrm. maybe that is what it is. I wonder if there is any way to detect that. Well, thanks for the response!
