### ISSUE TITLE
cant find release for client version?

### ISSUE THREAD

**Issue by ThomasEmilMortensen** [AcidWeb/CurseBreaker#165]
Im suddenly getting this when running Cursebreaker 3.11.1

![image](https://user-images.githubusercontent.com/19706569/95294146-0c91a700-0875-11eb-84b0-90b6964bba47.png)

Havent really changed anything, so im wondering why it suddenly says it cant find release for my client version?

**Comment by AcidWeb** [comment]
CurseBreaker started to parse the dependencies. I guess that one of your addons have declared `LibStub` as dependency (that is a mistake) and LibStub never had the official classic release. Execute `install -i cf:libstub`. That will forcefully install the retail version and meet the dependency.

**Comment by ThomasEmilMortensen** [comment]
Thank you - i did that, and another error came up. Decided to clean up my addons and removed unused ones and all is back to normal :-)
