### ISSUE TITLE
Personal cloud backup/restore

### ISSUE THREAD

**Issue by liamcooper** [AcidWeb/CurseBreaker#166]
Hi,

I want to start by saying I love this addon manager, I'm currently using it across two computers and I was wondering if it was possible to add personal cloud backup/restore functionality to something like gdrive or dropbox. Reason is that I don't want to have to configure my addons on both machines and I want my data to be transferred when I move from one machine to another. I know I can just copy across the files/backup manually, but having it within the addon manager would make things a lot easier.

Thanks,

Liam

**Comment by AcidWeb** [comment]
I thought about it long time ago. This is big one. Still not sure if it will be ever in scope of this application.

I'm leaving this ticket open for posterity.

**Comment by nagha95** [comment]
Hey @liamcooper, I have automatic backup for all of my character & addon settings (WTF folder) set up to my Google Drive. This is very easy and simple to do:

1. Download the Google Drive desktop application: https://www.google.com/intl/en-GB_ALL/drive/download/backup-and-sync/
2. Find the WTF-Backup folder (automatically created by CurseBreaker) in your WoW \_retail_ folder.
3. Right-click it and let the folder sync to Google Drive (or it can be done through the Backup and Sync application settings). It will show a green tick which indicates the folder is being synced:
![image](https://user-images.githubusercontent.com/50773468/95655011-04539900-0b0d-11eb-9d91-6015f7d4b70f.png)

Any time you run CurseBreaker, your WTF backups will automatically be updated and synced to Google Drive. This can also be done for any folder.

Hope this helps you and anyone else wondering!

**Comment by JasonBristol** [comment]
I've been doing what @nagha95 suggests as well for over 2 years now, have had no issues. Recommend setting your screenshots folder to sync as well if you are like me and like the memories

**Comment by liamcooper** [comment]
Keeping backups of that folder is fine outside the app, but it's more having a process in the app to restore them so it doesn't need to be done outside. 
As a work around I'm guessing I can probably just backup the WTF/Interface folders instead of WTF-Backup, then I should have my settings on each machine too.

Thanks guys.

**Comment by nagha95** [comment]
Yep, I assume you mean you want to avoid the manual process of downloading, unzipping and restoring files.

If you want to have your 'live' folders (WTF/Interface) syncing between two computers I believe this can be done by setting the right settings in Google Backup & Sync, so that any file that is edited on the 1st PC also changes on the 2nd PC, etc.

**Comment by DoctorBak** [comment]
Years ago I made a junction into my dropbox folder with a few strings in cmd. It worked like a charm.
It might still work but discretion is advised.
> mkdir "%USERPROFILE%\Dropbox\WoWSync"
move "%WOWPATH%\Interface\AddOns" "%USERPROFILE%\Dropbox\WoWSync"
mklink /J "%WOWPATH%\Interface\AddOns" "%USERPROFILE%\Dropbox\WoWSync\AddOns"
move "%WOWPATH%\WTF\Account" "%USERPROFILE%\Dropbox\WoWSync"
mklink /J "%WOWPATH%\WTF\Account" "%USERPROFILE%\Dropbox\WoWSync\Account"

**Comment by nagha95** [comment]
This reminds me that I forgot to mention something important. You can also use [Syncthing](https://github.com/syncthing/syncthing) to sync any files between two or more devices. It's the best, most secure, free and open source device syncing software.

You could probably use this to sync your live WTF/Interface folders between devices (or Google Backup & Sync depending on what works better for you), while having Google Backup & Sync automatically syncing WTF-Backup to your Google Drive for backup purposes.

**Comment by electr0sheep** [comment]
I just submitted a PR that _sorta kinda_ addresses this, which you can find just above.

**Comment by Marthisdil** [comment]
I just have my interface and wtf folders on my dropbox and have windows hard links in my wow folder pointing to them.  syncing across 3 computers (I only use 1 at a time)
