### ISSUE TITLE
how to install wowinterface addon: postal_classic

### ISSUE THREAD

**Issue by mczg** [AcidWeb/CurseBreaker#167]
cursebreaker ver : 3.11.1
CB> install wowi:25366-Postal_Classic
0/1 | ───────────────────────────────────────────── |
┌─────────────── Traceback (most recent call last) ────────────┐
│ CurseBreaker.py:184 in start                                                                  │
│                                                                                               │
│ CurseBreaker.py:374 in c_install                                                              │
│                                                                                               │
│ CB\Core.py:259 in add_addon                                                                   │
│                                                                                               │
│ CB\__init__.py:30 in inner                                                                    │
└────────────────────────────────────────────────┘
RuntimeError: Failed to parse addon data: File is not a zip file

**Comment by AcidWeb** [comment]
Hmm. It works here. You maybe live in some country that filter the internet?

**Comment by mczg** [comment]
Ok, thank you!
