### ISSUE TITLE
Failed to parse addon data: Armory (Classic). - But no classic version installed.

### ISSUE THREAD

**Issue by cont1nuity** [AcidWeb/CurseBreaker#168]
When trying to update, I receive the following error:

+------------------------------ Traceback (most recent call last) ------------------------------+
CurseBreaker.py:148 in start
CurseBreaker.py:496 in c_update
CurseBreaker.py:374 in c_install
CB\Core.py:258 in add_addon
CB\Core.py:175 in parse_url     
CB\__init__.py:30 in inner     
+-----------------------------------------------------------------------------------------------+
RuntimeError: Failed to parse addon data: Armory (Classic).
Failed to find release for your client version.

The json does list Armory, but the cache lists armory-classic. Not sure what/where that's going wrong...

cache and json:

**Comment by AcidWeb** [comment]
Armory addon have broken dependency list.

**Comment by cont1nuity** [comment]
Just for the reference: https://www.curseforge.com/wow/addons/elvui-armory-skin/relations/dependencies?filter-related-dependencies=3
Thanks for the quick analysis and response!
