### ISSUE TITLE
Have a non-auto update's option when cursebreaker is start ?

### ISSUE THREAD

**Issue by mczg** [AcidWeb/CurseBreaker#170]
I found app.github.com(185.199.111.153) sometime can'nt access by browser.
www.github.com is ok!
telnet 185.199.111.153 80/443  is ok! But browser is failure, response : ERR_CONNECTION_REFUSED
cause cursebreaker start fail.  Any directly append option, eg: cursebreaker status, same error response. Can'nt enter CB prompt yet.

**Comment by AcidWeb** [comment]
That mean you have problem with your internet connection or your internet is filtered. Nothing to fix here for me.
