### ISSUE TITLE
Runtime Error: Failed to parse addon data: LibStub

### ISSUE THREAD

**Issue by Shamatix** [AcidWeb/CurseBreaker#173]
Hi there,

As of today I can no longer get CurseBreaker to work:S 

https://i.imgur.com/tqzLe2Y.png

I had no issues the other day, but when I start it up today I get  the error as seen in the picture.

Feel free to reply here or add me on discord: Shamatix#4329

**Comment by AcidWeb** [comment]
One of your addons have incorrectly declared LibStub dependency. Try to install it manually `install -i LibSub`

**Comment by Shamatix** [comment]
That worked, damn you fast on the support! Keep up the great work :) really hope this wont stop working with this overwolf bullshit

**Comment by AcidWeb** [comment]
Yeah I guess if author set LibStub wrong we made the same error with `cf:callbackhandler`.

**Comment by Shamatix** [comment]
Seems like it's working now, guess there was no way to tell which addon it was?
If answer is no just close this ticket and once again thanks a ton for the help.

**Comment by AcidWeb** [comment]
Currently there is no option to display addon dependencies.
