### ISSUE TITLE
CurseBreaker does not start

### ISSUE THREAD

**Issue by Murilobeluco** [AcidWeb/CurseBreaker#174]
CurseBreaker.exe does not start

![curse breaker](https://i.imgur.com/9K2DBTL.png)

**Comment by AcidWeb** [comment]
I don't have slightest idea. I presume that is not Windows 7?

**Comment by Kazlehoff** [comment]
Providing the error message that displays when you try to launch CurseBreaker might also help to troubleshoot as well.

**Comment by AcidWeb** [comment]
That is entire point - There is no error massages.

**Comment by tyranadin** [comment]
If you just downloaded this and it's your first time running it at all, you may need to first let it have permissions to run, as Windows may have flagged it. In the Windows GUI, right click on Cursebreaker. Properties -> Security, and then give it permission to run. Then try again.
