### ISSUE TITLE
frozen version from blocked addons

### ISSUE THREAD

**Issue by katzner** [AcidWeb/CurseBreaker#175]
When you toggle_block an addon like TradeSkillMaster/TradeSkillMaster_AppHelper, because it's updated through another app or manually. CurseBreaker shows the old/frozen version in it's status. Not a bug, but I don't like it, because it's always shown as "Modified", when I really want CurseBreaker to ignore it and/or show the currently installed version.

**Comment by AcidWeb** [comment]
Yeah it is displaying version from local database that is only updated when CB update the addon.
I can only suggest to ignore it or `uninstall` it and let external application handle it. It will not automatically appear again.

**Comment by katzner** [comment]
You are right, to `uninstall` it, is the correct choice. Don't know why this didn't come to my mind. Thank you. :-)
