### ISSUE TITLE
[Feature Request] Add date/game version of installed addon version to summary table

### ISSUE THREAD

**Issue by lostmimic** [AcidWeb/CurseBreaker#176]
It would be good to be able to see (even if only with an optional param to status command) the `fileDate` or `gameVersion` of the installed version of the addon so you can see at a glance what may be very out of date

**Comment by bitpixl** [comment]
I came here for this request :)

**Comment by Malpractis** [comment]
Hah also came to request a 4th column for gameVersion.

**Comment by AcidWeb** [comment]
Main problem is a fact that due to general state of CF API you don't really can get that value reliably.

**Comment by nucce1** [comment]
I also came here to request this in someway. If not gameversion works maybe last updated date&time on serverside?

**Comment by lostmimic** [comment]
@AcidWeb ahh okay, maybe I was just getting lucky as I was checking out a few examples from the `https://addons-ecs.forgesvc.net/api/v2/addon/search?gameId=1&pageSize=10&searchFilter=` call back when I was seeing if it was possible or not :(

**Comment by fatalicus** [comment]
> 
> 
> Main problem is a fact that due to general state of CF API you don't really can get that value reliably.

I'm guessing that the problem could be that the installed addon could be older than what you get back in gameVersionLatestFiles, which i'm also guessing is what you check against to see if there is an update?

It could then be enough with a best effort attempt: when status is ran, check against gameVersionLatestFiles if the currently installed version is there.
Is the installed version there? Great, grab gameVersion and show it.
Is it not? show blank or N/A.

**Comment by Barleduq** [comment]
Here for requesting installation timestamp, which I look at all the time when I'm installing by hand.

**Comment by AcidWeb** [comment]
I will just display that API says and pray it is correct.

**Comment by AcidWeb** [comment]
I added a warning if latest project release don't match latest WoW version.

![image](https://user-images.githubusercontent.com/3713734/96348572-24093500-10aa-11eb-8a91-6ce7d6a1c707.png)
