### ISSUE TITLE
v3.12.0 toggle channel global parameter not showing

### ISSUE THREAD

**Issue by clicketz** [AcidWeb/CurseBreaker#177]
Global parameter not showing which channel is being toggled.  It seems to still work, you just have to keep trying until you get the one you're looking for.

![Untitled](https://user-images.githubusercontent.com/40314230/95903270-29d1e400-0d53-11eb-9b37-6d0d078ab938.png)

**Comment by AcidWeb** [comment]
Yeah. I is working but message is broken.
