### ISSUE TITLE
RuntimeError: Failed to parse addon data: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by lucasnbraga** [AcidWeb/CurseBreaker#179]
Was working a few hours ago, but ever since the servers went back up i am getting this error on Cursebreaker.

**Comment by lucasnbraga** [comment]
Now i am getting more details:

RuntimeError: Failed to parse addon data: ('Connection aborted.', TimeoutError(10060, 'A
connection attempt failed because the connected party did not properly respond after a period of
time, or established connection failed because connected host has failed to respond', None,
10060, None))

**Comment by JasonBristol** [comment]
Seeing this as well

**Comment by lucasnbraga** [comment]
I suspect the curse cdn is overloaded or something like that, so i'm going to take a wild guess that its probably not cursebreaker's fault

**Comment by JasonBristol** [comment]
Yah doubt its CB, seeing similar issues in the twitch client right now

**Comment by AcidWeb** [comment]
All addon sites are currently hugged to death. Expect errors. I set the in-app MOTD.
