### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by DemonfangArun** [AcidWeb/CurseBreaker#180]
For some reason, addon updates are not being detected from curseforge properly. Some are updating today, as expected, while others aren't installing updates marked as release months ago. I've tried toggling to alpha and that still didn't fix it. Most prominent is recount which explicitly has an update for 9.0.1 out as release but it's being ignored. Meanwhile Bagnon and MicroDeclineDuel updated fine.

**Comment by AcidWeb** [comment]
All addon sites are currently hugged to death. Expect errors. I set the in-app MOTD. It should fix itself in few hours.

**Comment by DemonfangArun** [comment]
I love that description :D
