### ISSUE TITLE
Autoback of WTF not functioning

### ISSUE THREAD

**Issue by foxdove** [AcidWeb/CurseBreaker#181]
The program runs through checking addons and automatic updates on start like normal but then freezes for a minute or so. There are no backups of the WTF created after this, it will simply skip to the next point where the program auto closes after the next keypress. This issue is repeated with at least 2 different people on different computers starting today.

**Comment by AcidWeb** [comment]
All addon sites are currently hugged to death. Expect errors. I set the in-app MOTD. It should fix itself in few hours.

In your case it is freezing during WA update.
