### ISSUE TITLE
[Feature Request] Auto-tag deprecated addon

### ISSUE THREAD

**Issue by Leomaradan** [AcidWeb/CurseBreaker#182]
Some addon are not updated anymore, but continue to work. For eg. the addon "Hide Screen Captured" that remove the Screen Captured message when taking a screenshot. The last version is for the 7.3.0 version of the game, but it is compatible with 8.3 (not tested for 9.0)

It would be nice to have a function to add some addon on a "tag list", and then auto-tag these addon to the last game version

I made an example of the Hide Screen Captured TOC:
```lua
## Interface: 90000
# OriginalInterface: 70300
## Title: |cff00ff00Hide|cffff6060 Screen|cffff00ff Captured
## Notes: Hide Screen Captured is an Addon thats hide the message "Screen Captured" when you took a selfi or a screenshot. And other useful functions.
## Autor: Rawesome
## Version: 0.1.9

hide\load_hide.xml
core\load_core.xml
calculator\load_calculator.xml
```

The TOC Interface Metadata has been updated to 9.0 version, but the original version is stored in the comment starting with OriginalInterface.

And for the case of old addon with returning author, I think these addon must be retired from the tag list when updated

**Comment by AcidWeb** [comment]
Out-of-scope. I prefer not to cross the border of editing automatically somebody else code. It have bad precedents in WoW community history. Plus you can easily just edit that file and live with `Modified` tag.

PS. Correct TOC for pre-patch is `90001`
