### ISSUE TITLE
[Question / Feature Request] Support UI compilations

### ISSUE THREAD

**Issue by jvandertil** [AcidWeb/CurseBreaker#185]
I tried searching but couldn't find a previous issue about this, sorry if I missed it.

Are UI compilations supported? I tried retrieving [RealUI](https://www.wowinterface.com/downloads/info16068-RealUI.html) from WoWInterface, but that didn't work:
```
CB> install wowi:16068-RealUI
0/1 | 
RuntimeError: Failed to parse addon data: https://www.wowinterface.com/downloads/info16068-RealUI.html
```

I assume these kind of 'compilations' are currently unsupported, or is this expected to work?

edit: Some sytem information: Client version is v3.12.0 running on Windows. I used the environment variable to point CurseBreaker to my WoW directory (retail).

**Comment by AcidWeb** [comment]
It should as package contain addons only. But for some reason WoWI API thinks this project don't exist: https://api.mmoui.com/v3/game/WOW/filedetails/16068.json

Maybe it is only temporary problem.

**Comment by jvandertil** [comment]
I tried some other UI compilations and it seems that the WoWI API does not recognize those either. As a test I installed the Minion app offered by WowInterface, but they are not available there as well. So this would appear to be a limitation of the API used, unfortunately.

The good news (for me) is that RealUI has a [GitHub](https://github.com/RealUI/RealUI) repository 😄 which I can use.

In any case, this might be something to add to the known limitations as there is little you can do to change this (I think). 
Adding a nice error message when WoWI returns `{"ERROR":"No AddOn found."}` might be worth considering?

**Comment by AcidWeb** [comment]
I made own research and I agree with the conclusions. Sadly this is unfixable. I will improve error message.

**Comment by AcidWeb** [comment]
For posterity: #195
