### ISSUE TITLE
How do I reset cursebreaker?

### ISSUE THREAD

**Issue by mrminus** [AcidWeb/CurseBreaker#186]
I seem to have gotten myself into a state that I don't know how to blackout of. 
![help](https://user-images.githubusercontent.com/615900/96012070-994ddf00-0df8-11eb-968a-38fff5c6b0e2.png)  How do I just tell CB to "forget whatever it thinks it knows, look at the addons directory and import it all, update what needs updating'?

**Comment by mrminus** [comment]
For exmaple, I dont even have AdiBags installed in the addons directory, but it keeps telling me it is "modified"

**Comment by jamby** [comment]
See: https://github.com/AcidWeb/CurseBreaker/issues/183

**Comment by mrminus** [comment]
ok, that did it! thanks
