### ISSUE TITLE
*ELVUI 

### ISSUE THREAD

**Issue by Razur3** [AcidWeb/CurseBreaker#187]
So i keep getting several error messages when trying to install the ELVUI through cursebreaker. 
Tried installing some other addons, and that worked just fine. 
Here are some of the messages i keep getting.: 

"RuntimeError: Failed to parse addon data: HTTPSConnectionPool(host='git.tukui.org', port=443):
Max retries exceeded with url: /api/v4/projects/60/repository/branches/master (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020E48E33D60>: Failed to
establish a new connection: [WinError 10060] A connection attempt failed because the connected
party did not properly respond after a period of time, or established connection failed because
connected host has failed to respond'))"

"RuntimeError: Failed to parse addon data: HTTPSConnectionPool(host='git.tukui.org', port=443):
Max retries exceeded with url: /api/v4/projects/60/repository/branches/master (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x0000020E49057A00>: Failed to
establish a new connection: [WinError 10061] No connection could be made because the target
machine actively refused it'))"

was just wondering what i might do to fix this. 
Because it seems that my attempts to install ELVUI is stopped from where it is getting ELVUI.

**Comment by nope-dot-jpg** [comment]
Tukui seems to be down, that's probably the problem

**Comment by AcidWeb** [comment]
It looks like everything returned to norm.
