### ISSUE TITLE
Failed to parse addon data, no releases

### ISSUE THREAD

**Issue by jamby** [AcidWeb/CurseBreaker#188]
So definitely have some problems in regard to it trying to find specific projects that "don't have any releases".

One in particular is KuiNameplates, which does in fact have releases. It has releases on CurseForge and on their GitHub.

**Comment by bsolar17** [comment]
Same problem with Dominos.

**Comment by nope-dot-jpg** [comment]
Same problem with Kui

**Comment by AcidWeb** [comment]
CF API is dead.

**Comment by bsolar17** [comment]
Overwolf removed access to the API?

**Comment by AcidWeb** [comment]
Jesus no. Traffic killed it.

**Comment by AcidWeb** [comment]
It looks like everything returned to norm.
