### ISSUE TITLE
Can't find github releases marked as source code

### ISSUE THREAD

**Issue by jammer** [AcidWeb/CurseBreaker#189]
Seems the application fails to detect the addon release when it's marked as source code in GitHub. Like in the following examples:

>CB> install https://github.com/Tercioo/Details-Damage-Meter
RuntimeError: Failed to parse addon data: https://github.com/Tercioo/Details-Damage-Meter
This integration supports only the projects that provide packaged releases.

>CB> install https://github.com/Tercioo/Plater-Nameplates
RuntimeError: Failed to parse addon data: https://github.com/Tercioo/Plater-Nameplates
This integration supports only the projects that provide packaged releases.

**Comment by AcidWeb** [comment]
Releases are missing proper addon package. CB don't operate on raw repositories.
