### ISSUE TITLE
Failed to parse addon data.

### ISSUE THREAD

**Issue by NCC-Lykos** [AcidWeb/CurseBreaker#19]
I see this was an issue before, but I'm having this issue now and it is returning no additional information...

![image](https://user-images.githubusercontent.com/24256285/65700510-70b84300-e045-11e9-8bfc-3867b5f77b6c.png)

Is there a log or verbose output somewhere?

**Comment by AcidWeb** [comment]
Not yet. But that error is produced by addon right after "Macro Toolkit".

**Comment by NCC-Lykos** [comment]
> Not yet. But that error is produced by addon right after "Macro Toolkit".

Looks like an issue with this addon, removed and tried to reinstall but failed again. 

https://www.curseforge.com/wow/addons/mechagon-rare-share

**Comment by AcidWeb** [comment]
Author removed all releases: https://www.curseforge.com/wow/addons/mechagon-rare-share/files
"This project has been discontinued due to API changes Blizzard has implemented in 8.2.5"

I need to think about better error reporting but this issue is not caused by CB.
