### ISSUE TITLE
does not open the application after updating to the pre-patch

### ISSUE THREAD

**Issue by williangk-ctrl** [AcidWeb/CurseBreaker#190]
after the pre-patch arrived, the application had an update that prevents it from opening, I tried to reinstall but it didn't work very well, when I install it, it updates the cursebraker to the latest version and then stops opening. HELP

**Comment by AcidWeb** [comment]
Please show error messages.

**Comment by williangk-ctrl** [comment]
> Please show error messages.


124/5000
after the update it does not open, nothing appears when I try to open it, but a friend of mine is using it normally.

**Comment by AcidWeb** [comment]
Windows 7?

**Comment by williangk-ctrl** [comment]
no, windows 10.

**Comment by AcidWeb** [comment]
Check this: https://github.com/AcidWeb/CurseBreaker/issues/174#issuecomment-707913477

**Comment by williangk-ctrl** [comment]
it still didn't work. only the latest version of the program is not working. basically if i try to put an old version of the cursebreaker, it opens normally and updates the cursebreaker, after updating it does not open anymore

**Comment by AcidWeb** [comment]
Which version is "old"?

**Comment by williangk-ctrl** [comment]
the old version is version 3.5.1. basically i tried to reinstall the cursebreaker with version 3.5.1, then it opens, updates to the current version and then it doesn't open anymore.

**Comment by AcidWeb** [comment]
Oh damn that is old. I expected v3.11.1. Check if v3.9.3 and v3.9.4 start and update or just also crash.

**Comment by williangk-ctrl** [comment]
none of these versions opened?

**Comment by AcidWeb** [comment]
I have no idea what causing this. Try to find newest version that starts.

**Comment by williangk-ctrl** [comment]
the last version that opens and updates is 3.9.1 after that no other opens

**Comment by AcidWeb** [comment]
No changes between 3.9.1 and 3.9.2 should cause this. Can you show me output of `echo %TMP%` command?
