### ISSUE TITLE
Cannot enter interactive mode by pressing a key

### ISSUE THREAD

**Issue by bdrago** [AcidWeb/CurseBreaker#193]
macOS 10.15.7 
zsh 5.7.1 (system default)
CurseBreaker v3.12.1 

When I launch CurseBreaker from the _retail_ directory with './CurseBreaker' I get the normal message: 

```
Automatic update of all addons will start in 5 seconds.
Press any button to enter interactive mode.

``` 

No matter what keys I press I cannot enter interactive mode and after five seconds CurseBreaker upgrades all installed adding and then exits. 

This used to work on this system as expected but I don't know when the behavior changed.

**Comment by DoctorShades24** [comment]
Same here.  Running macOS 10.5.6

**Comment by AcidWeb** [comment]
Hmm nothing changed on this side. `Enter` works?

**Comment by AcidWeb** [comment]
Yeah. For some reason only `Enter` works. I will take a look.

**Comment by bdrago** [comment]
Confirming that `Enter` works but no other keys.
