### ISSUE TITLE
Issue with cf:infinite-raid-tools

### ISSUE THREAD

**Issue by Dahustler** [AcidWeb/CurseBreaker#194]
Hey, I just started using CB and so far I like it. /recommendations was very helpful.

I have a problem with cf:infinite-raid-tools though.
I manually deleted the EndlessRaidTools folder and the InfiniteRaidTools folder and then ran these commands:

Unknown directories:
InfiniteRaidTools
SilverDragon_Shadowlands
TidyPlates_Classic

Execute import install command to install all detected addons.
Possible matches need to be installed manually with the install command.
Addons that are available only on WoWInterface and/or Tukui are not detected by this process.
CB> install cf:infinite-raid-tools
1/1 | ───────────────────────────────────────────────────────────────────────────────────────── |
┌───────────────────┬─────────────────────┬─────────┐
│      Status       │ Name / Author       │ Version │
├───────────────────┼─────────────────────┼─────────┤
│ Already installed │ Infinite Raid Tools │ v9.02   │
└───────────────────┴─────────────────────┴─────────┘
CB> import
Addons found:

Possible matches:

Unknown directories:
SilverDragon_Shadowlands
TidyPlates_Classic

Execute import install command to install all detected addons.
Possible matches need to be installed manually with the install command.
Addons that are available only on WoWInterface and/or Tukui are not detected by this process.
CB> uninstall cf-Infinite Raid Tools
1/1 | ───────────────────────────────────────────────────────────────────────────────────────── |
┌─────────────┬─────────────────────┬─────────┐
│   Status    │ Name / Author       │ Version │
├─────────────┼─────────────────────┼─────────┤
│ Uninstalled │ Infinite Raid Tools │ v9.02   │
└─────────────┴─────────────────────┴─────────┘
CB> install cf:infinite-raid-tools
1/1 | ───────────────────────────────────────────────────────────────────────────────────────── |
┌───────────┬─────────────────────┬─────────┐
│  Status   │ Name / Author       │ Version │
├───────────┼─────────────────────┼─────────┤
│ Installed │ Infinite Raid Tools │ v9.02   │
└───────────┴─────────────────────┴─────────┘
CB> import
Addons found:

Possible matches:

Unknown directories:
InfiniteRaidTools
SilverDragon_Shadowlands
TidyPlates_Classic

Execute import install command to install all detected addons.
Possible matches need to be installed manually with the install command.
Addons that are available only on WoWInterface and/or Tukui are not detected by this process.
CB>

So, after installing InfiniteRaidTools with CB commands, again the folder is listed as Unknown directories.

**Comment by AcidWeb** [comment]
It is caused by project rename. Database used by `import` don't know `InfiniteRaidTools` directory yet. It should fix itself in few days.
Not a bug.
