### ISSUE TITLE
multiple addons from wowinterface not found, "Failed to parse addon data"

### ISSUE THREAD

**Issue by Barleduq** [AcidWeb/CurseBreaker#195]
So far I have this problem on 3 addons from wowinterface: the first two which are older (I thought that was the problem) but the other is very active.  The addons are 
https://www.wowinterface.com/downloads/info7929-MinimapButtonFrame.html
https://www.wowinterface.com/downloads/info9077-PetCare.html
https://www.wowinterface.com/downloads/info24608-Hekili.html

In all cases, this fails whether I'm using install wow:7929 (for example) or the full url. I have other addons with only 4 numbers, so that isn't a problem.  For Minimap Button Frame, it finds something for me to tab and get the whole name.  For PetCare and Hekili, it does not.  All three have the error 
Runtime Error: Failed to parse addon data

**Comment by AcidWeb** [comment]
Sadly that is quite common issue with WoWI API.

https://api.mmoui.com/v3/game/WOW/filedetails/7929.json
https://api.mmoui.com/v3/game/WOW/filedetails/9077.json
https://api.mmoui.com/v3/game/WOW/filedetails/24608.json

Currently API return information that those addons don't exist. Can't do anything about it.

**Comment by AcidWeb** [comment]
Issue is cause by the fact that some of addon categories are ignored in the API. Minimap Button Frame and PetCare are in `Optional » Discontinued and Outdated Mods` category. Hekili for some reason is stuck in `Optional » Battle for Azeroth Beta` and never was moved to `Stand-Alone Addons` like many projects there.

I think that is not API issue. It was designed to work that way. Minion is also affected by this.
