### ISSUE TITLE
Feature Request: Scroll up further in the Cursebreaker Window

### ISSUE THREAD

**Issue by Dahustler** [AcidWeb/CurseBreaker#197]
Great program you have created! It feels like playing an old DOS game.

I noticed that for example when I execute the command "status" twice in a row, the results of the first status are not completely visible anymore when I scroll up in the Cursebeaker window. It feels like about 150 rows are shown.
It would be great if you could display more rows.

**Comment by AcidWeb** [comment]
If you need bigger scroll buffer you need to switch to other console software. I suggest: https://aka.ms/terminal-preview

**Comment by Dahustler** [comment]
Oh you are right, I did not notice it uses the windows Terminal window. I increased the buffer to 2000 rows Thanks :)
