### ISSUE TITLE
Feature Request: Add a parameter to "status" to display the date of the addon and sort the output by date

### ISSUE THREAD

**Issue by Dahustler** [AcidWeb/CurseBreaker#198]
I use over 100 WoW addons.
To find out out what addons have not been updated for a long time by their creators/maintainers it would be great to have a parameter for the command "status" to display the date the addon had its latest version updated and sort the output of "status" by the date, to can easily identify old addons.
Then the user can think about if he/she wants to remove them or maybe find a replacement for them that is maintained regularly.

For example: cf:Toomanyaddons was last updated 2017-08-17 and would probably make the top of the sorted list :)

**Comment by AcidWeb** [comment]
Duplicate #176
