### ISSUE TITLE
removing addons from status

### ISSUE THREAD

**Issue by Morwo01** [AcidWeb/CurseBreaker#199]
using Cursebreaker since late July now, but i wonder how i manage removing addons from the list/status. while i deleted addons in off my addon folder of WoW, they remain in Cursebreaker with status 'Modified'. 
what command do i have to type in, is there maybe already how to guide i missed yet?

**Comment by AcidWeb** [comment]
Just `uninstall` them.

**Comment by Morwo01** [comment]
thanks
