### ISSUE TITLE
Scroll through the addon list in the window

### ISSUE THREAD

**Issue by skmzarn** [AcidWeb/CurseBreaker#2]
I find it to be quite buggy to scroll up to see all addons when you want to see the list from 'status', for example. A PGUP/PGDOWN keybind function, or another keybind that could work to be able to scroll up through the window would be awesome! Thanks!

**Comment by AcidWeb** [comment]
Currently scrolling is not supported at all.

**Comment by skmzarn** [comment]
I see. Right now I have no way to read all the addons in the list, because it's too big.

**Comment by AcidWeb** [comment]
Simple scrolling was added. It should be better but it is still not perfect - windows console really dislike to scroll color codes.
