### ISSUE TITLE
Unclear URL support for wowinterface.com

### ISSUE THREAD

**Issue by Cephel** [AcidWeb/CurseBreaker#20]
I'm using a quick example off an add-on that I want to use.

Consider this URL: https://www.wowinterface.com/downloads/fileinfo.php?s=2077fa2f66a75e80af5be48cdf76dd25&id=24980

Notice it does not match the format that CurseBreaker expects. At first I thought it was because no Classic version of the add-on is available, but then I noticed this:
![image](https://user-images.githubusercontent.com/6716857/65831524-d2cdae00-e2ba-11e9-8e99-413eec447b9d.png)

It seems to me that at least some add-ons have a malformed URL on wowinterface and cannot be used with this tool.

**Comment by AcidWeb** [comment]
I never seen this URL schema anywhere. Additionally if you search for "QuestLogEx" you are redirected to: https://www.wowinterface.com/downloads/info24980-QuestLogEx.html

But that will not help anyway as this project is not listed in WoWI API. So correct URL or not CurseBreaker can't handle it.

It look like entire project is malformed.

**Comment by Cephel** [comment]
Yikes, what is this URL scheme they got going there...

**Comment by layday** [comment]
You have a fileinfo URL in your very own [REKeys](https://github.com/AcidWeb/REKeys) ;P I guess it's something they might've used in the past.

**Comment by AcidWeb** [comment]
Huh.
QuestLogEx was created 05/29/19 so that is not connected with the date.
Anyway - nothing to fix here.
