### ISSUE TITLE
-a switch for status

### ISSUE THREAD

**Issue by eldir** [AcidWeb/CurseBreaker#200]
Just a small quality of life improvement by adding `-a` to `status` instead of having to `toggle compact_mode` on and off.

**Comment by Beet4** [comment]
I second this. Came here now to suggest the very same thing. It's a bit of a pain to see what addons updates at a glance with `compact_mode` off but once in a while you want to check all your installed addons then `status -a` would be a nice enhancement.

**Comment by AcidWeb** [comment]
I will add the flag that will reverse the current `compact_mode` state.
