### ISSUE TITLE
Source switching

### ISSUE THREAD

**Issue by eldir** [AcidWeb/CurseBreaker#202]
It'd be great to be able to switch between sources for the same addon. Especially during pre-patch I find myself preferring the github version of some addons. Perhaps a `install gh:[addonname]` could prompt for source switch of the addon is already installed instead of the current error message.

**Comment by AcidWeb** [comment]
In current form CB can't support it.
We will see what future will bring.

**Comment by fatalicus** [comment]
Note that OverWolf has decided to close curseforge for addon uploads/updates for the week of SL launch, meaning souorce switching will be more relevant than ever if people want to keep their addons up to date: https://www.wowhead.com/news=319169/curseforge-suspending-addon-updates-during-shadowlands-launch-week

**Comment by AcidWeb** [comment]
I'm aware about it and it this feature will definitely not be implemented in this timeframe.

**Comment by Marthisdil** [comment]
> Note that OverWolf has decided to close curseforge for addon uploads/updates for the week of SL launch, meaning souorce switching will be more relevant than ever if people want to keep their addons up to date: https://www.wowhead.com/news=319169/curseforge-suspending-addon-updates-during-shadowlands-launch-week

Twitch and OverWolf have come to an agreement where Twitch will continue providing updates/access to CurseForge through Nov 30th.
