### ISSUE TITLE
add option to disable addons?

### ISSUE THREAD

**Issue by lifebound** [AcidWeb/CurseBreaker#203]
Addon toggles appear to be stored in %WOW_FOLDER%\\\_retail_\WTF\Account\\%AccountName%\\%ServerName%\\%CharacterName%\Addons.txt with the following format:

FolderName: enabled|disabled

Should be pretty simple to script that. 

I'd envision a flag that auto-disables out-of-date addons detected by cursebreaker, something like

```
toggle outdated //would automatically disable any addon identified as out of date
toggle outdated FarmHud //would mark FarmHud for automatic disablement as soon as it was out of date; no other addons would be affected in this way.
```

**Comment by AcidWeb** [comment]
I don't see really use for that. WoW client already allow to disable outdated addons in bulk.
