### ISSUE TITLE
Add an option to view patch notes of addons

### ISSUE THREAD

**Issue by KarlitosVII** [AcidWeb/CurseBreaker#204]
Hello,
I like to know what's new or fixed before updating my addons. It would be great to add an option to view the patch notes of addons that have an update available.

**Comment by AcidWeb** [comment]
Version number is a link to changelog. But you need to use console that support hyperlinks. https://aka.ms/terminal-preview for example.

**Comment by KarlitosVII** [comment]
I am using Mintty for WSL and console things. It detects urls but not hyperlinks like modern terminals.
Maybe it is time to switch. Thanks. :)
