### ISSUE TITLE
Packaged release error

### ISSUE THREAD

**Issue by Rollyjoger85** [AcidWeb/CurseBreaker#206]
Hi,
I've been trying to get the application to download SuperDuperMacro directly from GitHub and it keeps giving me the error below, as far as i can see there shouldn't be any reason for the error as the message indicates something that should already be available? (https://github.com/spiralofhope/SuperDuperMacro/releases)

```
RuntimeError: Failed to parse addon data: https://github.com/spiralofhope/SuperDuperMacro
This integration supports only the projects that provide packaged releases.
```

I'm using CurseBreaker v3.13.0

**Comment by AcidWeb** [comment]
This project don't provide proper packages. Just a tags.

**Comment by Rollyjoger85** [comment]
Oh I see, my bad then, sorry for the troubles
