### ISSUE TITLE
Req: Increase scrollback buffer

### ISSUE THREAD

**Issue by BristleBeard** [AcidWeb/CurseBreaker#21]
Could you increase the scrollback buffer?
When a lot of addons exist, a status command scrolls them off the screen and the buffer doesn't go back far enough to see them.

**Comment by AcidWeb** [comment]
You are using more than ~70 addons?

It is a little problematic as Windows console don't like to scroll color codes.
Anyway I will implement some kind of dynamical buffer.

**Comment by BristleBeard** [comment]
> You are using more than ~70 addons?

Sadly, yes... All of the little plugin ones add up! (Handy notes this, handy notes that, DBM this, DBM that, etc)
