### ISSUE TITLE
HTML files created by headless parameter requests

### ISSUE THREAD

**Issue by nucce1** [AcidWeb/CurseBreaker#210]
Hi there.

I got two requests for the generated cursebreaker.html file:
1. First of all I want it to purge old data, I got this runnning every morning and there is no point keeping more than 2-3 weeks history.
2. The latest run should be at the top instead of the bottom.

Full Regards

**Comment by AcidWeb** [comment]
After some thought I decided to not change anything.

1. If you need any purge you can do it easily on script level that start CB binary.
2. Logs don't grow upwards.

**Comment by nucce1** [comment]
1. I don't know howto do this easily, so thats perhaps could be something that you could provide along with your software.
2. I'll disagree. If you for example open _Windows Event Viewer_ you got the most recent event in the top.
