### ISSUE TITLE
Alpha/Beta Addon Toggle Option Not Available In Classic?

### ISSUE THREAD

**Issue by stratoru** [AcidWeb/CurseBreaker#211]
It appears as if the option to update to alpha/beta versions of addons is not available for classic. Only release versions are being updated to.

**Comment by AcidWeb** [comment]
Give me a sample project that should be updated but it is not.

**Comment by stratoru** [comment]
![image](https://user-images.githubusercontent.com/43893231/97093162-50bfce00-160f-11eb-828a-912e26639927.png)
Here is Prat, for example, showing 3.9.0. 
![image](https://user-images.githubusercontent.com/43893231/97093174-63d29e00-160f-11eb-8a50-7c85c7296816.png)
Here is the most recent version of Prat available.

**Comment by AcidWeb** [comment]
![image](https://user-images.githubusercontent.com/3713734/97101078-81991500-169a-11eb-9344-dba8f7bda01c.png)

It is working correctly. You are sure you enabled alpha channel for this addon?

**Comment by AcidWeb** [comment]
I presume you get it working.
