### ISSUE TITLE
Uninstall asking for closing quotation

### ISSUE THREAD

**Issue by StellaMiri** [AcidWeb/CurseBreaker#212]
Hello, 
i tried uninstalling an addon, but the client returns a Value error. Force update and install (prompt: already installed) work fine only uninstall returns an error. I experimented with other addons containing quotation marks and brackets in their name and didn't get the error.
![CurseBreaker](https://user-images.githubusercontent.com/73364771/97105679-16ad0580-16bd-11eb-8fe2-28b24a552530.JPG)

**Comment by AcidWeb** [comment]
This is clearly broken - I will take a look.

**Comment by AcidWeb** [comment]
Temporary fix: Add `'` at the end of the addon name.

**Comment by StellaMiri** [comment]
He really just wanted that quotation mark. Thanks for the quick fix!
