### ISSUE TITLE
Weakauras / Plater update causes LAU error in WA Companion

### ISSUE THREAD

**Issue by vderaa** [AcidWeb/CurseBreaker#213]
As per the title, the data.lua file created for the WA Companion to process causes errors, specifically trying to update plater profiles

Errors as below:

1x WeakAurasCompanion\data.lua:85: attempt to perform arithmetic on a string value
[string "@WeakAurasCompanion\data.lua"]:85: in main chunk

Locals:
(*temporary) = <table> {
 slugs = <table> {
 }
 ids = <table> {
 }
 uids = <table> {
 }
 stash = <table> {
 }
}
(*temporary) = <table> {
 slugs = <table> {
 }
 uids = <table> {
 }
}
(*temporary) = <table> {
 M+ Important Spells [Plater] = "8s7Mcrve2"
 M+ Explosive [Plater] = "1TlaFYtDO"
 Cast Bar & Icon Options = "DbHvO1awZ"
 Hide Neutral Units [Plater] = "5YLLQsaMR"
}
(*temporary) = nil
(*temporary) = "attempt to perform arithmetic on a string value"

AND

1x WeakAurasCompanion\init.lua:27: attempt to index global 'WeakAurasCompanion' (a nil value)
[string "@WeakAurasCompanion\init.lua"]:27: in function <WeakAurasCompanion\init.lua:8>

Locals:
_ = <unnamed> {
 0 = <userdata>
}
_ = "ADDON_LOADED"
addonName = "WeakAurasCompanion"
count = 0
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'WeakAurasCompanion' (a nil value)"

**Comment by AcidWeb** [comment]
Upload yours `WTF\Account\<Account>\SavedVariables\WeakAuras.lua` and `Plater.lua`. I will check it out.

**Comment by vderaa** [comment]
Hi,

Files you requested have been attached.  Thanks :)

[files.zip](https://github.com/AcidWeb/CurseBreaker/files/5435669/files.zip)

**Comment by AcidWeb** [comment]
Issue is caused by Plater script `Disable "-AGGRO-" flash`. Quotation marks in name are not escaped correctly and they are breaking the code.

I will fix it. For now just update that one manually and

**Comment by vderaa** [comment]
That was fast!  Many thanks :)
