### ISSUE TITLE
goLoot doesn't update

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#214]
https://www.curseforge.com/wow/addons/goloot/files

CB says that goLoot's up-to-date with version 1.00. 1.03 was uploaded 4 days ago, and CB doesn't seem to pick this up.

**Comment by AcidWeb** [comment]
You are playing classic?

**Comment by AcidWeb** [comment]
Author of this project is marking his releases as compatible both with retail and classic. This is known issue with CF API and it cause incorrect payload.

In this case 1.03 is marked as classic only update - that why it is not updated.
