### ISSUE TITLE
Unsure if issue or not more and more "Update supressed"

### ISSUE THREAD

**Issue by Shamatix** [AcidWeb/CurseBreaker#215]
Hi there,

Last update I did I could see in the "Twitch app" I had 7 addons ready for being updated.
I launched Cursebreaker and it only updated 1, I am frequently getting more and more "Update suppressed"
How can I avoid having to run force_update everytime, cant it update em automatically and why is this happening to this extent?

**Comment by AcidWeb** [comment]
Don't use two updaters. CB detect local changes made in addons and block the update.

**Comment by eldir** [comment]
@Shamatix if you just want to keep the Twitch app to have a look at your just turn auto update and addon management off (press ctrl+comma in the app to get to settings and then do as it's shown in the picture 
![image](https://user-images.githubusercontent.com/5166778/97594873-049fcf80-19fb-11eb-86af-f8bec6b3e7cd.png)

But like AcidWeb said, it's not good to use any two or more addon updaters as they will most likely get in conflict with one-another.

**Comment by Shamatix** [comment]
I dont update in the twitch app, however while "migrating" to use cursebreaker 110% of the time, I do use twitch app to look if both programs "shows me the same" if that makes sense.

**Comment by AcidWeb** [comment]
There are only two reasons why `Update suppressed` status can appear. Addon was modified after installing with CB and now update is available. Or you manually blocked updates with `toggle pinning` command.
