### ISSUE TITLE
Display remote version with `status` [enhancement]

### ISSUE THREAD

**Issue by eldir** [AcidWeb/CurseBreaker#216]
Especially during pre-patch some addons required manual fixing so their status will change to `Modified` and they won't be updated automatically anymore (which is great). That being said It'd be a nice QoL addition to have `status` or `status -a` display the remote version so I can easily tell when an update from the main developer has been made and then use a targeted `force_update` for this.

**Comment by AcidWeb** [comment]
When `Modified` addon have update available status change to `Update suppressed`.
