### ISSUE TITLE
Beta Compability

### ISSUE THREAD

**Issue by ninelore** [AcidWeb/CurseBreaker#218]
the WoW Beta executable file is called wowb.exe on windows

**Comment by AcidWeb** [comment]
It is already supported.

**Comment by ninelore** [comment]
i just triple checked. After all tries includinga clean WTF Folder didnt work and still shows me that the executable is not found. I did started the game multiple times after the clean WTF Folder

**Comment by AcidWeb** [comment]
Thanks for research. Both Windows and macOS clients are creating directory `Interface\AddOns`. So I don't consider it a bug.
