### ISSUE TITLE
Req: Continue on after error

### ISSUE THREAD

**Issue by NCC-Lykos** [AcidWeb/CurseBreaker#22]
Today Pawn updated, but for some reason CB couldn't update it. I don't know if its a cache error on some webserver somewhere or what, but it just quit at that point.

That is an alright behavior in some cases and makes you fix the issue, but could we just mark that as Error and continue on to the rest? I did check and Pawn is still up (Apologies for my last report haha) -> https://www.curseforge.com/wow/addons/pawn/files

![image](https://user-images.githubusercontent.com/24256285/65885303-057db200-e360-11e9-8399-01cb2104a20e.png)

**Comment by AcidWeb** [comment]
Pawn released files marked both for classic and retail. CF interface allow it but it breaks both CF API and Twitch client so I guess author will fix that mess soon.

Generally you are right but IDK if I can implement it without major rewrite.
