### ISSUE TITLE
Remember window position

### ISSUE THREAD

**Issue by Mythos** [AcidWeb/CurseBreaker#220]
Every time I start CurseBreaker, it resets to the center left of my main screen. (which is where my fullscreen apps are)
It would be really nice, if CurseBreaker could remember the last window position, which is for example on my second screen at position XY.

**Comment by AcidWeb** [comment]
CurseBreaker is console application. And generally window location is handled by console terminal application. Technically I could add support for saving it for default Windows cmd but I need to think if I want to mess with it.

**Comment by Mythos** [comment]
Thanks with that hint I figured out how to achieve that.

Only thing that bugs me is the auto resizing of the app (not keeping the settings from Windows), but with saving the positioning it's not that bad anymore.

**Comment by AcidWeb** [comment]
I would suggest to start CB with https://aka.ms/terminal-preview

**Comment by Mythos** [comment]
I got that one already installed as it's one of the best things MS released recently after VSCode... is there a way to open my shortcut in Windows Terminal? Can't find an "open with" setting in the shortcut which would lead to cmd.exe currently.
Opening Windows Terminal, navigating to my WoW dir and then running CB is a bit meh...also a profile for it is mehr as I like the "double click and wait for it to finish". :-)

**Comment by AcidWeb** [comment]
Make `wt.exe X:/path/to/cursebreaker.exe` shortcut.

**Comment by Mythos** [comment]
Thanks a lot, bro!
