### ISSUE TITLE
Difference in behavior between automatic and interactive modes

### ISSUE THREAD

**Issue by Barleduq** [AcidWeb/CurseBreaker#221]
If I launch CB and do not 'press any key' (which I believe has to be the enter key?), it updates and backs up the WTF directory.  If I launch CB and press enter to get into interactive mode, it does not back up the WTF directory when I tell CB to update or forceupdate.  Is this working as intended?

Also, I don't see (in the help file) a way to interactively cause CB to back up the WTF directory.  Am I missing something?   I can toggle whether the backup happens automatically (and have made sure that it's on). 

If it is working as intended to have there be no backup of the WTF directory after an interactive update, could there please be a command to do the backup?  Having to exit cursebreaker and relaunch it to - again - update everything so that the WTF gets backed up seems suboptimal. 

Thank you!
/amq

**Comment by AcidWeb** [comment]
It is working as indented. I agree that backup command is missing.
