### ISSUE TITLE
command "source"

### ISSUE THREAD

**Issue by vmwinckler** [AcidWeb/CurseBreaker#224]
examples: 

- source ProjectAzilroka _List all sources_
  -   cf:ProjectAzilroka (courseforge)
  -   tu:79 (tukui.org)
- source ProjectAzilroka tu:79
  - change from cf:ProjectAzilroka (courseforge) to tu:79 (tukui.org) (_sortcut for unistall ProjectAzilroka then install tu:79_)

*now all tukui installations desapear from "Tukui Client" but on new CurseForge Client (overwolf) its ok

**Comment by vmwinckler** [comment]
complement for #202

**Comment by AcidWeb** [comment]
I don't have any plans to implement centralized addon directory required by this feature.

**Comment by vmwinckler** [comment]
so what's the advantage of using it instead of Overwolf CurseForge?

**Comment by AcidWeb** [comment]
It support more addon sources than OW client. It also can update WA. It lightweight and most importantly it is not owned by OW.

**Comment by vmwinckler** [comment]
It supports more fonts but forces the use of CurseForge, that is, it supports but does not facilitate. Lightness is a real advantage on a computer that supports WoW and "not owned by OW" makes no difference.

OK, you've created a long-awaited, promising tool and you don't want to make it better. OK

A possible solution is to allow others to make implements and just validate.

**Comment by AcidWeb** [comment]
You are not forced to use CF.

I don't agree with you. It seems you simple looking for other updater. I suggest to check the list: https://ogri-la.github.io/wow-addon-managers/

**Comment by vmwinckler** [comment]
I will look. thanks.
