### ISSUE TITLE
add others info on table status

### ISSUE THREAD

**Issue by vmwinckler** [AcidWeb/CurseBreaker#225]
1.  add information over "what WoW version tath addon works now" on table status
on tukui client: WoW Patch
on curseforge client (overwolf): Game version

2. add addon "version" visible on table (today defined by command "toggle channel[Name]")

**Comment by AcidWeb** [comment]
Feature is partially implemented. "[!] mark means that the latest release is not updated yet for the current WoW version." I don't see a reason to display the version.

**Comment by vmwinckler** [comment]
ok but this information (about [!]) is not found anywhere

**Comment by AcidWeb** [comment]
It is - in application help.
