### ISSUE TITLE
Unknown directories

### ISSUE THREAD

**Issue by vmwinckler** [AcidWeb/CurseBreaker#227]
**Unknown directories**:
ElvUI_FCT _(this from "Floating Combat Text" -  tu:137)_ 
Icons _(this from "Clean Icons - Mechagnome Edition" - wowi:25064-CleanIcons-MechagnomeEdition)_

**Comment by AcidWeb** [comment]
Not a bug. `import` command detect addons only hosted on CurseForge.

**Comment by vmwinckler** [comment]
so what's the advantage of using it instead of Overwolf CurseForge?
