### ISSUE TITLE
Cannot install ElvUI

### ISSUE THREAD

**Issue by Erythros** [AcidWeb/CurseBreaker#228]
I used to manage my ElvUI via TukUI client. Since I haven't played for a few months, when I launched TukUI it removed all my addons managed my TukUI. (WTF folder is untouched). An [error like this](https://preview.redd.it/hrwyfetyaux51.png?width=406&format=png&auto=webp&s=cec95eb1a1b6e7dd8e3ea33e7ae58d783664a611) showed up for each of the plugins...

Great, so I switched to CurseBreaker. `import` finds all my addons, except those managed by TukUI (which have been removed as mentioned above).

I tried searching for ElvUI in order to manually install it. But, for some reason, it cannot find ElvUI.
![image](https://user-images.githubusercontent.com/2624183/98448445-babe9400-2134-11eb-9510-44fefdeb6cb5.png)

My 2 problems:

1. How do I install ElvUI?

2. If I Install ElvUI, will all my configs (from the WTF folder) be applied or overwritten and I have to start from scratch ?

**Comment by AcidWeb** [comment]
Import detect only addons on CF.

1. `install ElvUI`
2. No. CB don't touch any addon settings.
