### ISSUE TITLE
Often hangs after updating addons

### ISSUE THREAD

**Issue by Beet4** [AcidWeb/CurseBreaker#229]
I find that CurseBreaker often hangs after updating the addons. Most of the times it hangs after I have clicked a few links to updated addons (to check changelog). The window stops responding and has to be forcefully quit. Just now it stopped responding after I clicked one link. Could also have been while trying to update from wago.io?

It happens almost every time I run the updater.

I run CurseBreaker in Windows Terminal Preview version 1.4.2652

Anything I can do to further narrow the issue down?

**Comment by Beet4** [comment]
It is definitely when clicking links.

![image](https://user-images.githubusercontent.com/38279393/98852961-bfe35200-2458-11eb-9d29-dc3730338e7a.png)

**Comment by AcidWeb** [comment]
Can't do anything about it. Windows Terminal is crashing not CB. No idea what is causing that.

**Comment by Beet4** [comment]
I see, thanks. I noticed that WT 1.4 Stable and 1.5 Preview was released yesterday. I'll check if the problem is fixed in any of those versions.

**Comment by Beet4** [comment]
Seems to be fixed in Windows Terminal 1.4 Stable.
