### ISSUE TITLE
WA Update Error

### ISSUE THREAD

**Issue by behub-torch** [AcidWeb/CurseBreaker#23]
Have checked the API and Account Name all match.

If I run 'wa_update', I get the following error:

```
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 1044671: character maps to <undefined>

During handling of the above exception, another exception occurred:

xml.parsers.expat.ExpatError: mismatched tag: line 2, column 106
[10780] Failed to execute script CurseBreaker
```

**Comment by AcidWeb** [comment]
How you start it? Because I don't know what output `[10780] Failed to execute script CurseBreaker`.

Also send me your `SavedVariables/WeakAuras.lua` file.

**Comment by AcidWeb** [comment]
Also how you start it as I don't know what produce `[10780] Failed to execute script CurseBreaker` output.

**Comment by behub-torch** [comment]
I just start it from a shortcut to CurseBreaker.exe. I have to run it from a command prompt in order to get the output you see as the window closes once the error is thrown. It happens when it is set to automatically update the WA's or if I manually run 'wa_update'.

Will send you SavedVariables/WeakAuras.lua

**Comment by AcidWeb** [comment]
Found the issue. I will fix it soon.
