### ISSUE TITLE
HandyNotes: Battle for Azeroth (Curseforge) is not found

### ISSUE THREAD

**Issue by Dahustler** [AcidWeb/CurseBreaker#231]
This addon is not found for some reason: https://www.curseforge.com/wow/addons/handynotes-battle-for-azeroth
I just updated CB to v3.15.0
![image](https://user-images.githubusercontent.com/72993848/98978634-92f77380-251a-11eb-9510-8362dc808b8a.png)

Also the folder SilverDragon_Overlay is an "Unknown directory". It is part of Silverdragon afaik. The files inside the folder were updated 11.11.2020, so yesterday. And CB is the only tool I use to update addons.

**Comment by AcidWeb** [comment]
I will check it out but this issue not impact upgrade process if addon is visible on `status` list.

**Comment by AcidWeb** [comment]
Can't replicate this issue. Please provide yours `WTF\CurseBreaker.json` and list of directories in `Interface\AddOns`.

**Comment by Dahustler** [comment]
I just wanted to provide the data you asked for, but now both Unknown Directories are not shown anymore and CB found the Handynotes-battle-for-azeroth addon. See the screenshot below.
It is still a bit weird, because I had that problem for a few days and only reported it yesterday, after the newest version of CB came out and I still had the problem.

![image](https://user-images.githubusercontent.com/72993848/99096466-95b79e80-25d6-11eb-8eee-f5d8d1363e0e.png)

**Comment by AcidWeb** [comment]
OK. So apparently this was caused by outdated data on backend side.
