### ISSUE TITLE
Windows Block

### ISSUE THREAD

**Issue by ShawnSmall43** [AcidWeb/CurseBreaker#235]
I don't know if this is really an issue but, I tried to download CurseBreaker and Windows blocked it. Is it safe to download anyways?

**Comment by AcidWeb** [comment]
Yes.
https://www.virustotal.com/gui/file/0a9c7dc8d01a1b7f31e9f6b85ccdad2a879557efca9cfac8648900b9e7b9b35d/detection

**Comment by AcidWeb** [comment]
3.15.2 should be better in this regard.
