### ISSUE TITLE
WTF-Backup Directory Building Up

### ISSUE THREAD

**Issue by Davidforster1** [AcidWeb/CurseBreaker#237]
Hi there, love the app great work.

One issue I have is the backup folder located at C:\Program Files (x86)\World of Warcraft\_retail_\WTF-Backup in my case, is filling up gradually. Each time the addon folder backs up, it doesn't clean up old backup files (that I am aware of).

Could you possibly add in a feature that cleans out backups older than x number of days for example? For now I could set a scheduled task to do this but it would be nice to have this functionality within the app.

![image](https://user-images.githubusercontent.com/12282576/99570961-9d0dec00-29ca-11eb-9388-ad36a05220d7.png)

**Comment by AcidWeb** [comment]
It is cleaning them by default. It should keep max 7 files there.
