### ISSUE TITLE
Raider.io update suppressed

### ISSUE THREAD

**Issue by EmmanueleVilla** [AcidWeb/CurseBreaker#238]
Everytime I open curse breaker I have the message "update suppressed" regarding the "raider.io" addon update.
I've tried also to open curse breaker after closing both battle.net and the raider.io desktop client.
Do you think it's a local issue of mine or something could prevent raider.io from updating?

**Comment by AcidWeb** [comment]
Raider.IO desktop client is handling updates. CB is detecting that addon was externally changed and stops automatic updates. You can force update with `force_update` but this will repeat itself after next update made by R.IO client.

**Comment by EmmanueleVilla** [comment]
Understood! Thanks for the clarification :)
