### ISSUE TITLE
Add config.pickle.gz and slugs.pickle.gz to the repo

### ISSUE THREAD

**Issue by vbogach** [AcidWeb/CurseBreaker#239]
Currently config.pickle.gz and slugs.pickle.gz are downloaded from external source website. Generally data should be inspected before unpickling to avoid execution of malicious code. Currently these two files should be inspected on every app launch. If added to the repo, these files will have to be inspected only once. Could you please consider adding these two files to the repo?

**Comment by AcidWeb** [comment]
They are part of backend and they change quite often. They will not be part of application as it would undermine their usefulness.

**Comment by AcidWeb** [comment]
I'm not ignoring this possible security issue but in current form injecting malicious code would require user to be affected by MITM attack that redirect Google Cloud traffic and fake SSL certificates.

I consider it a unrealistic risk.
