### ISSUE TITLE
Multiple "malware" detections after update to v3.15.1

### ISSUE THREAD

**Issue by IceQ1337** [AcidWeb/CurseBreaker#241]
I know it's likely a false positive, but Avast Antivirus Pro isn't happy with the latest update. It detects CurseBreaker as "FileRepMalware" and this was not the case for earlier versions.

I've checked both [v3.15.0](https://www.virustotal.com/gui/file/0a9c7dc8d01a1b7f31e9f6b85ccdad2a879557efca9cfac8648900b9e7b9b35d/detection) and [v3.15.1](https://www.virustotal.com/gui/file/0b961031bde6ea119b6277bb3858f97aaf1e310adb1715265e1642dd985d0510/detection) on VirusTotal but the problem only affects the last version. I haven't looked closely at the changes, but since this could scare some users off, it might be worth investigating what is causing this problem.

**Comment by AcidWeb** [comment]
It is generic issue with binaries created by PyInstaller. Obscure and/or bad AV software sometimes have issues with this packager.

It is not first and not last time.

**Comment by AcidWeb** [comment]
3.15.2 should be better in this regard.
