### ISSUE TITLE
Flagged by Windows defender for behavior

### ISSUE THREAD

**Issue by Deathtech-00** [AcidWeb/CurseBreaker#243]
Just wanted to let you guys know that the heuristic scanner in windows defender flagged the app for "Behavior - can execute remote code"

I can provide more details, or if this is a known issue then disregard.

**Comment by AcidWeb** [comment]
#241

**Comment by AcidWeb** [comment]
Anyway I will try to make a binary that should not be marked as false positive this easily.

**Comment by AcidWeb** [comment]
3.15.2 should be better in this regard.
