### ISSUE TITLE
False Positive? MS Defender found Trojan:Script/Wacatac.B!ml in CurseBreaker.exe

### ISSUE THREAD

**Issue by katzner** [AcidWeb/CurseBreaker#244]
**This is probably a false positive!**

The Microsoft Defender found the trojan Script/Wacatac.B!ml yesterday in the current CurseBreaker.exe. I've checked the file in VirusTotal:
https://www.virustotal.com/gui/file/0b961031bde6ea119b6277bb3858f97aaf1e310adb1715265e1642dd985d0510/detection
... 7 engines detected a trojan (down to 3 today).

**Comment by AcidWeb** [comment]
#243 #241

**Comment by AcidWeb** [comment]
3.15.2 should be better in this regard.
