### ISSUE TITLE
Recent commit appears to have broken something, nuking WTF folder.

### ISSUE THREAD

**Issue by Frostea** [AcidWeb/CurseBreaker#245]
The recent commit (c7adf098cf416d83a8375a50412f68eac9e79e33) seems to have broken something when allowing auto-update to run. The WTF folder is in an unreadable state by WOW and it nuked the existing folder.

Reproduction steps:

1. Launch Cursebreaker
2. Allow auto-update to commence and finish.
3. Error printed at the end of update (unfortunately I didn't think to capture this, but it is similar to the error below)
4. Launch WOW
5. See this error:

```
Message: WTF\SavedVariables\Blizzard_Console.lua:1: unexpected symbol
Time: Sun Nov 22 20:07:38 2020
Count: 1
Stack: WTF\SavedVariables\Blizzard_Console.lua:1: unexpected symbol

Locals:
Lua Warning:
Message: WTF\SavedVariables\Blizzard_Console.lua:1: unexpected symbol
Time: Sun Nov 22 20:07:39 2020
Count: 2
```

Result:
Allowing auto-update to run effectively wiped the WTF folder due to this (probably minor) error.

Proposal:
1. Auto-update should not be the default command on launch. Allow users to decide when to launch.
2. Make it trivial for users to restore their backup within the Cursebreaker console.

**Comment by Frostea** [comment]
Addendum:
The backup made by Cursebreaker (presumably) prior to the update also contains the same error. I had to revert to an older backup.

**Comment by AcidWeb** [comment]
CurseBreaker is not making ANY modifications to WTF SV contents. So I could not corrupt contents of `WTF\SavedVariables\Blizzard_Console.lua` file as this application is never open these files for writing.

**Comment by Frostea** [comment]
The similar part I mention is specifically referring to the `unexpected symbol` bit, not the format that it prints out. Besides that, I don't recall what exactly was printed out. If CurseBreaker logs the error somewhere, let me know and I'll upload it.

**Comment by AcidWeb** [comment]
That would suggest that file was corrupted before even backup started. Sorry but issue you describing was not caused by CB.

**Comment by Frostea** [comment]
I figure it may be possible that this is due to my WOW crashing when I ran it earlier, hence causing an unexpected end of file somewhere. You said that CB doesn't write to WTF folder, but perhaps when making a backup of the folder it was affected by this. I guess this can be filed away as a known issue not caused by CB itself.

**Comment by AcidWeb** [comment]
Well WoW crashing definitely can cause WTF corruption. One of main reasons why WTF even need the backup.
