### ISSUE TITLE
CurseBreaker process running in background after update

### ISSUE THREAD

**Issue by zerbiniandrea** [AcidWeb/CurseBreaker#246]
After the update to v3.15.1 (20 nov), I've noticed that Curse Breaker was running in the background. I've closed the process and then I haven't seen it happening again until today's update (v3.15.2). 
After Curse Breaker updates to a newer version, it stays as a process in the background until I end the process myself. It didn't happen in any other scenario, so I guess something in the updates forces it to keep it running as a process.

![image](https://user-images.githubusercontent.com/43417875/99909603-deafd700-2ce9-11eb-9ac1-4a4d8aaf382d.png)

I've just noticed it cause my PC fans were running even when the PC was doing nothing so I've checked if something was running in background.

**Comment by AcidWeb** [comment]
Can't replicate.

**Comment by AcidWeb** [comment]
I tried to break update progress in every way I can imagine and not even once process was not closed properly. I have no idea what it is causing it for you.

Do you use headless mode?

**Comment by zerbiniandrea** [comment]
Nope, but I'm running it executing a simple .bat file to open it in Windows Terminal
`wt "C:\Program Files (x86)\World of Warcraft\_retail_\CurseBreaker.exe"`

**Comment by AcidWeb** [comment]
Try to use shortcut instead the bat file.
