### ISSUE TITLE
Create backup with command

### ISSUE THREAD

**Issue by Grawul** [AcidWeb/CurseBreaker#248]
Hi, right now I am missing the feature to trigger a backup over a command.
I am running the tool with auto backup off because I want to decide when to backup myself. But enabling auto-backup -> closing app -> opening again -> disabling auto-backup is quite a hassle.
If there would be a simple "backup" command I would be happy

**Comment by AcidWeb** [comment]
Yes. I agree. But for next few days I will be busy playing SL so not expect this feature soon :-P
