### ISSUE TITLE
Orphaned file cleanup

### ISSUE THREAD

**Issue by EvilGrinUK** [AcidWeb/CurseBreaker#249]
I would like a feature to be added to clean up orphaned files. Currently the addon is aware of these via the 'orphan' command. I have quite an old wow install folder with many hundreds of orphaned lua files. I would like to be able to clean these up. Ideally on a per character, realm or addon name basis. I imagine the orphan command could be extended to allow this?

**Comment by AcidWeb** [comment]
#108
