### ISSUE TITLE
Installing "Classic Quest Log for Classic" deletes other addons

### ISSUE THREAD

**Issue by adamgoon** [AcidWeb/CurseBreaker#25]
Installing for force-updating "Classic Quest Log for Classic" (wowi:24937-ClassicQuestLogforClassic) deletes all other addons in the Interface/Addon directory.

If I install this addon first, and then the other addons I use, it gets marked as modified:
![image](https://user-images.githubusercontent.com/14028858/66342803-2aff5280-e942-11e9-9bb1-7e2d3813c6bc.png)

**Comment by AcidWeb** [comment]
It use non-standard archive structure and check is failing to detect that.
