### ISSUE TITLE
"import install" not working if some sites are unreachable

### ISSUE THREAD

**Issue by Xalcon** [AcidWeb/CurseBreaker#250]
I wanted to reset my addons for shadowlands since I had one addon installed which was no longer available on curseforge and `uninstall` wouldn't do anything for said addon. I removed the 2 cursebreaker files (cache + json) from my wtf folder and run cursebreaker with the `import install` command. This fails to add curseforge addons since it crashes during the check of the tukui website.

My addon folder contains several addons (~60) from curseforge as well as elvui.

# Replication Steps
Run `import install` while some of addon repositories (i.e. tukui.org) is unavailable with some addons already present from curseforge as well as elvui.

# Expected Result
Addons from reachable repositories are added to the status index properly; addons fom unreachable repositories are reported to the standard output with a suitable error description.

# Actual Result
The command `import install` will fail with the following message without adding **any** addons to the index.
```
RuntimeError: Failed to parse addon data: HTTPSConnectionPool(host='www.tukui.org', port=443):
Max retries exceeded with url: /client-api.php?ui=elvui (Caused by
ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001D7BBF72E50>,
'Connection to www.tukui.org timed out. (connect timeout=5)'))
```

# Workaround
I was able to work around the issue for now by removing ElvUI from the addons folder and then running the `import install` command.

**Comment by AcidWeb** [comment]
This is terrible time for this type of operations. All addon sites have performance issues.

**Comment by stu177** [comment]
The `(read timeout=5)` I'm guessing is a 5 second timeout? Is it possible to increase this or have it incrementally increase after each timeout failure to account for high load periods?

**Comment by iktomi15** [comment]
To further clarify something that is likely known: this also includes first time installs.  I wanted to install it for the first time and so I attempted 'install ElvUI' and got the same error.  The next step was doing the download myself and doing a manual import, at which point I see the same behavior outlined above.

The timeout idea seems like it could be a great workaround.  Perhaps an optional switch to set a specific timeout if desired?

**Comment by AcidWeb** [comment]
Increasing of timeout will not change anything considering state of Tukui API.

**Comment by stu177** [comment]
The website is working albeit, slowly.

Doing a quick test in Chrome, for me, https://www.tukui.org/client-api.php?ui=elvui is resolving in anywhere between 4s and 15s.

So increasing the timeout would help.

Like @iktomi15 said, even just allowing the user to manually override the timeout would work without setting the timeout too high to prevent slow usability for most users.

**Comment by AcidWeb** [comment]
I'm have some more extensive information about state of Tukui API and I'm telling you it will not help. Not in a broader perspective.

Only reason why I keep this ticket open is a fact that I need to tweak install command so fail of single addon will not stop installing rest of them.

**Comment by stu177** [comment]
I don't see how simply letting users decide the duration of the timeout is a big deal, it's just giving users more control of how they can download addons.
