### ISSUE TITLE
Trojan found in cursebreaker.exe

### ISSUE THREAD

**Issue by zapruder327** [AcidWeb/CurseBreaker#251]
Detected: Trojan:Win32/Fuery.C!cl
Status: Quarantined
Date: 11/24/2020 11:50 AM
Affected items:
file: C:\Program Files(x86)\World of Warcraft\_classic_\CurseBreaker.exe
![Trojanalert](https://user-images.githubusercontent.com/20376190/100127456-20a55e00-2e4d-11eb-810d-29be36a4804f.PNG)

**Comment by AcidWeb** [comment]
No idea from where you got that file.

Current release is clean: https://www.virustotal.com/gui/file/23e03f45d2d3a1559878bd4a3450ffa3d69100a59f32a5b735069268f35a6862/detection
