### ISSUE TITLE
Does not detect updates on some addons

### ISSUE THREAD

**Issue by Beet4** [AcidWeb/CurseBreaker#252]
It appears that CurseBreaker does not detect that some addons are updated. Two examples below:

https://www.curseforge.com/wow/addons/adibags-zone-items/files
https://www.curseforge.com/wow/addons/adibags-prior-expansions

I assume that is it because these two examples does not tag their filenames with version numbers.

Is there anything to do about this?

**Comment by AcidWeb** [comment]
Yes issue is caused by lack of unique filenames. But I see that author already fixed it.
