### ISSUE TITLE
integrity check? +another more obscure idea

### ISSUE THREAD

**Issue by ANaPhOrAX** [AcidWeb/CurseBreaker#253]
is there a way for you to implement like an integrity check, where it can check if all the addons installed are like 'undamaged'? (or does it already do this?)

maybe in combination with like a reinstall function, where it can take already installed addons and like "refresh" their installs?

there was another idea I had, but this one's a bit more obscure: how about making it possible for cursebreaker to move unused addons to like a seperate directory.. because even addons that aren't used, still do slow the game down somewhat just by virtue of being in the addon directory.. so what if cursebreaker could be used to like enable/disable addons, and then move the disabled ones into another directory? and then if you re-enable them via cursebreaker itd move them back.. itd still keep them up to date as well, just not in the main addon folder, to speed up the game

**Comment by AcidWeb** [comment]
CB already detect addon modifications made after installation.

If you don't use addon just disable it. Disabled addons don't impact game speed.

**Comment by Pegoth** [comment]
If you have an addon installed and you modify it you will notice that the addon will be taggad as [modified](https://i.imgur.com/msiIQeq.png) and will not be updated. To redownload the addon you can type [force_update ADDONNAME](https://i.imgur.com/yiMwgMQ.png).
