### ISSUE TITLE
Failed to parse addon data (Tukui addons)

### ISSUE THREAD

**Issue by Beet4** [AcidWeb/CurseBreaker#254]
Have getting these messages for a couple of days now:
![image](https://user-images.githubusercontent.com/38279393/100554638-3b853180-3296-11eb-8709-f9e87f19a506.png)

And addons installed from tukui does not update. Something wrong with the API?

**Comment by AcidWeb** [comment]
Yes. TukUI site is crippled by traffic.

**Comment by AcidWeb** [comment]
#255
