### ISSUE TITLE
Getting an error after updating addons= RuntimeError: Failed to parse addon data: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by lucasnbraga** [AcidWeb/CurseBreaker#255]
![image](https://user-images.githubusercontent.com/30246110/100600741-76ac5280-32e0-11eb-8b0e-fb129f668461.png)

This error started happening and i do not know which addon is causing it

**Comment by JeremyMorton** [comment]
I am seeing similar:
```
RuntimeError: Failed to parse addon data: string indices must be integers
```

It happens with my GitHub addons, unfortunately, it causes `status` not to list them, so it's kind of a pain to figure out which addons to uninstall and re-install from cf:

**Comment by AcidWeb** [comment]
Upload yours `WTF/CurseBreaker.json`.

**Comment by JeremyMorton** [comment]
It started working again now.
[CurseBreaker.zip](https://github.com/AcidWeb/CurseBreaker/files/5615988/CurseBreaker.zip)

**Comment by Kazlehoff** [comment]
Hey Acid, im getting this issue as well, is not working currently.
[CurseBreaker.zip](https://github.com/AcidWeb/CurseBreaker/files/5616239/CurseBreaker.zip)
(note, my archive was a .7z file but Github was like "wE dOnT lIKe tHaT fIlE" so i renamed it zip. if you have issues opening, just rename it .7z again, or PM me on Discord through the Elv Discord :P lol

**Comment by AcidWeb** [comment]
Well TukUI API is a burning nightmare currently so issues are not a surprise. Main problem I see here are unhelpful error messages and that need to be fixed.

**Comment by AcidWeb** [comment]
OK. I see the issue. Part of Tukui API was completely disabled. That cause most of the problems.

**Comment by AcidWeb** [comment]
I got confirmation that Tukui API cache was modified. So currently CB support is completely broken.

**Comment by AcidWeb** [comment]
Currently, API is a little in flux. I will release the update when it stabilizes a little.

**Comment by jdhorner** [comment]
> 
> 
> I got confirmation that Tukui API was modified. So currently CB support is completely broken.

As a developer, isn't it great when a service completely changes their API without any notification **and** without any sort of backwards compatibility, so at least if things fail, they fail gracefully?

**Comment by Kazlehoff** [comment]
Unfortunate. have they provided any eta of the resumption of the functionality?

**Comment by AcidWeb** [comment]
v3.15.3 will contain temporary fix for this issue. Proper update will follow later.
