### ISSUE TITLE
WTF Backup errors in v3.15.3

### ISSUE THREAD

**Issue by EvilGrinUK** [AcidWeb/CurseBreaker#257]
I have just in place upgraded to 3.15.3, it has then run an automatic update and WTF backup. The WTF backup got stuck until I hit Ctrl-C. Then I got a screenful of errors complaining about duplicate file names.

![image](https://user-images.githubusercontent.com/2217729/100871920-ed8c4b80-3498-11eb-836a-2d20518f160e.png)

**Comment by AcidWeb** [comment]
Try to delete (or move) today backup file (if it exist) and try again. It is crashing again?

**Comment by EvilGrinUK** [comment]
That has fixed it.
