### ISSUE TITLE
CurseBreaker stopped working completely

### ISSUE THREAD

**Issue by wowTurron** [AcidWeb/CurseBreaker#258]
...with the message on start:
_RuntimeError:_ _Failed to parse addon data: Detected a Cloudflare version 2 challenge, This feature
is not available in the opensource (free) version._

**Comment by AcidWeb** [comment]
Do you have any WoWInterface addons or all are CurseForge ones?

**Comment by AcidWeb** [comment]
OK. I now understand the issue. OW migration marked some popular addons as abandoned. That removed them from source I use to get addon data.

If that data is missing CB is trying to get them from secondary location that is secured by Cloudflare. If your connection will be blocked I can't do anything about it. I don't have any workaround for now.

PS. Error message is returned by cloudscraper library. There is no premium version of CurseBreaker :-P

**Comment by wowTurron** [comment]
I think I have 55 addons from CurseForge and 1 from WoWInterface(this 1 just missed on CF). It might be better if CB just ignores addons with missing data. Because otherwise CB is absolutely useless for me right now, I can't even run the _status_ command to remember which addon is came from WoWInterface.

**Comment by AcidWeb** [comment]
It definitely should not fail checking all addons - just ones that fail to get proper data. I will fix it Soon™.

**Comment by AcidWeb** [comment]
v3.15.4 is fixing this issue only partially. Addons not affected by this problem will start to update but rest will still crash until:
A) Cloudflare will stop blocking traffic from current user.
B) Project abandoned flag will be removed and my backend will update addon data.

**Comment by wowTurron** [comment]
Yes, thank you very much - now "normal" addons are updated without problems, and problematic addons are displayed after the update is over, this is great!
And by the way(I just don't know where I can ask a General question? is there some forum?) - some normally updated addons have a special mark in the update table in the form of **[!]** after the version number of the addon. Example: _90000.48-Release [!]_. I just wonder what is it for?
