### ISSUE TITLE
Add support for TukUI Gitlab links

### ISSUE THREAD

**Issue by lifebound** [AcidWeb/CurseBreaker#259]
Cursebreaker supports github repositories, but not the TukUI gitlab repositories. This can create a problem when the TukUI public-facing link has not been updated to match the latest iteration available on Gitlab. For example:

https://www.tukui.org/addons.php?id=140 - Valid link for Cursebreaker, underlying download not updated since 8.2

https://git.tukui.org/NihilisticPandemonium/RematchElvUISkin - link not valid for Cursebreaker, addon working correctly with 9.x

proposed solution: following the nomenclature of github, either supplying the full URL or tg:[username]/[repo_name]

**Comment by AcidWeb** [comment]
It is the same problem as GitHub support. Most of repositories can't be used directly as addon source. GitHub support only parse packaged releases not bare repo itself.

**Comment by dark0dave** [comment]
You can make an exception for tukui, as its a different path ie not github.com, happy to donate the source code for it.

**Comment by AcidWeb** [comment]
OK> I will add Tukui dev version.
