### ISSUE TITLE
Cross Platform Compatibility

### ISSUE THREAD

**Issue by NCC-Lykos** [AcidWeb/CurseBreaker#26]
So I've been looking into making this work cross platform... 

It seems it could be possible. Are you using py2exe for this? macOS supports py2app which could *possibly* do the same thing for macOS users such as myself... I'd love to dump Twitch on its face.

Would there be any interest in using more cross platform friendly code if you had a dedicated tester for such a project?

**Comment by AcidWeb** [comment]
PyInstaller. It is only usable tool for code freezing this days.

Freezing the code is not a problem. But I have some doubts that time needed for coding, QA and long term support of other platforms that have very small market share in good investment,

**Comment by NCC-Lykos** [comment]
> PyInstaller. It is only usable tool for code freezing this days.
> 
> Freezing the code is not a problem. But I have some doubts that time needed for coding, QA and long term support of other platforms that have very small market share in good investment,

I'll look at pyinstaller.

There is actually quite a large macOS community for WoW, large enough they have a category dedicated to them on the wow forums. I'm sure you would gain a lot of popularity there, the Linux guys can figure it out for themselves like they enjoy doing xD

**Comment by AcidWeb** [comment]
I will think about it.

**Comment by NCC-Lykos** [comment]
> Also barging about forum when game officially support macos is not very powerful move :-P

I was just noting that the community and want was great enough for Blizz to support it for macOS lol mainly saying it isn't a hack to use. I know that gaming on a mac is always frowned upon but hey it happens, hackintosh is a real thing and I love my macOS. Apple hardware on the other hand is garbage lol

I've started poking around to see if it could even be a possibility. Python isn't my thing though, C# and C++ is more my mainstream.

**Comment by NCC-Lykos** [comment]
I've got it running, I just need to do some cleanup. I'll make a fork and let you inspect it. I won't be doing a pull request though as I don't know how you want to handle the OS Specific things, but the changes are very minimal.

![image](https://user-images.githubusercontent.com/24256285/66683265-a744af00-ec3c-11e9-8111-925a109282d8.png)

**Comment by AcidWeb** [comment]
Don't invest too much time in your changes as I probably rewrite them from scratch anyway.

**Comment by NCC-Lykos** [comment]
> Don't invest too much time in your changes as I probably rewrite them from scratch anyway.

Of course, I'm only making sure functionality is completely there. So far I have completely replicated the Windows functionality. The only issue is the table that the addons display in, which I assume is a font issue.

![image](https://user-images.githubusercontent.com/24256285/66685880-4e2c4980-ec43-11e9-8fe1-90a7850581c2.png)

**Comment by Masgalor** [comment]
Hey there, just for your information.
I made a Linux compatible fork of your project, maybe it has some value to your cross platform efforts.
https://github.com/Masgalor/CurseBreaker

By the way, the table design is there broken as well.
It is some bug in `from terminaltables import SingleTable`, thy use outdated encodings on *nix systems. But using DoubleTables works fine.

**Comment by NCC-Lykos** [comment]
> By the way, the table design is there broken as well.
> It is some bug in `from terminaltables import SingleTable`, thy use outdated encodings on *nix systems. But using DoubleTables works fine.

Ah nice, that made things look better.

**Comment by AcidWeb** [comment]
I almost finished implementing support for macOS and Linux. During next days I will test a little and make a pipeline to build proper binaries.
