### ISSUE TITLE
Crash problem

### ISSUE THREAD

**Issue by OoLucasoO** [AcidWeb/CurseBreaker#260]
Hi, yesterday I've updated the version 3.15.4, and it worked well. But today when I run the cursebreaker to see if there is any updates for UIs, it crashs.

I can't upload a complete sreenshot because it comes so fast the I can only get this:
![crash problem](https://user-images.githubusercontent.com/14848127/101231249-e6f21400-36e4-11eb-871d-bb90fe63d7e5.png)

I'am not sure it's due to my system or network or there is somethings wrong with cursebreaker. 

My system is "win8" by the way. 

Thank you.

**Comment by AcidWeb** [comment]
You don't have connection with Google Cloud Storage.

**Comment by OoLucasoO** [comment]
All right....Thanks a lot ^^
