### ISSUE TITLE
Installing dependencies

### ISSUE THREAD

**Issue by Beet4** [AcidWeb/CurseBreaker#262]
Is it really necessary that CurseBreaker tries to install dependencies for installed addons every time it is run, even though any of those addons are not updated?

![image](https://user-images.githubusercontent.com/38279393/101289829-0d0bd700-37ff-11eb-8dc6-5ee5b89ffea1.png)

I have ElvUI AdiBags installed and two AdiBags extensions installed which has AdiBags as dependency. CurseBreaker tries to install ElvUI AdiBags every time it is run.

**Comment by AcidWeb** [comment]
It should do this only once. I guess it is clashing with a fact your ElvUI AdiBags installation is modified. Upload yours `WTF/Cursebreaker.json`.

**Comment by Beet4** [comment]
I've ivestigated more and it does not happen with standard AdiBags but it does with unmodified ElvUI AdiBags:
![image](https://user-images.githubusercontent.com/38279393/101376168-86afcd80-38b0-11eb-8b05-fb482e0cea4e.png)

I guess it is because the standard AdiBags is the actual dependency of the extensions I use and not ElvUI AdiBags.

Attaching my Cursebreaker.json
[CurseBreaker.zip](https://github.com/AcidWeb/CurseBreaker/files/5653833/CurseBreaker.zip)

Maybe some sort of expection can be made?

ElvUI AdiBags is just a skinned version of AdiBags.

**Comment by AcidWeb** [comment]
Yep. Plugins have declared "normal" version of _AdiBags_ as dependency. So CB is trying to meet that dependency but directory name is already claimed by _ElvUI AdiBags_.

I will think how to fix it.

**Comment by AcidWeb** [comment]
It will be partially solved in next release by by adding the option to ignore deps during initial installation.

After update remove adibags plugins and install them again with `-d` flag. That should fix your issues.

**Comment by Beet4** [comment]
Doesn't seem to help, do I have to clear some old cached files or something?

![image](https://user-images.githubusercontent.com/38279393/102532599-7ebc0e80-40a4-11eb-9b09-5c02392725d9.png)

**Comment by AcidWeb** [comment]
Show me output of `show dependencies`

**Comment by Beet4** [comment]
![image](https://user-images.githubusercontent.com/38279393/102641711-d3bb5b80-415c-11eb-8626-fead04ab64f9.png)

**Comment by AcidWeb** [comment]
OK. Found yet another bug. I will fix it next release.
