### ISSUE TITLE
Display local/remote version number if status is "Modified"

### ISSUE THREAD

**Issue by muiqo** [AcidWeb/CurseBreaker#264]
First of all: This is an amazing application <3

**Question:** Is there a way to display the local and remote version number if the status of an addon is "Modified"?

I tweaked a couple of my addons and i'd love to see if the remote version is the current one, or if there is an actual update available (so i can diff the changes after a force_update).

Thanks again!

**Comment by AcidWeb** [comment]
You already see different status when modified addon have update.

**Comment by muiqo** [comment]
Sorry my bad, seems i didn't noticed it the last time. Cheers and happy holidays!
