### ISSUE TITLE
3.16 won't start up on Mac

### ISSUE THREAD

**Issue by khaosspawn** [AcidWeb/CurseBreaker#266]
3.15.4 seems to work just fine - but it auto updates to 3.16 which gives the following errors. I hope it can be easily fixed. This is the best addon manager I've ever used for WoW!!

──────────────────────────────────────── CurseBreaker v3.15.4 ─────────────────────────────────────────

Updating CurseBreaker...
Update complete! The application will be restarted now.

Changelog:
* Added command to execute manual backup
* Added support for dev version of Tukui
* Allowed to ignore the dependencies during addon installation
* Bugfixes and tweaks

Press any key to continue . . .
Traceback (most recent call last):
  File "CurseBreaker.py", line 13, in <module>
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "pyperclip/__init__.py", line 52, in <module>
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: dlopen(/var/folders/ny/pgyb4c5171g2l9t8dl0qm8xr0000gn/T/_MEIFXA8Xo/_ctypes.cpython-39-darwin.so, 2): Symbol not found: _ffi_closure_alloc
  Referenced from: /var/folders/ny/pgyb4c5171g2l9t8dl0qm8xr0000gn/T/_MEIFXA8Xo/_ctypes.cpython-39-darwin.so (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libffi.dylib
 in /var/folders/ny/pgyb4c5171g2l9t8dl0qm8xr0000gn/T/_MEIFXA8Xo/_ctypes.cpython-39-darwin.so
[8903] Failed to execute script CurseBreaker

**Comment by AcidWeb** [comment]
What macOS version you use?

**Comment by khaosspawn** [comment]
10.14.6

**Comment by AcidWeb** [comment]
I'm surprised that old versions started at all. Binaries are build using macOS 10.15 and I don't have access here to older workers.

Not sure if I can fix it.

**Comment by khaosspawn** [comment]
Is there any way to get a 3.15.4 that doesn't auto-update? That version worked just fine.

**Comment by AcidWeb** [comment]
Old binaries are still in releases. Set `CURSEBREAKER_VARDEXMODE` environment variable - that will disable auto-update.

**Comment by khaosspawn** [comment]
TYVM! 3.15.4 working again!

**Comment by AcidWeb** [comment]
Please check if this binary crash too: https://github.com/AcidWeb/CurseBreaker/suites/1693799011/artifacts/31817173

**Comment by khaosspawn** [comment]
The binary works! I have the CURSEBREAKER_VARDEXMODE enabled still. Let me know if I should remove it.

**Comment by AcidWeb** [comment]
I will release 3.16.1 soon. Wait for it then remove `CURSEBREAKER_VARDEXMODE` and let it autoupdate.

**Comment by khaosspawn** [comment]
Will do - thank you very much!
