### ISSUE TITLE
Adding Townlong Yak as an addon source

### ISSUE THREAD

**Issue by carlschoeneich** [AcidWeb/CurseBreaker#267]
Hey there,
I was wondering if it was possible to add Townlong Yak's website (https://www.townlong-yak.com/) as an addon source since they have some very useful addons which aren't uploaded to curseforge or not updated there regularely.

**Comment by lucasnbraga** [comment]
Townlong Yak's author has abandoned curseforge and began hosting his addons by himself.

Seeing it added to cursebreaker would be great since some of them like Opie and Master Plan are/were used by many.

**Comment by AcidWeb** [comment]
I would love to do it but his page don't provide any form of API and CB have strict no scraping policy.
