### ISSUE TITLE
Details Addon Detection

### ISSUE THREAD

**Issue by RC-Projects** [AcidWeb/CurseBreaker#268]
CurseBreaker is no longer detecting the correct version of details. It looks like it is only working with the outdated "Shadowlands" version as seen here:
https://www.curseforge.com/wow/addons/details2

The correct version that should be detected is here:
https://www.curseforge.com/wow/addons/details

To clarify on the problem, having details installed manually will not be detected by CurseBreaker, nor a auto install will not download the correct files.

**Comment by AcidWeb** [comment]
Both `install cf:details` and importing current version `DetailsRetail.9.0.2.8102.144` is working correctly.

I seems that you have details2 project currently installed. Removed it and install proper project.

**Comment by RC-Projects** [comment]
> Both `install cf:details` and importing current version `DetailsRetail.9.0.2.8102.144` is working correctly.
> 
> I seems that you have details2 project currently installed. Removed it and install proper project.

I have already tried this. I have manually installed Details1, and it is not being detected. Is there a way to clear the DB or something that may correct this issue?

**Comment by AcidWeb** [comment]
It was never detecting manually installed addons by default. You need to run `import` command.

**Comment by RC-Projects** [comment]
> It was never detecting manually installed addons by default. You need to run `import` command.

Got it, thanks!
