### ISSUE TITLE
Shows available updates for Plater Mods/Scripts that already are updated but where the old version is still in "recently removed"

### ISSUE THREAD

**Issue by Beet4** [AcidWeb/CurseBreaker#269]
Hi!

WA Companion has this bug and I have opened an issue here: https://github.com/WeakAuras/WeakAuras-Companion/issues/912

I thought I would post this here as well as CurseBreaker is suffering from the same behaviour. I do not know if it is a fix needed in WA Companion/CurseBreaker or Plater. But I was thinking it's good to inform you.

**Comment by AcidWeb** [comment]
It sound like something that should be fixed upstream but time will tell.

**Comment by cont1nuity** [comment]
Nothing to be done here, as trashed data is not checked. All (in-)active profiles are checked, however. In this case, the mods/scripts are used in several profiles.
Details in https://github.com/WeakAuras/WeakAuras-Companion/issues/912

**Comment by Beet4** [comment]
Thanks, solved. Closing.
