### ISSUE TITLE
2.8.0 broken text in W7 CMD, fine in CMDER

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#27]
Broken again in W7 CMD:
![](https://i.imgur.com/6IjHWVA.png)

**Comment by AcidWeb** [comment]
Nothing changed that could break it again.

**Comment by AcidWeb** [comment]
I checked it once more and I have no idea what is causing it.
Considering that in 90 days Windows 7 is officially and fully EOL I don't plan to continue this topic.
