### ISSUE TITLE
Flag to Run Non-Interactive

### ISSUE THREAD

**Issue by siklr** [AcidWeb/CurseBreaker#270]
By default, it seems that the application will automatically update if no keypress is registered in a certain timeframe. However, a keypress is needed after the update process to close the application. Would it be possible to pass a command line argument to disable this and simply exit? Trying to automate the update process without external tools and this change would be helpful.

**Comment by AcidWeb** [comment]
Use headless mode.

**Comment by siklr** [comment]
For some reason I completely missed that in the docs. Apologies!
