### ISSUE TITLE
Possibility of integration to Wago ElvUI profiles

### ISSUE THREAD

**Issue by lucasnbraga** [AcidWeb/CurseBreaker#271]
Since Cursebreaker supports Weakauras from WAGO, i wondered if it could support ElvUI profiles too since they exist on wago. 
Supporting those profiles could be great, since then it would be easier to update them by using cursebreaker rather than visiting wago, just like how the updates show up in game for weakauras.

This is a feature question not exactly a feature request either.

**Comment by cont1nuity** [comment]
This needs to be supported by ElvUI first.

**Comment by AcidWeb** [comment]
It would need to be supported first by:

- ElvUI
- Wago
- WeakAuras Companion

And ElvUI don't plan to add it.
