### ISSUE TITLE
[BUG] CB isn't updating ElvUI:Dev anymore

### ISSUE THREAD

**Issue by SHJordan** [AcidWeb/CurseBreaker#272]
RuntimeError: Failed to parse addon data: HTTPSConnectionPool(host='git.tukui.org', port=443): Max retries exceeded with
url: /api/v4/projects/60/repository/branches/development (Caused by
ConnectTimeoutError(<urllib3.connection.HTTPSConnection object at 0x000001B79A173CA0>, 'Connection to git.tukui.org
timed out. (connect timeout=5)'))

Can you confirm?

**Comment by AcidWeb** [comment]
Entire ElvUI site is down.

**Comment by SHJordan** [comment]
Haha, didn't bother checking, my bad.

Em sáb., 2 de jan. de 2021 às 10:22, Paweł Jastrzębski <
notifications@github.com> escreveu:
