### ISSUE TITLE
Dependencies from Another Source are unidentified

### ISSUE THREAD

**Issue by Crelam** [AcidWeb/CurseBreaker#274]
I have Opie installed from Towlong Yak (https://www.townlong-yak.com/addons/opie) and Opie Masque installed from Curse (https://www.curseforge.com/wow/addons/opie-masque).

When I update, CurseBreaker sees that Opie Masque has a dependency of Opie, but does not realize it is already installed and attempts to install it again presumably from curse which fails.

Thank you for your time.

**Comment by AcidWeb** [comment]
`uninstall OPie Masque`
`install -d cf:opie-masque`
