### ISSUE TITLE
CB pauses Addon Updates and Backup of WTF directory when using the vertical scrollbar of the DOS-box window

### ISSUE THREAD

**Issue by Dahustler** [AcidWeb/CurseBreaker#275]
Hello,

maybe this is how any command line tool behaves and not a CB issue, but while clicking on the vertical scrollbar on the right side of the cmd window and scrolling up and down, Addon Updating and WTF Directory Backup just pauses. You dont even have to scroll up and down, just click on the vertical scrollbar and hold it is enough to pause any activity.

**Comment by AcidWeb** [comment]
It is default behavior of Windows CMD. Nothing to fix here. I would suggest to use Windows Terminal instead.
