### ISSUE TITLE
Updating Cursebreaker fails

### ISSUE THREAD

**Issue by Sakeros** [AcidWeb/CurseBreaker#276]
Hello,

sometimes the update of cursebreaker fails due to a timeout. When this happens the cursebreaker.exe is renamed to cursebreaker.exe.old and I have to manually rename it back to start it again. This has been happening occasionally since I first used it in August 2020. Unfortunately no log files were created.
<img width="1111" alt="cursebreakerError" src="https://user-images.githubusercontent.com/77746825/105215385-819d9980-5b51-11eb-90ad-95e9b8c3f944.png">

**Comment by AcidWeb** [comment]
For last few months users from Germany have issues with GitHub CDN. It is not related with this project.

**Comment by Sakeros** [comment]
That may the case but the exe file shouldn't be left in that state regardless.

**Comment by AcidWeb** [comment]
I forgot I already fixed it in 3.17.0 -.-
Next failed update will recover correctly.
