### ISSUE TITLE
Error when updating, can't figure out the source of it

### ISSUE THREAD

**Issue by lucasnbraga** [AcidWeb/CurseBreaker#277]
So today i got this error:

**RuntimeError: Failed to parse addon data: HTTPSConnectionPool(host='api.mmoui.com', port=443):
Max retries exceeded with url: /v3/game/WOW/filedetails/20958.json (Caused by
NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000205E71A1130>: Failed to
establish a new connection: [Errno 11002] getaddrinfo failed'))**

Except i never heard of a mmoui.com and never installed an addon from there, is this the backend of some other site like curse or wowinterface?

**Comment by AcidWeb** [comment]
One of WoWI addons fail to update.
