### ISSUE TITLE
CB hung when uninstalling when command had wrong/incomplete addon name. 

### ISSUE THREAD

**Issue by Barleduq** [AcidWeb/CurseBreaker#280]
I chose to uninstall Master Plan. I typed 'uninstall Master' and failed to hit tab to complete the name, and hit return automatically. After 5 minutes, I control-c'ed and got a traceback.  Perhaps a more graceful failure mode?  Ubuntu 18.04, not sure which terminal program. Sorry for bad formatting - I'm not sure of a better way to get the info to you. MInd you, I'm *running* CurseBreaker, I had just used it to update everything, and checked help to see that you now install from townlong-yak. I legit squee-ed, because I'd just found out about Venture Plan, and had lamented the loss of Master Plan.

Cut&Paste from terminal:
CB> status -s Master Plan
1/1 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ |
┌───────────────┬────────────────────────────────────┬─────────┐
│    Status     │ Name / Author                      │ Version │
├───────────────┼────────────────────────────────────┼─────────┤
│ Up-to-date CF │ Master Plan by Forge_User_16328612 │ 0.119   │
└───────────────┴────────────────────────────────────┴─────────┘
CB> uninstall Master
0/0 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ |    
^C╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/amqueue/CurseBreaker.py:470 in c_uninstall                             │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/CurseBreaker.py'         │
│                                                                              │
│ /home/amqueue/rich/progress.py:629 in finished                               │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/rich/progress.py'        │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyboardInterrupt: 

During handling of the above exception, another exception occurred:

╭───────────────────── Traceback (most recent call last) ──────────────────────╮
│ /home/amqueue/CurseBreaker.py:894 in <module>                                │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/CurseBreaker.py'         │
│                                                                              │
│ /home/amqueue/CurseBreaker.py:191 in start                                   │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/CurseBreaker.py'         │
│                                                                              │
│ /home/amqueue/CurseBreaker.py:479 in c_uninstall                             │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/CurseBreaker.py'         │
│                                                                              │
│ /home/amqueue/rich/progress.py:697 in __exit__                               │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/rich/progress.py'        │
│                                                                              │
│ /home/amqueue/rich/progress.py:676 in stop                                   │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/rich/progress.py'        │
│                                                                              │
│ /home/amqueue/rich/progress.py:920 in refresh                                │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/rich/progress.py'        │
│                                                                              │
│ /home/amqueue/rich/progress.py:926 in get_renderable                         │
│                                                                              │
│ [Errno 2] No such file or directory: '/home/amqueue/rich/progress.py'        │
╰──────────────────────────────────────────────────────────────────────────────╯
KeyboardInterrupt: 
[12001] Failed to execute script CurseBreaker

**Comment by AcidWeb** [comment]
There is something definitely wrong as every command with incorrect addon name is freezing the application.

**Comment by AcidWeb** [comment]
It looks like progress bar library behavior changed and it not leave loop correctly.
