### ISSUE TITLE
Flag Addon not to update

### ISSUE THREAD

**Issue by TheOSC** [AcidWeb/CurseBreaker#281]
I use a few addons that are no longer supported, but that are still hosted on the Curse website. In order to get them working I have modified some of the XML code to restore functionality broken by Blizzard updates over the years.

I also use a tool (Resilio Sync) to synchronize my UI between multiple computers. This means that when addons are updated through the sync tool EVERY addon gets flagged as modified and I have to run a force_update to get them up to date.

The problem is this also force updates the old unsupported addons, and I have to go back into the XML file and either modify the code again, or restore the file from a separate folder on my computer.

It would be great if there was a way to just flag an addon to ignore updates as I know I am not the only person out there who uses addons which are no longer in development but are kept alive by the fans and community of said addons.

The primary offender in my case is Minimap Button Frame which has broken code on lines 3 and 118 of the MBF XML file. I know this has been brought up in the past and the general consensus was "I don't want people complaining about broken addons when they don't keep them up to date". But I also think anyone who is smart enough to lock an addon from updating through an intentional command is also smart enough to realize that that broken addon is likely out of date and may require an update if it is still in development.

There is practical application to users to have this level of control over their interface and I really hope you will reconsider your stance on this feature as it is breaking the functionality of CurseBreaker for me, and I absolutely LOVE this program. (I preach the value of it over every other addon manager in the game and have converted almost all of my guild to it at this point.)

**Comment by AcidWeb** [comment]
There is already option to ignore updates `toggle pinning` but it will not help you much as you will override the lock with your forced updates after sync.

I would suggest to not track that addons in CurseBreaker at all.

**Comment by TheOSC** [comment]
How do I exclude the addon from being tracked by CurseBreaker? That sounds like a great plan.

**Comment by AcidWeb** [comment]
`uninstall` with `-k` flag.

**Comment by TheOSC** [comment]
Perfect this seems to work exactly as I needed!
