### ISSUE TITLE
Townlong Yak addon showing as installed and unknown

### ISSUE THREAD

**Issue by Kazlehoff** [AcidWeb/CurseBreaker#283]
I installed Venture Plan from Townlong yak a while ago. seeing that CB now also supports TY addons, I installed it through CB "install ty:venture-plan" it shows up as an installed addon in the update list, but when running the import command, the venture plan folder shows up as an unknown directory.

**Comment by AcidWeb** [comment]
It is expected behavior. `import` support only addons on CF.

**Comment by Kazlehoff** [comment]
![image](https://user-images.githubusercontent.com/52207847/107277523-8489fc80-6a22-11eb-83df-00e58d7fcfc8.png)
but if CB has installed the addon, and is managing updates for it, shouldn't it not be an unknown directory?

**Comment by AcidWeb** [comment]
It is working as designed. This command purpose is just initial configuration.

**Comment by Kazlehoff** [comment]
okay, thanks
