### ISSUE TITLE
Automatically created release zip not read by CurseBreaker

### ISSUE THREAD

**Issue by phys1ks** [AcidWeb/CurseBreaker#286]
Hey there, hopefully you can help me shine some light on this issue... 

We use a workflow to automatically create release zips of our addon. They can be downloaded and installed just fine manually, but CurseBreaker returns the following..

![image](https://user-images.githubusercontent.com/64342930/108091791-a9452c00-7041-11eb-80cd-123642461183.png)

However if I manually zip the same folder locally, and upload the zip file manually to the release then it reads it fine. We are using the following script to create the zip file -> https://github.com/thomas-frantz/CoreLoot/blob/master/.github/workflows/TaggedRelease.yml

Is it possible there is some kind of issue with the way CurseBreaker reads this archive vs how other apps read the archive? Is there something I can do different other than manually uploading the addon to fix it on my end? Is there something that could be done to fix it on CurseBreakers end? The workflow is just using Debians zip\unzip, nothing special.

**Comment by AcidWeb** [comment]
Automatically uploaded ZIP file have content_type set to `application/octet-stream`. And CB read only `application/x-zip-compressed` and `application/zip`.

**Comment by phys1ks** [comment]
> Automatically uploaded ZIP file have content_type set to `application/octet-stream`. And CB read only `application/x-zip-compressed` and `application/zip`.
> 
> I would suggest to use: https://wow.gamepedia.com/Using_the_BigWigs_Packager_with_GitHub_Actions

Fantastic! Thank you so much!
