### ISSUE TITLE
Not getting latest version of addon

### ISSUE THREAD

**Issue by boohyaka** [AcidWeb/CurseBreaker#287]
Hi there, this add-on has a new release (1.20): https://www.curseforge.com/wow/addons/skillet-classic/

But CurseBreaker keeps getting the older release:

![image](https://user-images.githubusercontent.com/31538990/108357240-750e6e80-71ed-11eb-99df-f2fe371c56a0.png)

They apparently merged/changed releases with the renaming to this "old" package, but yet CB doesn't get the latest one.

Is it a problem on their end and I should ask them instead?

Thanks as usual for your awesome updater.

**Comment by AcidWeb** [comment]
This issue was caused by project rename and backend cache on my side.

Try again in 12h and check if it still installs the old version

**Comment by boohyaka** [comment]
Brilliant, thanks for the ultraquick answer!

**Comment by boohyaka** [comment]
confirmed fixed :) thank you!
