### ISSUE TITLE
[Feature] Auto Adventure Report for Venture Plan

### ISSUE THREAD

**Issue by stefan0uh** [AcidWeb/CurseBreaker#288]
Would be cool if you could automatically send the string from `VenturePlan.lua`  to https://www.townlong-yak.com/addons/venture-plan/submit-reports when I start CurseBreaker.

**Comment by AcidWeb** [comment]
Sorry. Implementing that feature would require more work that is worth. Plus CB by design is not modifying contents of files in WTF directory.
