### ISSUE TITLE
[feature request] timestamp following operations like update, status

### ISSUE THREAD

**Issue by brucek2** [AcidWeb/CurseBreaker#289]
Thanks for this amazing tool. I like it so much I keep a terminal tab open for it near permanently. That's convenient but sometimes it means I forget how recently I last ran it. What would you think of adding a timestamp that prints at the end of each update or status report?

**Comment by AcidWeb** [comment]
Start it in headless mode. Log file have timestamp.

**Comment by brucek2** [comment]
OK, thank you.
