### ISSUE TITLE
Possibility to lock a wow version

### ISSUE THREAD

**Issue by NicciZar** [AcidWeb/CurseBreaker#291]
Feature Request:
Have CurseBreaker target a specific game version so it wont update past the locked target version. 
It should also download the version applicable for this version ( maybe a range of versions because some addons don't get updated for each version but they still work fine..)

**Comment by AcidWeb** [comment]
And what usercase this feature have? Not counting updating addons too soon when US is already updated and EU not.

**Comment by NicciZar** [comment]
The Usecase would be to not update the Addons past a specified game version.
This would be great for people who play on non official servers. (because the game version usually doesn't change..)

They would still be able to use the CurseBreaker tool to download / install these addons but then the Tool sees that it shouldnt update the addons past the locked version so it stays on that version.

**Comment by AcidWeb** [comment]
Sorry but better support for pirate servers is not something I care about.
