### ISSUE TITLE
Not updating.

### ISSUE THREAD

**Issue by SHJordan** [AcidWeb/CurseBreaker#294]
Hi today i tried updating my addons and got this message:

> RuntimeError: Failed to parse addon data: HTTPSConnectionPool(host='api.mmoui.com', port=443): Read timed out. (read
timeout=5)

Can you help me?

**Comment by SHJordan** [comment]
But why would it break the whole addon update process?

**Comment by AcidWeb** [comment]
It is not breaking entire process. Just for WoWI addons.

**Comment by SHJordan** [comment]
seems to be fixed now, closing. but it was stucking on first addon update.

> It is not breaking entire process. Just for WoWI addons.

seems to be fixed now, closing. but it was stucking on first addon update.

**Comment by AcidWeb** [comment]
That should definitely not happen.
