### ISSUE TITLE
Scale TUI to terminal size

### ISSUE THREAD

**Issue by wiiittttt** [AcidWeb/CurseBreaker#295]
Is there an option (or is possible to add one) for resizing the TUI to the current terminal size, instead of resizing the terminal to the TUI?

Use case: I typically like to keep my windows in a specific layout using PowerToys, but the terminal resizing messes with that layout.

If it's not possible to scale the TUI size, could there be an option to simply disable the terminal resizing, leaving the TUI the same. This would still allow window layouts to remain constant.

**Comment by AcidWeb** [comment]
TUI is already resizing to the window size. I just force terminal size on Windows when default terminal emulator is used to workaround multitude of issues created by that terribly outdated software.

I highly suggest to switch to something newer like [Windows Terminal](https://aka.ms/terminal-preview).

**Comment by wiiittttt** [comment]
I grabbed Windows Terminal and TUI resizing is working as intended. Appreciate the info.
