### ISSUE TITLE
uri_integration?

### ISSUE THREAD

**Issue by ClockworkGod** [AcidWeb/CurseBreaker#297]
is there something else that you are supposed to do to get this to work other than run the command? how is it supposed to work in the first place?

**Comment by AcidWeb** [comment]
It should display regedit dialog with question if you want to import the reg file.

**Comment by ClockworkGod** [comment]
assuming I'm understanding this right then, when I go to curse-forge and click the install button, it should launch curebreaker and install the addon then right, or am misinterpreting this?

**Comment by AcidWeb** [comment]
It should open separate OW page and then start CF - yes.

**Comment by ClockworkGod** [comment]
hmm, well on waterfox it doesn't do that, it just takes you to the overwolf app page.

**Comment by AcidWeb** [comment]
Hard to say how URI handlers are processed by your browser. `uri_integration` just add registry entries to tell system what to start when `twitch://`, `curseforge://` and `weakauras-companion://` is executed.
