### ISSUE TITLE
RuntimeError: ElvUI and Tukui cannot be installed this way.

### ISSUE THREAD

**Issue by Kriptoker** [AcidWeb/CurseBreaker#299]
I receive the aforementioned title as an error when trying to install a specific TBC Classic Addon Module for ElvUI.

The URL is https://www.tukui.org/classic-tbc-addons.php?id=11 which is for ElvUI TauntAlert.
I use the shorthand **install tubc:11** (as well as the full URL), and both result in the error.

**Comment by AcidWeb** [comment]
This is a bug. I will fix it soon.

**Comment by Kriptoker** [comment]
Awesome! Thank you for providing such an amazing application!
