### ISSUE TITLE
Upgrade from Alpha to Beta

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#3]
CurseBreaker doesn't seem detect the latest Beta(v2.9.5-beta2) of Chinchilla Minimap as an upgrade from the previous Alpha (v2.9.5-beta1-4-g8bcebbb-alpha).

https://www.wowace.com/projects/chinchilla/files

**Comment by AcidWeb** [comment]
This is a bug in dev version detection. I will fix it soon.

**Comment by tordenflesk** [comment]
Same issue with Beta/Alpha->Release. Bigwigs stays at v149.3-18-g9ff3d8a instead of upgrading to V150 Release.

**Comment by AcidWeb** [comment]
Eh I made a typo.
