### ISSUE TITLE
Linux binary does not come executable

### ISSUE THREAD

**Issue by tonijarjour** [AcidWeb/CurseBreaker#300]
![1624288021](https://user-images.githubusercontent.com/39845673/122784970-eedc6480-d280-11eb-8e72-6daf58701e1c.jpg)
The user will have to run `chmod +x CurseBreaker-linux` to be able to run the program.

**Comment by AcidWeb** [comment]
Strange. I'm quite sure I packed it with executable rights. I will check it later.
