### ISSUE TITLE
Not all addons on Curse are being detected

### ISSUE THREAD

**Issue by Fraktyl** [AcidWeb/CurseBreaker#301]
Trying to install AzerPugs Tooltips: https://www.curseforge.com/wow/addons/azerpugs-tooltips.  Getting a addon not found.

In fact none of AzerPugs addons are found using CurseBreaker.  Not sure if it's a curse problem or a Cursebreaker problem.

**Comment by AcidWeb** [comment]
Author requested to blacklist his work.

**Comment by Fraktyl** [comment]
Wasn't aware of that.  Appreciate the response and the work you do on this.
