### ISSUE TITLE
Not updating Venture Plan from Townlong Yak

### ISSUE THREAD

**Issue by SerkTX** [AcidWeb/CurseBreaker#302]
The current version of the addon Venture Plan from Townlong Yak is 4.16a, but Curse Breaker isn't updating this addon past version 4.15a

https://www.townlong-yak.com/addons/venture-plan

Thank you for making and maintaining an excellent addon manager!

**Comment by AcidWeb** [comment]
Townlong-yak author disabled update API. So we are back to manually updating addons from there.

**Comment by AcidWeb** [comment]
It should be fixed now.

**Comment by SerkTX** [comment]
Thank you! Confirmed working again...
