### ISSUE TITLE
Addon not being detected

### ISSUE THREAD

**Issue by vaindil** [AcidWeb/CurseBreaker#303]
Hello! Thanks for this awesome tool, I use it daily.

I recently became a contributor for [Wowhead Quick Link](https://www.curseforge.com/wow/addons/wowhead-quick-link), we were having some issues with the CurseForge auto-packager so I uploaded a version manually (2.12.0). CurseBreaker is not detecting this new version, however, it throws the standard "Failed to find release for your client version" error. I looked at the response from the API endpoint that CurseBreaker uses, and the version is being returned, but it's the second one in the `latestFiles` array.

Is there an issue on CurseForge's end with this (either my fault or their fault) or is it an issue with CurseBreaker?

**Comment by AcidWeb** [comment]
That is normal when package is marked for more than one client version. All clients (including official one) are affected.
If you want to support more than one client version you need to make a separate release for every client.

**Comment by vaindil** [comment]
Ah that's annoying, okay. I'll make a separate release for each version then and reupload. Thank you, I appreciate it!

**Comment by AcidWeb** [comment]
Yeah. It is. This bug exist since Classic launch and was not fixed yet.

**Comment by vaindil** [comment]
Oh that looks awesome, I'll get that figured out. Thank you again!
