### ISSUE TITLE
RuntimeError: Failed to parse Wago data.

### ISSUE THREAD

**Issue by Matuc1337** [AcidWeb/CurseBreaker#304]
everything works except Wago. Is there a problem with the Wago.api?

**Comment by AcidWeb** [comment]
It is still crashing?

**Comment by Matuc1337** [comment]
it still says "RuntimeError: Failed to parse Wago data."

**Comment by AcidWeb** [comment]
Please upload yours `WeakAuras.lua` from WTF directory.

**Comment by Matuc1337** [comment]
https://www.sendspace.com/file/sufenb

**Comment by AcidWeb** [comment]
This is interesting. I took your database and it is working correctly:
![image](https://user-images.githubusercontent.com/3713734/124875914-ba2f1380-dfc9-11eb-8fc0-7429494daf20.png)

I presume that wago site is working correctly for you? Everything loads there?

**Comment by Matuc1337** [comment]
yes it does.

**Comment by Matuc1337** [comment]
i just noticed, that when i enter the help command, Wago.io isn't part of the supported URLs. Maybe that's the reason why i can't update my weakauras?

[https://ibb.co/vd71xwF](url)

**Comment by Matuc1337** [comment]
here is the picture from the link

![Wago error](https://user-images.githubusercontent.com/86882172/125116181-9d3f3100-e0ec-11eb-92d1-a0c68be8029c.jpg)

**Comment by AcidWeb** [comment]
I'm terribly sorry as I completely forgot to respond to this ticket. I presume it still don't work?

**Comment by Matuc1337** [comment]
Nope. It still don't work.

**Comment by AcidWeb** [comment]
Set `CURSEBREAKER_DEBUG` environment variable and error should display more information.

**Comment by Matuc1337** [comment]
where do i have to set the variable?

**Comment by Matuc1337** [comment]
???

**Comment by AcidWeb** [comment]
Open the windows terminal. Execute `set CURSEBREAKER_DEBUG=` and then start the Cursebreaker from that session.

**Comment by Matuc1337** [comment]
I just googled Windows Terminal and found out that it's a Windows 10 app. That is a problem since i still use Windows 8.1 . Any advice on how to start the Cursebreaker debug on Windows 8.1?

**Comment by AcidWeb** [comment]
Windows `cmd` is enought.

**Comment by Matuc1337** [comment]
I changed the directory in the CMD to my WoW folder, entered the Command you told me to execute and startet the Cursebreaker client via CMD but it still is the same Display as in the Image above
![CMD1](https://user-images.githubusercontent.com/86882172/126573416-70d9d3f7-f0ec-4d5e-8058-6ac482a8d6ec.jpg)
![CB Error](https://user-images.githubusercontent.com/86882172/126573419-d52eca2d-1a94-43d8-926a-275dccfa7c99.jpg)

**Comment by AcidWeb** [comment]
Just `CurseBreaker.exe` without `start`.

**Comment by Matuc1337** [comment]
No changes to the error message. exact like the ones in the pictures above

**Comment by AcidWeb** [comment]
OK. I don't have idea. Do you maybe have incorrect Wago API key added? What AV you use?

**Comment by Matuc1337** [comment]
I use Avast but that hasn't made any noise so far regarding Cursebreaker. I also added the Wago API Key from my Wagi.io profile.

**Comment by Matuc1337** [comment]
any ideas left?

**Comment by AcidWeb** [comment]
Not really. It must be something local considering I can use your WA file correctly. Maybe try to run CurseBreaker with admin rights?

**Comment by Matuc1337** [comment]
I tried it just now... still not working. Any ideas which setting i can check since Cursebreaker works perfectly fine except for Wago?

**Comment by AcidWeb** [comment]
Send me your entire `WTF` directory. Just not publicly -> pawelj@iosphe.re

**Comment by Matuc1337** [comment]
Just this moment i sended an email containing my WTF Folder to you

**Comment by AcidWeb** [comment]
OK. With full package I finally replicated the issue. Let me check what is wrong.

**Comment by AcidWeb** [comment]
Error is caused by incorrect WA API key. Execute `set wago_api` and check if it magically started to work.

**Comment by Matuc1337** [comment]
Thanks so much. It finally worked.

**Comment by AcidWeb** [comment]
Great. I will add better error messages about it.
