### ISSUE TITLE
WeakAuras not updating

### ISSUE THREAD

**Issue by carlschoeneich** [AcidWeb/CurseBreaker#305]
For quite some time now it seems like Cursebreaker isn't updating my weakauras anymore.
There are newer versions on wago.io but they aren't downloading.

**Comment by AcidWeb** [comment]
Show me output of `wago_update` command.

**Comment by carlschoeneich** [comment]
![image](https://user-images.githubusercontent.com/16469528/124754587-b39d8f00-df2a-11eb-841a-b7fd1948d7de.png)
It actually doesn nothing.

**Comment by AcidWeb** [comment]
That mean no auras are detected - at all. You maybe use multiple accounts and updater is set to wrong one?

**Comment by carlschoeneich** [comment]
Thank you very much!!
Didn't even know that was a thing ^^
