### ISSUE TITLE
[Suggestion] Update Github/Gitlab projects last.

### ISSUE THREAD

**Issue by SHJordan** [AcidWeb/CurseBreaker#307]
I don't know if you have noticed already, but when using the update command it hangs on the addons that are being downloaded from these websites. I have tested it with and without ElvUI:Dev Shadow&Light:Dev and the diffrence is noticeable...

Another solution would create a separe pipeline for other websites so it would occour in paralel.

**Comment by AcidWeb** [comment]
Update process is single threaded and I don't see and I doubt this will change in the near future.
