### ISSUE TITLE
Running in headless mode forcibly clears my terminal

### ISSUE THREAD

**Issue by fontivan** [AcidWeb/CurseBreaker#309]
When running in Headless mode, I find that my terminal output has been forcibly cleared. The stdout output from my script from before invoking CurseBreaker is all lost as a result. I was expecting that when running in headless mode that there would just be some details logged in stdout/stderr but instead all my previous output is gone.

In particular I am rolling this into my script to update both classic and retail addons, so I can only see in the output whichever update runs second. Instead I would expect to see the output from both CurseBreaker runs in sequence in my output.

**Comment by AcidWeb** [comment]
I will take look later.

**Comment by fontivan** [comment]
Works great in the fixed build (v3.18.2) thanks!
