### ISSUE TITLE
What are you retrieving from your storage API and how are you generating the file there?

### ISSUE THREAD

**Issue by NCC-Lykos** [AcidWeb/CurseBreaker#31]
`parse_cf_id`

What are you retrieving from your CDN? https://storage.googleapis.com/cursebreaker/cfid.pickle.gz

How are you generating this file? Curious, if this CDN ever goes away will the CB app no longer function?

**Comment by AcidWeb** [comment]
It is some backstage magic for features like command autocompletion.

Application will work without that data.
