### ISSUE TITLE
Update readme for exclamation marks

### ISSUE THREAD

**Issue by wlfbck** [AcidWeb/CurseBreaker#310]
Title pretty much ;) I have these exclamation marks next to the version (of some addons), but no idea what they mean and it's not in the readme:
![grafik](https://user-images.githubusercontent.com/1621804/131963888-9bbbf95d-3506-4511-9a27-5e9bc1c85ee8.png)

**Comment by biggianteye** [comment]
If you type `help`, you'll see this in the `status` section:

```
status
        Prints the current state of all installed addons.
        [!] mark means that the latest release is not updated yet for the current WoW version.
        Flags:
                -a - Temporary reverse the table compacting option.
                -s - Display the source of the addons.
```
