### ISSUE TITLE
v3.17.4 error: api-ms-win-core-path-l1-1-0.dll missing

### ISSUE THREAD

**Issue by thmsdrew** [AcidWeb/CurseBreaker#318]
I just updated to v3.17.4 and I now receive the error: "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."

Windows 7 64-bit

Unsure what other info about my system would be helpful.

![image](https://user-images.githubusercontent.com/822002/139776338-384b9065-f550-40ee-a236-efe0ecfd4c44.png)
![image](https://user-images.githubusercontent.com/822002/139776350-6e5784a5-4195-463e-8adb-03c90fff0c0a.png)

**Comment by AcidWeb** [comment]
Duplicate #317.

**Comment by thmsdrew** [comment]
Ah my bad. Thank you!
