### ISSUE TITLE
Win7 DLL

### ISSUE THREAD

**Issue by ecspaeth** [AcidWeb/CurseBreaker#319]
The last working release for me was September 16. Now that release opens, but updates and when it restarts, I receive the following error:

"api-ms-win-crt-runtime-l1-1-0.dll is missing from your computer"

I tried fixing/reinstalling a c redestributable to no avail. I also ensured that dll does exist on my machine still. Am I out of luck on win7?

**Comment by AcidWeb** [comment]
Yes. Duplicate #317.
