### ISSUE TITLE
WeakAura.py: install_companion uses back slashes instead of front slashes

### ISSUE THREAD

**Issue by NCC-Lykos** [AcidWeb/CurseBreaker#32]
In the path, install_companion uses back slashes instead of front slashes. There is no issue when running on Windows but running on another OS it causes folders and files to be created with back slashes in the name.

https://github.com/AcidWeb/CurseBreaker/blob/master/CB/WeakAura.py#L109

**Comment by AcidWeb** [comment]
That is `Path`. It should be handled automatically. I will check it out.

**Comment by AcidWeb** [comment]
I'm closing it as part of #26.
