### ISSUE TITLE
ElvUI:Dev install error

### ISSUE THREAD

**Issue by trying-to-function** [AcidWeb/CurseBreaker#320]
When trying to `install ElvUI:Dev` I'm getting the following error:

```
CB> install ElvUI:Dev
1/1 | ----------------------------------------------------------------------------------------- |
┌────────┬───────────────┬─────────┐
│ Status │ Name / Author │ Version │
├────────┼───────────────┼─────────┤
└────────┴───────────────┴─────────┘
PermissionError: [WinError 5] Access is denied: 'Interface\\AddOns\\ElvUI-development\\ElvUI' ->
'Interface\\AddOns\\ElvUI'

During handling of the above exception, another exception occurred:

PermissionError: [WinError 32] The process cannot access the file because it is being used by
another process: 'Interface\\AddOns\\ElvUI-development\\ElvUI\\Core\\Media\\Arrows'
CB>
```

`install ElvUI` (non dev version) works as expected.

Dev channel was working three or four days ago, unsure what has changed.

I've tried manually removing the directories and rebooting, any other troubleshooting steps recommended?

**Comment by AcidWeb** [comment]
It looks like something is placing a lock on unpacked dev version of ElvUI before it ws moved to correct locarion.. Try running CB as admin.

**Comment by trying-to-function** [comment]
I suspect I know what is going on. I'm guessing CurseBreaker is downloading the git repository to `Interface\\AddOns\\ElvUI-development` then moving the necessary files from there to `Interface\\AddOns` then deleting the `ElvUI-development` directory?

I have my `Interface\\AddOns` directory stored inside dropbox so I'm able to move between computers easier and I suspect Dropbox sync is putting a temporary hold on the temporary files. My OSX computer doesn't have an issue with this- but Windows does. Is it possible to move the unpacking to the operating systems temporary folder instead of inside `Interface\\AddOns`?

**Comment by AcidWeb** [comment]
That sound as possible cause of the problem. I have some ideas how to handle it better. I would suggest tell dropbox to ignore `ElvUI-development` for now as temporary workaround.

**Comment by trying-to-function** [comment]
> I would suggest tell dropbox to ignore ElvUI-development for now as temporary workaround.

It is a bit tricky to get dropbox to ignore folders- but I should be able to using symlinks.

Thanks for looking into this, appreciate it!
