### ISSUE TITLE
Force install.

### ISSUE THREAD

**Issue by iamonefm** [AcidWeb/CurseBreaker#321]
Hi, MerathilisUI project (ElvUI plugins) Streamline Retail, Classic, TBC (all in one), of course now when checking the client type CurseBreaker warns about RuntimeError Client version. (Https://www.tukui.org/addons.php?id=1), is it possible (may be) to make a new force install parameter without checking the client type.

**Comment by AcidWeb** [comment]
I will take a look.

**Comment by Merathilis** [comment]
oh gosh... i break the client? muhahaha xD

**Comment by iamonefm** [comment]
> Due to upcoming CurseForge API changes this project will be discontinued in the first quarter of 2022. So Long, and Thanks for All the Fish.

**Comment by iamonefm** [comment]
> Q: Due to upcoming CurseForge API changes this project will be discontinued in the first quarter of 2022. So Long, and Thanks for All the Fish.  

**F**
Great client! Especially over ssh. :(

**Comment by AcidWeb** [comment]
I'm still planning to fix it.

**Comment by AcidWeb** [comment]
Fixing it correctly would require more work I expected. So considering this project is discontinued I'm closing this ticket.
