### ISSUE TITLE
Flagged as Trojan

### ISSUE THREAD

**Issue by Rollyjoger85** [AcidWeb/CurseBreaker#322]
Hi,

Today out of the blue Bitdefender flagged the application as a trojan.

![image](https://user-images.githubusercontent.com/40987871/141523793-f35805bd-cc27-4493-be6a-003b066c89b9.png)

I've used it without issues for so long now, never had any issues, not sure what has changed.
I'm on the newest version (3.19)

**Comment by AcidWeb** [comment]
False positive. Sometimes binaries made by PyInstaller are tagged by AV as malware in Python also use PyInstaller.

**Comment by AcidWeb** [comment]
I send report about it to BitDefender.

**Comment by AcidWeb** [comment]
It looks like they cleaned it up.
