### ISSUE TITLE
Bitdefender Quarantine

### ISSUE THREAD

**Issue by Ghostrider4321** [AcidWeb/CurseBreaker#323]
Bitdefender is now detecting the latest version of cursebreaker.exe as Trojan.GenericKDZ.80024.  

I have used CurseBreaker for over a year and this is the first time bitdefender blocked it.  I most recently used cursebreaker last night with no issues.  The detection was made this morning during my daily scan before I launched it.  Also, bitdefender blocks the download for the same reason.  

I suspect this to be a false positive as I have been running the latest version since its release, but I am running a full system scan to be safe.   I wanted to let you know of the detection so you can check things out on your side.

**Comment by AcidWeb** [comment]
Duplicate #322
