### ISSUE TITLE
This project will NOT be discontinued

### ISSUE THREAD

**Issue by AcidWeb** [AcidWeb/CurseBreaker#325]
Due to upcoming CurseForge API [changes](https://mailchi.mp/overwolf/whats-new-with-overwolf-curseforge-november3) I plan to discontinue this project as I don't believe it can fulfill its purpose anymore.

**Two main reasons:**

1. Entire point of this application is to aggregate multiple sources in one client. Without access to the full CF catalog, the vast number of addons will no longer be available.
2. If downloads made by third-party solutions don't generate Rewards Points anymore I can no longer with clear conscious recommend using a third-party updater.

**So what now?**

CurseBreaker will be maintained until the old API is still working. Expect breakage in the first quarter of 2022.
This is a part where I should recommend using other third-party updaters (like WoWUP, Instawow or Ajour) but I strongly believe they will have the same problem as me so... Maybe it is time just to stop using CurseForge altogether.

_So Long, and Thanks for All the Fish._

**EDIT:**
I'm pulling this project out of the freezer. Expect 4.0.0 release in the first week of June.

**Comment by Jed-Giblin** [comment]
Thanks for all your great work, I've used this project since the overworlf acquisition happened. 

I'll be forking and looking to highlight any/all donate links found in any addons that CF developers leave as accessible to 3rd party applications.

**Comment by icbat** [comment]
Thanks for all your hard work!

Honestly, CurseBreaker is still really handy for installing and updating not-CF addons. The GitHub and WoWI integrations are enough to keep me using it as long as I can :)

**Comment by JeremyMorton** [comment]
I would like to able to keep updating addons from non-CurseForge sites, especially from GitHub.

Towards the point: "Maybe it is time just to stop using CurseForge altogether", I think it is much easier to do that if there are addon updaters that work with alternate sites, like wowi, github, Townlong Yak, tukui, etc.

It's a lot harder to have CurseForge alternatives if there are no updating programs for those alternatives.

**Comment by DemonfangArun** [comment]
Thanks for all your hard work, it was nice to have everything in one place behind something that isn't bloated to no end. I guess I will retire back to letting CF handle things and hoping it doesn't screw everything up.

**Comment by srbrunner** [comment]
This is sad news, but couldn't have asked for a better addon.  Thanks for all the hard work and disappointed curse has made these decisions.  maybe it is time to start using wag.io https://addons.wago.io/ or github with donations.

**Comment by caffeineaddiction** [comment]
@AcidWeb your saying your not supporting the project because you cant make money from it anymore?  How much money where you making via curse, and is it possible to obtain that same amount through https://www.buymeacoffee.com/ or https://www.patreon.com/ ?

**Comment by AcidWeb** [comment]
What? Where I'm saying that. Don't be ridiculous.

**Comment by Xnatee** [comment]
Well, it feels bad to read that because it was such a nice tool :)
I thought you were going to keep going without curseforge since wago/github should support most addons (and developpers providing addons by that way understand what it means).
I hope the situation will change before end of CFs API !
Thanks for all

**Comment by caffeineaddiction** [comment]
> What? Where I'm saying that. Don't be ridiculous.

Ok, maybe I missread 2). then

> If downloads made by third-party solutions don't generate Rewards Points anymore I can no longer with clear conscious recommend using a third-party updater.

If your not worried about Reward Points ... then why is that an issue?

**Comment by AcidWeb** [comment]
Curse/overwolf is stealing? Are you delusional? Please go away.

**Comment by krazyito65** [comment]
> @AcidWeb your saying your not supporting the project because you cant make money from it anymore? How much money where you making via curse, and is it possible to obtain that same amount through [buymeacoffee.com](https://www.buymeacoffee.com/) or [patreon.com](https://www.patreon.com/) ?
> 
> I mean, lets be real ... no one here is going to start using overwolf.

To help clear this question.....  3rd party tool do NOT make any money from OW/CF at all.  They never have.  

> If downloads made by third-party solutions don't generate Rewards Points anymore I can no longer with clear conscious recommend using a third-party updater.

This part is referring to the actual addon authors.  He is saying that he cannot morally continue with this project, knowing that he is essentially denying any revenue to those addon developers because of his application.  This has nothing to do with his own financial motivations.

**Comment by mspykerez** [comment]
As I understand curseforge will give the addon developers the option to make their addons accessible through 3rd parties like CurseBreaker or not. So why not continue CurseBreaker to serve those addons that would still be accessible?
Even if they choose to lock the API can't CurseBreaker just display a message informing so or provide a link to the curseforge site, IMO it would still be useful information.

I'm inclined to believe that only a bunch of popular addons would benefit from having the API locked and the vast majority would not care or will think that it isn't worthwhile the extra few bucks hence choosing to keep the API open.

Also curseforge is not the only player around, there are other sites where developers upload which include stuff that curseforge does not have.

**Comment by ChrisKader** [comment]
> To help clear this qu



> @AcidWeb your saying your not supporting the project because you cant make money from it anymore? How much money where you making via curse, and is it possible to obtain that same amount through https://www.buymeacoffee.com/ or https://www.patreon.com/ ?
> 
> I mean, lets be real ... no one here is going to start using overwolf.

The request form CF has up for requesting a third party API key has the following question
> Are you looking to monetize the project? (Ads, subs, donations or any other method)
This would indicate that developer of third party addon managers are not allowed to request or receive donations.

@AcidWeb if you are open to allowing someone else to maintain this project to support the new API, I would be more than happy to do so.

As far as the impact it would have on addon developers: They have the choice to turn off access to third party addon managers. Since the choice is in the hands of the addon developer, I do not feel that any third party addon manager would be directly (or indirectly) hindering the ability for an addon developer to generate revenue.

**Comment by kennywasafk** [comment]
I just wanted to join in and say thank you for developing and maintaining Cursebreaker. After the aquisition I started looking into 3rd party addon managers and this is the only one that _does it all_ with no hick-ups whether you're managing 10 or 200 addons. I'm incredibly sad to see it go, got very used to not thinking about managing addons from different sources with different software. It's unlikely to happen but I do hope people stop using curseforge, or at least use multiple platforms for hosting their addons.

**Comment by Bloodmallet** [comment]
As others mentioned above, is there a chance to continue the project to keep non-cf addons up to date? I love cli and your tool is great!

**Comment by AcidWeb** [comment]
It should still work in the foreseeable future without any interruption.

**Comment by lixicus** [comment]
Still why just depend on CurseForge when whe have Wowinterface that is just as good if not better ?

**Comment by brucek2** [comment]
Thanks for this amazing project. If you're done, you're done, but I'd just like to note that I think it will still be very valuable without any curseforge support. Many popular addons are already available from non-curse sources (i.e., increasingly, GitHub, which I think is great), and when the API change comes, the existence of good tools like yours may be a key point in helping encourage authors who haven't already, to list on one of the alternate sources as well.

**Comment by Barleduq** [comment]
I'd like to ask others who use this which other one they would recommend, but I don't want to keep pinging this author with other questions.  Is there a forum or somewhere to go look?  I was mainly interested in this one because it does NOT involve a UI to do things, and so far the others I've looked at do. Wondering if I'm missing something.

**Comment by cybern4ut** [comment]
I've been a fan of your project for a while, I recently swap my source  to WOWI but my question is since wago addons offers monetization, couldn't we integrate that into cursebreaker to make it viable as a different source from CF with a reward program.

**Comment by fspy** [comment]
RIP, it's finally dead.

**Comment by FoxBJK** [comment]
Getting numerous connection errors when I try to run CurseBreaker that I've never seen before. I think the day has finally come, the API access is gone.

**Comment by AcidWeb** [comment]
Nope. CF API just had a stroke.

**Comment by AcidWeb** [comment]
May 9 - Old CF API will be discontinued.
So CF support in CurseBreaker will break completely. Rest of sources will still work.

**Comment by ChrisKader** [comment]
Glad I updated my local version to use the new API and got a key.

**Comment by AcidWeb** [comment]
That will not help much as tons of popular addons will not be available over new API.

**Comment by mykkenny** [comment]
So we're basically stuck using CF and/or their client?

**Comment by AcidWeb** [comment]
It looks like I will have good news in upcoming weeks. Stay tuned.

**Comment by ChrisKader** [comment]
Now I'm excited.

**Comment by cybern4ut** [comment]
> It looks like I will have good news in upcoming weeks. Stay tuned.

I can’t wait man, there is nothing like cursebreaker!

**Comment by Thompsonize** [comment]
Thank you for keeping this going and us updated. This tool is hugely valuable.

**Comment by abelito75** [comment]
With a new curseforge API which is [here](https://docs.curseforge.com/?python#get-mod) will the project regain support?

**Comment by ArabCoders** [comment]
> It looks like I will have good news in upcoming weeks. Stay tuned.

Hopefully it will leads to cursebreaker working again. Right now i am using windows sandbox to install their client to update addons.

**Comment by Xionyus** [comment]
I have swapped over to Wowup for the time being but I would be so incredibly happy if you still worked on this and got it to work with the overwolf overhaul. I love Cursebreaker so much and recommend it to everyone I play WoW with! Take your time and thank you so much for all of your hard work!

**Comment by Barleduq** [comment]
I couldn't be arsed to get wowup working on linux.  I just heard that curseforge made a linux client, but I'd really rather use wowinterface.com regardless.  I hope the good news is continuation!

**Comment by nezorflame** [comment]
It's literally an Electron wrapper for their client. It can run wherever Chrome runs, it's just that they didn't want to launch it anywhere else (yet).

**Comment by jamby** [comment]
Here's hoping we can get that good news soon!

**Comment by btnmasher** [comment]
I absolutely refuse to install Overwolf spyware on my machine, and updating addons manually by hand in the meantime is brutal, I really hope to hear some good news soon! Thank you so much for this project!

**Comment by AcidWeb** [comment]
Expect 4.0.0 release in the first week of June.

**Comment by mykkenny** [comment]
> Expect 4.0.0 release in the first week of June.

So everything will be working again? Any changes?

**Comment by AcidWeb** [comment]
No. Yes. The current market situation is forcing small... reshuffle. But I think I have come up with a solution that will satisfy all parties.
I will share details closer to launch.

**Comment by AWalterJackson** [comment]
> Legal. I strongly believe that the current TOS of the API is anti-consumer and incompatible with open source projects. It feels like it was designed to suppress them. That is why nobody else from the WoW ecosystem other than WoWUP even bothered to apply for it. If feedback would be not ignored we could easily construct something that would be usable and satisfy all parties. But OW has knowingly chosen to deploy its current form.

I think you're entirely on the money with this one. Honestly, I believe that in buying Curseforge, OW saw what they thought was a captive market that they'd be able to tap into for marketing/tracking data to sell to 3rd parties, and that their goal at the moment is to actively stifle any third party manager projects as these represent a risk to that business model.

It does appear however that they failed to realise that when you're dealing with an entire community based around software development, you're literally working with the same people who will just make their own competitor from scratch if you upset them too much The recent rapid growth of WoWUp, alongside other repository sites like Wago and WoWI are evidence of that, as well as the increasing number of addons offering github releases.

I wholly expect this trend to expand into the Minecraft community as well who are just now finding their own launchers affected by this same decision.

**Comment by stabbthehuman** [comment]
Very happy to see this will NOT be discontinued! Appreciate the work you've done and can't wait to see what you do next.

**Comment by eixwow** [comment]
Any news when you will be finished?

**Comment by AcidWeb** [comment]
I still need to put some finishing touches. I hope it will be ready to release soon.

**Comment by Barleduq** [comment]
Add a +1 to eagerly awaiting the new version. I've entirely too many addons only available on curseforge, that I'm sure are getting updated and since using this I just Can't Be Bothered to go and download individual ones. I'm *so* glad there's something that is not trying to interface with the UI that has a native linux distro and Just Works.

**Comment by cmacrowther** [comment]
Stoked to hear you're deciding to continue on with this project - it's been a godsend 🤘

**Comment by jamby** [comment]
Any word on an update for this? My addons desperately need an update.

**Comment by AcidWeb** [comment]
Version 4.0.0 has been ready for some time. Still waiting for some... external factors.

**Comment by nezorflame** [comment]
Guys, give the author some space. It'll be done when it's done.

**Comment by AcidWeb** [comment]
OK. I will be releasing CurseBreaker 4.0.0 with beta Wago Addons support today.

I think we have achieved the scenario closest to the ideal - Personal API keys.
Platform get the money, authors get the money, users don't need to see any ads and they can choose tool they want to use.

**Comment by FoxBJK** [comment]
This only works if Overwolf is willing to give you an API key, right? What happens when a bunch of end users start applying for a key to use this app? Has anyone from Overwolf said this is gonna be allowed, or are we all just hoping they'll be cool?

[Application link](https://forms.monday.com/forms/dce5ccb7afda9a1c21dab1a1aa1d84eb?r=use1), for the lazy

**Comment by nezorflame** [comment]
@FoxBJK he's talking about the Wago Addons's API key, not the OverWolf ones.

**Comment by AcidWeb** [comment]
This application no longer support Curseforge at all. I'm talking about Wago Addons API key.

**Comment by AcidWeb** [comment]
If you want to use Wago Addons as addon source - yes.

**Comment by leginnos1en** [comment]
This project should be discontinued because its nothing but a scam front for wag.io addon patron subscription money now
