### ISSUE TITLE
Add a way to set a GitHub token to avoid rate limiting

### ISSUE THREAD

**Issue by JeremyMorton** [AcidWeb/CurseBreaker#326]
As I switch more addon sources from CF to GitHub, I sometimes hit the symptoms of GH restricting anonymous API calls ("RuntimeError: Failed to parse addon data: string indices must be integers"), and I would like to provide my own token to be used for GH API calls, similar to the `set wago_api` command.

**Comment by AcidWeb** [comment]
It makes sense.
