### ISSUE TITLE
CurseBreaker 3.0.0 feedback & request

### ISSUE THREAD

**Issue by NCC-Lykos** [AcidWeb/CurseBreaker#33]
First, fantastic! I see what you meant now and that is how I should have approached the multi-platform code.

Everything appears to function well on macOS.

One thing, when I pull a `status` ....I'd like to know the origin of the addon if possible? Either cf wowi tu or tuc. I have Shadow & Light and BenikUI and others that I installed from tu: and I'd like to verify that that is still the source they are coming from.

Thanks!

**Comment by AcidWeb** [comment]
Use `export` command to see sources.
