### ISSUE TITLE
Unable to add addon via GitHub

### ISSUE THREAD

**Issue by nezorflame** [AcidWeb/CurseBreaker#331]
Hi! Thanks for the 4.0.0 update.
I'm trying to add some of the missing addons via their Github repos (e.g. [Wowhead Quick Link](https://github.com/NielsHeltner/wowhead-quick-link/releases), [Angrier World Quests](https://github.com/GurliGebis/AngrierWorldQuests/releases), [Better Wardrobe and Transmog](https://github.com/SLOKnightfall/BetterWardrobe/releases) and a few others), but I'm always getting the same error.

E.g.:

```
CB> install gh:NielsHeltner/wowhead-quick-link
1/1 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ |
┌────────┬───────────────┬─────────┐
│ Status │ Name / Author │ Version │
├────────┼───────────────┼─────────┤
└────────┴───────────────┴─────────┘
RuntimeError: Failed to parse addon data: string indices must be integers
```

Any idea what goes wrong? The error message is always the same.
Does CurseBreaker only accept a specific type of release scheme?

**Comment by AcidWeb** [comment]
First two should work. And they are working for me:
<img width="766" alt="image" src="https://user-images.githubusercontent.com/3713734/177322400-213d54ef-e7ca-45fd-b5e9-06825de9381c.png">
Third will not work due to lack of proper packaged release.

Error means that something is failing during parsing of GitHub API. You know how to set a environmental variable called `CURSEBREAKER_DEBUG`? If yes please show entire error.

**Comment by nezorflame** [comment]
```
CB> install gh:NielsHeltner/wowhead-quick-link
1/1 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ |
┌────────┬───────────────┬─────────┐
│ Status │ Name / Author │ Version │
├────────┼───────────────┼─────────┤
└────────┴───────────────┴─────────┘
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ C:\Program Files (x86)\World of Warcraft\_retail_\CurseBreaker.py:444 in c_install               │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\World of                          │
│ Warcraft\\_retail_\\CurseBreaker.py'                                                             │
│                                                                                                  │
│ C:\Program Files (x86)\World of Warcraft\_retail_\CB\Core.py:294 in add_addon                    │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\World of                          │
│ Warcraft\\_retail_\\CB\\Core.py'                                                                 │
│                                                                                                  │
│ C:\Program Files (x86)\World of Warcraft\_retail_\CB\Core.py:211 in parse_url                    │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\World of                          │
│ Warcraft\\_retail_\\CB\\Core.py'                                                                 │
│                                                                                                  │
│ C:\Program Files (x86)\World of Warcraft\_retail_\CB\__init__.py:29 in inner                     │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'C:\\Program Files (x86)\\World of                          │
│ Warcraft\\_retail_\\CB\\__init__.py'                                                             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Failed to parse addon data: string indices must be integers
```

**Comment by AcidWeb** [comment]
Well it looks like debug is broken in binary release :D I will take a look on this too.

If you have GH Personal Token added - delete it. If not - add it. Maybe it is failing to detect rate limiting correctly.

**Comment by nezorflame** [comment]
Yup, deleting the key worked. Interesting...

**Comment by AcidWeb** [comment]
Yeah. If you want to debug it deeper I would set api key header manually and check output of `https://api.github.com/repos/NielsHeltner/wowhead-quick-link/releases`

**Comment by nezorflame** [comment]
I've found my issue, lol - my Github key expired in June :D created a new one and that fixed my issue.
Thanks for the help!

**Comment by Barleduq** [comment]
Sorry to comment on this after it's closed, but I'm a bit confused. As far as I know, I don't have a token for GitHub. Is this something automatic that I wouldn't know about?

**Comment by AcidWeb** [comment]
GitHub API is free and public but heavily rate limited. If somebody use GH as source for many addons it might start to return errors. In this case user need to provide a personal token that can be generated for free: https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/creating-a-personal-access-token
