### ISSUE TITLE
CaerdonWardrobe seems to have a release on github, but cursebreaker won't install it

### ISSUE THREAD

**Issue by Barleduq** [AcidWeb/CurseBreaker#336]
https://github.com/Caerdon/CaerdonWardrobe

has files in release, but when I 
install gh:caerdon/caerdonwardrobe

I get 
RuntimeError: Failed to parse addon data: 
https://github.com/caerdon/caerdonwardrobe
This integration supports only the projects that provide packaged releases.

**Comment by AcidWeb** [comment]
This type of releases is not enough. Release need to contain addon package created manually or by https://github.com/BigWigsMods/packager.
