### ISSUE TITLE
RuntimeError: Wago Addons API key is missing or incorrect.

### ISSUE THREAD

**Issue by Dranni21312** [AcidWeb/CurseBreaker#337]
First of all, thank you for your hard work and continued maintenance of the project!

After updating CurseForge to v4.0.1 and setting my wago addon API key, searching for any addons results in the following error message:

CB> set wago_addons_api XXXXXXXXXXXXXXXXXXXXXXX (an actual API key generated @ wago addons pasted in here)
Wago Addons API key is now set.
CB> search bagnon
RuntimeError: Wago Addons API key is missing or incorrect.
CB> search DBM
RuntimeError: Wago Addons API key is missing or incorrect.
CB>

Any ideas about what might be wrong and how to fix this? I have double-checked that the pasted value is correct.

**Comment by AcidWeb** [comment]
Are you sure you getting your key from https://addons.wago.io/patreon and not developer portal?

**Comment by Dranni21312** [comment]
I navigate to https://addons.wago.io/patreon, then click my account name in the top right corner, click Account Settings, then API Keys, and that's where I generate an API key. Is that not the correct place for it?

**Comment by Dranni21312** [comment]
![2022-07-07 06_22_39-Window](https://user-images.githubusercontent.com/80227585/177762211-748dda54-251b-4a88-80f3-406fa32c93a5.png)

**Comment by AcidWeb** [comment]
No. This part of page need to be used: 
<img width="391" alt="image" src="https://user-images.githubusercontent.com/3713734/177762415-c0b8f3c4-cf86-4952-8757-1cfd3167fc87.png">
