### ISSUE TITLE
Question: Files marked Modified that I haven't touched

### ISSUE THREAD

**Issue by Barleduq** [AcidWeb/CurseBreaker#339]
I know that if I edit a file in an addon, it gets marked modified. I believe that it also doesn't get updated anymore, at that point?  What else would cause a file to get marked Modified.  Right now, the base DBM addon is marked as Modified, and I haven't touched anything in there. Having that not be updated could be Bad (tm).

**Comment by AcidWeb** [comment]
Well something touched it. Between time of installation and now something edited or added some files there.

When modified addon have available update separate status will appear.

**Comment by Kruhlmann** [comment]
> I know that if I edit a file in an addon, it gets marked modified. I believe that it also doesn't get updated anymore, at that point? What else would cause a file to get marked Modified. Right now, the base DBM addon is marked as Modified, and I haven't touched anything in there. Having that not be updated could be Bad (tm).

You could run a diff on the version you have installed and a fresh copy of that version to see any modifications.
