### ISSUE TITLE
Failed to execute bulk version check

### ISSUE THREAD

**Issue by vehystrix** [AcidWeb/CurseBreaker#34]
Since I updated to version 3.0.1, I get the following error whenever I try to update my addons:

![image](https://user-images.githubusercontent.com/7142781/67228073-d925f480-f438-11e9-9e9a-3d4c00600af3.png)

**Comment by AcidWeb** [comment]
Send me yours `CurseBreaker.json` from `WTF` directory.

**Comment by vehystrix** [comment]
[CurseBreaker.json.txt](https://github.com/AcidWeb/CurseBreaker/files/3752266/CurseBreaker.json.txt)

**Comment by AcidWeb** [comment]
Got it - I will check it soon.

**Comment by AcidWeb** [comment]
Problem is caused by "Luna Unit Frames". Project was removed from CurseForge as author is a thief.
`uninstall Luna Unit Frames` and it should start to work correctly.

I leaving this bug open as I need to improve error reporting.
