### ISSUE TITLE
Request: Allow private GitHub repos as addon source

### ISSUE THREAD

**Issue by LukasDahl** [AcidWeb/CurseBreaker#345]
First of all, thanks for an awesome addon manager.

I was wondering if it would be possible to allow a private GitHub repo as a source.
This would allow distribution of addons privately to guildies/friends without making a public repo.
As far as I can tell it just requires the already provided GitHub token to be passed along with every get request.

Right now attempting to install from a private repo gives the error:
`RuntimeError: Failed to parse addon data: Expecting value: line 1 column 1 (char 0)`

**Comment by AcidWeb** [comment]
I will take a look.

**Comment by AcidWeb** [comment]
This code will allow to support private repos as long provided personal token give access to them.
