### ISSUE TITLE
Installing from GitHub without metadata can fail with "raw" content-type

### ISSUE THREAD

**Issue by ruscur** [AcidWeb/CurseBreaker#347]
Installing from https://github.com/FabysGames/mythicplustimer/releases/tag/4.8.2 fails because the content type of the asset is `raw` instead of what is expected for a `.zip` file.  This looks to me like something wonky on the GitHub side but I'm not entirely sure.

If installing from GitHub repos that don't provide a `release.json` file is something CurseBreaker wants to support (wasn't entirely sure from flicking through old issues), then the solution should just be accepting a `raw` content type for an asset ending in `.zip`.  In the above case, accepting a `raw` content type does enable the install to work as expected.

**Comment by AcidWeb** [comment]
I will take a look.
