### ISSUE TITLE
Help, not an issue

### ISSUE THREAD

**Issue by Barleduq** [AcidWeb/CurseBreaker#349]
I wasn't able to find a place to ask - or get an answer from other places that I thought CurseBreaker users would be (various wow-related discords). 

In anticipation of having a large pile of new addon versions, I moved the contents of my AddOns directory, of the WTF directory, and moved the WTF backup directory elsewhere. Cursebreaker has now lost my list of addons. Is this still available somewhere, and how can I recover it?  I'd really rather not reinstall all my addons. 

And is there somewhere better to ask questions like this, that aren't issues/bugs but help in making it work? 
-Barleduq

**Comment by AcidWeb** [comment]
There is `CurseBreaker.json` in WTF directory. Restore it and you will get your configuration back.

I invite you to my discord server: https://discord.gg/G2SXFGb

**Comment by Barleduq** [comment]
Thank you!
