### ISSUE TITLE
3.0.1 strange addons mix

### ISSUE THREAD

**Issue by boohyaka** [AcidWeb/CurseBreaker#35]
Hi, recently I've had a strange issue with two addons getting mixed. The two addons were:

https://www.curseforge.com/wow/addons/clique
https://www.curseforge.com/wow/addons/all-the-things

Looking at the JSON, the entry for Clique had the Addon URL of all the things, and in total I had 4 separate entries for All the Things. When I ran CurseBreaker, I had 3 lines "removed" (I think?) for All The Things in the "Status" column. Closing and reopening CurseBreaker, the same happened every time.

I have deleted both addons, removed all entries for them in the json, and reinstalled the addons properly. Now it's looking okay, except this error in the bottom:

![image](https://user-images.githubusercontent.com/31538990/67262198-2f7c4d00-f4a4-11e9-97d0-c31536a71415.png)

I realize it would have been more useful to you if I had made a copy of the json file and screenshots of the problems before trying to fix them.. sorry.

**Comment by AcidWeb** [comment]
Yeah. `CurseBreaker.json` was most important part. I will try to replicate this issue.

Send me yours `CurseBreaker.json` because it is still broken.

**Comment by boohyaka** [comment]
Yes, sorry, not the smartest on my part. I've send the json by email, thank you for the quick help!

**Comment by AcidWeb** [comment]
Your current error is displayed because addon called "MonkeyQuest Classic (DaMaGepy edition)" don't exist anymore. Delete it and error will disappear.

There is no compatibility issues with that two addons you linking.

**Comment by AcidWeb** [comment]
I will improve error reporting so it will display more meaningful error message next time.

**Comment by boohyaka** [comment]
OK fixed, thank you. It's too bad I did not document the initial situation because it's definitely some bug that happened...I never modified anything by hand in the JSON, I used the software as expected and did nothing to create the issue that happened all of a sudden. 

Again thanks for the great software and quick help :)

**Comment by boohyaka** [comment]
Hey AcidWeb, I believe I managed to find the source of the problem, reproducing it by accident. I noticed Gathermate2 had disappeared form my addon list, so I went to install it again and here's what happened:

![image](https://user-images.githubusercontent.com/31538990/67319013-a0efe600-f50c-11e9-85a6-dddc056440a0.png)

![image](https://user-images.githubusercontent.com/31538990/67319071-b7963d00-f50c-11e9-8fd2-4a97d2080c50.png)

Gathermate2 folder was definitely not created in my Interface folder, addon is missing.
In the JSON I find this:

![image](https://user-images.githubusercontent.com/31538990/67319162-dac0ec80-f50c-11e9-9883-f3d2406f50a3.png)

The checksum is the same as the regular Clique entry, but I'm not sure that is something that CurseBreaker creates or if it comes from Curse website? Anyway if I manually download the Gatherer2 addon from Curse, the package is correct.

Hope this helps figuring it out! Let me know if I can help further.

**Comment by AcidWeb** [comment]
For now I'm not sure how that is possible but I will investigate.

**Comment by AcidWeb** [comment]
Send me yours `CurseBreaker.json`

**Comment by boohyaka** [comment]
Sent by email

**Comment by AcidWeb** [comment]
Well I think I found a bug that possibly might cause anomaly that caused your issue.

For now: `uninstall Clique` twice and `install cf:clique,cf:gathermate2`

**Comment by boohyaka** [comment]
I couldn't uninstall Clique twice, I did it once and both were removed. I then installed with your command and it looks ok so far. Thanks and hope you find the bug :)
