### ISSUE TITLE
Filter out UNSUPPORTED addons

### ISSUE THREAD

**Issue by Dranni21312** [AcidWeb/CurseBreaker#352]
Currently, the addon view is flooded with UNSUPPORTED addons. It would be nice to have a toggle that hides all the unsupported addons from the view.

**Comment by AcidWeb** [comment]
Persistent nature of this state is by design. User should `uninstall` these addons and `install` them from compatible source. Or remove it from CurseBreaker without removing the addon files: ``uninstall -k`.
