### ISSUE TITLE
Duplicate entries in compacting mode

### ISSUE THREAD

**Issue by KarlitosVII** [AcidWeb/CurseBreaker#353]
Hello,
Compacting mode seems to be bugged and duplicates entries.

Without sources :
![Sans titre](https://user-images.githubusercontent.com/7722685/202279932-58e876e8-5071-41dd-aa1e-fd6b9bc22270.png)

With sources :
![Sans titre 2](https://user-images.githubusercontent.com/7722685/202280018-3774a69c-a4c6-46a5-987d-7fceccfd9bd8.png)

Cheers.

**Comment by AcidWeb** [comment]
Oh boy. Something here is much more broken than compact mode.
Can you join my Discord and share yours `CurseBreaker.json` **in private message?**

**Comment by KarlitosVII** [comment]
Yeah sure but which Discord ? I can't see any link on this repo or in you profile.

**Comment by AcidWeb** [comment]
https://discord.gg/G2SXFGb
