### ISSUE TITLE
Scam project?

### ISSUE THREAD

**Issue by leginnos1en** [AcidWeb/CurseBreaker#354]
Apparently this can't be used without "donating" money to wag.io? And the instructions make no mention of this it just says "yeah go here," so yeah. Maybe be a little more upfront with your greed instead of dropping it on people who wanted to use an addon updater they used to use before it was taken over by grubby wag.io connected leech

**Comment by AcidWeb** [comment]
This claim is so ridiculous I don't even know why I bother to respond. This application support multiple addon sources and using Wago is far from mandatory. I don't control how providers provide access to their resources.

Please go away and don't embarrass yourself more with these type of statements.
