### ISSUE TITLE
Allow us to toggle sources

### ISSUE THREAD

**Issue by benftwc** [AcidWeb/CurseBreaker#358]
# Issue 

Hello Acid,

I used to manage addons with Cursebreaker, first of all, a big THANK for your work !

But recently, I have to reinstall whole game projects, and when I type "import install", it raise for some reasons ["features require wago api key"](https://github.com/AcidWeb/CurseBreaker/blob/a32688b735c0570599e2ec0a4f012fed768a8b2d/CB/Core.py#L502-L504), and, I guess someone ran into the same issue previously (https://github.com/AcidWeb/CurseBreaker/issues/354).

As I already used this software, I'm pretty sure it's not a scam, but for newcomers, I understand it can be "weird".

Regarding code, I would say https://github.com/AcidWeb/CurseBreaker/blob/a32688b735c0570599e2ec0a4f012fed768a8b2d/CB/Core.py#L611-L614 is involved in this issue

# Reproduce steps

- Install some addons with any methods, cursebreaker, curseforge, zip exctract ...
- Ensure you got fresh new installation (using latest version (v4.3.4) and remove `GAMEFOLDER/WTF/CurseBreaker.json`
- As mentioned by CLI, type `import install`
- It should scan folders to get addons name then, regarding to code, download latest versions and include managed addons through newly created CurseBreaker.json
Instead, it ask for Wago_Addon API key to scan their website.

![image](https://user-images.githubusercontent.com/1745200/209498124-55d9217d-d68c-4eba-98e2-ee6ffea2a6ec.png)

# Fix ?

- I would suggest to continue code execution without Wago Addons if API key isn't set 
OR
- Let us decide what sources to use/enable

**Comment by AcidWeb** [comment]
I just need to improve that error message as import is using only wago as the source. As it was using only CF before.
