### ISSUE TITLE
RuntimeError: This feature requires the Wago Addons API key.

### ISSUE THREAD

**Issue by AHrubik** [AcidWeb/CurseBreaker#359]
As of this morning my client seems unable to read my addons that were installed from WoW Interface and is insisting that I enable the Wago Addons API to use the client.

Is this an intended change?

Version: CurseBreaker 4.3.4

**Comment by AcidWeb** [comment]
There was no change. Please show me output of `status` command.

**Comment by AHrubik** [comment]
Here is what I see.

Command Shell Screenshot
https://i.imgur.com/Jiw5XkR.jpg

Addons folder showing addons present
https://i.imgur.com/ZT12Quj.jpg

**Comment by AcidWeb** [comment]
Ah. You using CB for a first time?

I really should push the release that improve this error message:
https://github.com/AcidWeb/CurseBreaker/commit/562790de399421dac6ac82491b844d4b94a41ff5

**Comment by AHrubik** [comment]
Nope. I've been using it for quite awhile now even before the CurseAPI/Overwolf debacle. In fact I used it as recently as the WoW 10.0.5 update to grab newer version of my addons.

**Comment by AcidWeb** [comment]
In this case something nuked your settings. Do you maybe replaced your `WTF` directory? In `WTF-Backup` you should find some recent backup to restore the `CurseBreaker.json` file.

**Comment by AHrubik** [comment]
Ahhh ... The recent WoW update required me to delete my Cache and WTF directories to be able to connect again. This explains the issue. I was able to restore the JSON from December and after some brief (re)uninstalling and (re)reinstalling of some addons already removed and installed everything is working again. 

Thank you for the help.

**Comment by AcidWeb** [comment]
Happy to help.
