### ISSUE TITLE
Feature Request: Command arguments

### ISSUE THREAD

**Issue by ninelore** [AcidWeb/CurseBreaker#360]
Got two:
- Twould be nice for terminal nerds to run something like `cursebreaker -c command`
  - When running install with this we could try to auto-correct to the closest match if an invalid name was given
  - This would be especially userful for example if you want to only partially clean up `orphans` with the help of `grep`
- A argument where it doesnt prompt for interactive mode and immediately closes after updating

TY :)

**Comment by AcidWeb** [comment]
This is already implemented.

`./cursebreaker orphans`
`./cursebreaker update`
`./cursebreaker headless`

**Comment by ninelore** [comment]
Oh sorry my bad, 

also notices that i shouldnt try to run the windows version via wsl :D
