### ISSUE TITLE
Error when attempting to update WeakAuras and Plater

### ISSUE THREAD

**Issue by eldir** [AcidWeb/CurseBreaker#362]
Not sure this is actually caused by CurseBreaker, but when I attempt to update my WAs and Plater scripts I just instantly get an error from CB:

![image](https://user-images.githubusercontent.com/5166778/230088385-36dc4843-5091-41f6-b2eb-29050521c5a5.png)

**Comment by AcidWeb** [comment]
It looks like it failing to parse the Plater storage. Can you share yours `Plater.lua`?

**Comment by cont1nuity** [comment]
New global SV was introduced to Plater:
```
PlaterLanguage = {
	["language"] = "enUS",
	["version"] = 1,
}
```
The relevant commit: https://github.com/Tercioo/Plater-Nameplates/commit/2f08e2ce8b1cb2cd496565714e0cdffeadaea67c#diff-48a154fc8f826f8efe50265b99457be003947152fe64842055f02e5e56c5db82

**Comment by AcidWeb** [comment]
That explain the breakage.
