### ISSUE TITLE
ElvUI update

### ISSUE THREAD

**Issue by Zeus93** [AcidWeb/CurseBreaker#367]
Using CurseBreaker to update ElvUI shows that the version number of ElvUI is still 13.34, and the latest version of ElvUI is 13.38

**Comment by AcidWeb** [comment]
Show me output of `status` command.

**Comment by Zeus93** [comment]
My English language skills are not good, don't know if this is what you want.
───────────────────────────────── CurseBreaker v4.5.1 ──────────────────────────────────
1/1 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ |
┌───────────────────┬───────────────┬─────────┐
│      Status       │ Name / Author │ Version │
├───────────────────┼───────────────┼─────────┤
│ Update suppressed │ ElvUI by Elv  │ 13.34   │
└───────────────────┴───────────────┴─────────┘


More than one WoW account detected.
Please use set wago_wow_account command to set the correct account name.

Press I to enter interactive mode or any other button to close the application.

**Comment by AcidWeb** [comment]
Update was not installed as something modified local files.

`force_update ElvUI` should fix it.

**Comment by Zeus93** [comment]
CB> status
1/1 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ |
┌───────────────────┬───────────────┬─────────┐
│      Status       │ Name / Author │ Version │
├───────────────────┼───────────────┼─────────┤
│ Update suppressed │ ElvUI by Elv  │ 13.34   │
└───────────────────┴───────────────┴─────────┘

**Comment by Zeus93** [comment]
Now it works,thanks.
