### ISSUE TITLE
Terminal resizing doesn't work on all terminals on linux

### ISSUE THREAD

**Issue by kurumushi** [AcidWeb/CurseBreaker#37]
This method of resizing works on xterm and urxvt, but not all terminals support resizing via escape codes. My suggestion is to just remove it altogether, since on linux the terminal is already open when we run the program, and we're not opening a new one.

https://github.com/AcidWeb/CurseBreaker/blob/b51175ee0e1a0674dadbc5c49759d314219f3f6e/CurseBreaker.py#L227-L228

When running on a terminal that doesn't accept the resizing (konsole in my case,) All the output of the program can end up in the scrollback buffer instead of in the live window where it should be.

Also thank you very much for adding linux support, One less reason to reboot for WoW.

**Comment by AcidWeb** [comment]
It looks more like konsole issue. During my tests on multiple terminal emulators resizing just worked or failed silently without scroll-back buffer issues.

**Comment by kurumushi** [comment]
The resizing also does not work on terminator, terminology, tilix, alacritty, sakura, lxterminal, deepin-terminal, qterminal, or kitty from my tests, although those terms don't suffer the scrollback problem as konsole, they just refuse to resize. I still stand by the opinion that as long as it's being run from within an existing terminal, and not started in a new window (as it is on windows) there is no reason to force the window to be a specific size.
