### ISSUE TITLE
Cursebreaker not installing the latest github release for Addon DialogKey

### ISSUE THREAD

**Issue by CrenshawCoding** [AcidWeb/CurseBreaker#371]
When I use the command `install gh:N0ich/dialogkey-DF` cursebreaker installs the addon DialogKey DF correctly. But it does not install the latest release, instead it installs version v1.4.8. The latest version as of the time of writing this is v1.5.1. The update command does not install the latest version either.

**Comment by AcidWeb** [comment]
It expected behavior. All GH releases after v1.4.8 don't provide proper packages.

**Comment by CrenshawCoding** [comment]
Ah okay, I’ll try and talk to the addon author about it. Thank you for you for your work.

**Comment by AcidWeb** [comment]
Pipeline is miss-configured. There is no point to use `ncipollo/release-action`. `BigWigsMods/packager` should handle GH releases too.
