### ISSUE TITLE
Backup breaks if a file is symlinked

### ISSUE THREAD

**Issue by eltreum0** [AcidWeb/CurseBreaker#376]
When creating a backup, if a file inside the WTF is symlinked it will throw an error

`OSError [WinError 4392] The data present in the reparse point buffer is invalid: 'pathtofile'`

This does not happen if the file is hardlinked instead

**Comment by AcidWeb** [comment]
After some additional discussion and tests this ticket is closed.

**Comment by eltreum0** [comment]
You can relabel as prob fixed since after i remade the links i havent had issues

Might be something on the windows side after all
