### ISSUE TITLE
Installing Curse only addons?

### ISSUE THREAD

**Issue by Zerophase** [AcidWeb/CurseBreaker#378]
I'm trying to install ranker on Linux, and don't want to have to install curseforge too. Is there anyway to use cursebreaker to download from custom URLs?

**Comment by AcidWeb** [comment]
This application don't support CurseForge in any form.

**Comment by Zerophase** [comment]
Is there anyway if I can get a static URL to install those addons?

**Comment by AcidWeb** [comment]
Static URL will not help you in any way.

**Comment by Zerophase** [comment]
> Static URL will not help you in any way.

What I mean is does install support static URLs?

**Comment by AcidWeb** [comment]
No.
