### ISSUE TITLE
Installation of a specific addon fails

### ISSUE THREAD

**Issue by tanrak** [AcidWeb/CurseBreaker#38]
First of all. Big praise for this simple, efficient and lightweight addon updater! Good work. Now the problem...
The install of https://www.curseforge.com/wow/addons/whoa-unitframes-for-wow-classic fails with error "Failed to parse addon data: whoa UnitFrames (for WoW Classic). The project doesn't have any releases.)".
https://www.curseforge.com/wow/addons/whoa-thickframes-for-wow-classic from the same author works without problems.

**Comment by AcidWeb** [comment]
CurseForge issue. For some reason API call: https://addons-ecs.forgesvc.net/api/v2/addon/338841 return that this project don't have any files released.

Can't do anything about it. It will probably start working by itself in few hours.

**Comment by tanrak** [comment]
Ok. Thanks for the info and the quick answer.

**Comment by AcidWeb** [comment]
It should work now.

**Comment by tanrak** [comment]
Thanks for the info. It works now.
