### ISSUE TITLE
Won't run on Linux

### ISSUE THREAD

**Issue by Jared0430** [AcidWeb/CurseBreaker#385]
Every time I launch the app, I get this message

> This executable should be placed in the same directory where Wow.exe, WowClassic.exe or World of Warcraft.app is located. Additionally, make sure that this WoW installation was started at least once.

I have installed Battle.net + WoW through Lutris, placed the executable in the `_retail_` folder, and launched the game at least once.

I have tested the v4.7 back to v4.2 and I get the same issue.

**Comment by AcidWeb** [comment]
You are running Linux version or Windows one through Lutris?

**Comment by Jared0430** [comment]
Running the Linux version. I tried to run the Windows version in the Wine prefix but it didn't launch at all

**Comment by AcidWeb** [comment]
Show me directory where binary is placed.

**Comment by Jared0430** [comment]
![image](https://github.com/AcidWeb/CurseBreaker/assets/3133657/8e088637-019b-4e27-818e-4f1e5ffe5b8e)

**Comment by AcidWeb** [comment]
`Interface/AddOns` exist?

**Comment by Jared0430** [comment]
Fixed - for some reason my addons folder was `Addons`, not `AddOns` (capital O). Seems that didn't matter back when I was on Windows, but does on Linux (I restored by Interface & WTF folders from a backup)

Thanks and sorry to waste your time
