### ISSUE TITLE
Is this still working for Mac at all?

### ISSUE THREAD

**Issue by tylertylerday** [AcidWeb/CurseBreaker#389]
Dropped the binary into the correct folder and when running it, it just asks about updating and exits.

**Comment by AcidWeb** [comment]
It is working.

Show me screenshot of what you see.

**Comment by tylertylerday** [comment]
Don't think I'll end up using this, didn't realize we needed a wago API key which costs money. Thanks though!

**Comment by AcidWeb** [comment]
It still supports other sources without that key.

**Comment by tylertylerday** [comment]
When I try searching or importing it says it's only available for wago?
