### ISSUE TITLE
WoW Classic .exe filename changed last night

### ISSUE THREAD

**Issue by boohyaka** [AcidWeb/CurseBreaker#39]
Hello AcidWeb,

Looks like Blizzard changed the WoW Classic exe filename yesterday, and CurseBreaker doesn't find the executable anymore.

![image](https://user-images.githubusercontent.com/31538990/70610471-ea52dc80-1c03-11ea-8d28-9ca9e3218981.png)

![image](https://user-images.githubusercontent.com/31538990/70610492-f343ae00-1c03-11ea-8153-a29307aebd8c.png)

Cheers

**Comment by AcidWeb** [comment]
Already fixed in 3.1.1.

**Comment by boohyaka** [comment]
why is my cursebreaker not auto-updating when launching it then?

**Comment by AcidWeb** [comment]
That is good question considering that auto-update mechanism is working correctly.

**Comment by boohyaka** [comment]
it always had indeed :) what should I try ?

**Comment by AcidWeb** [comment]
Update it manually. I see the problem. Binary check is executed before updating :-|

**Comment by boohyaka** [comment]
yeah that was my guess as I created a copy of wowclassic.exe and renamed it to wow.exe and it updated fine. I'm in 3.1.1 now. I will inform my friends that use your tool as well.

**Comment by AcidWeb** [comment]
Yeah I will fix it later today.

**Comment by AcidWeb** [comment]
I leave it as it is as 3.1.1 already support any future binary name change and no matter I do classic users will be forced to update 3.1.0 more or less manually.
