### ISSUE TITLE
Closes instantly

### ISSUE THREAD

**Issue by alexboutros** [AcidWeb/CurseBreaker#4]
I placed the cursebreaker.py into the folder with the wow.exe and when I click it the window opens and closes immediately. No errors about being in the wrong location or anything. Is this still working?

**Comment by AcidWeb** [comment]
You should use EXE version unless you have up and running entire Python environment with all dependencies.

**Comment by alexboutros** [comment]
Where can I find the EXE?

**Comment by AcidWeb** [comment]
https://github.com/AcidWeb/CurseBreaker/releases
