### ISSUE TITLE
Booty Bay Gazette not updating

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#40]
Booty Bay Gazette doesn't seem to update. My guess is that since it doesn't use versions ( just BootyBayGazette.zip ) CB thinks it's up to date.

**Comment by AcidWeb** [comment]
Yeah. To bypass part of API that works unreliable unique filename is required. And almost all projects do that. I poked author about it.

**Comment by AcidWeb** [comment]
Next releases should have version as part of the name.
