### ISSUE TITLE
maybe the wowinterface url is wrong

### ISSUE THREAD

**Issue by icaca** [AcidWeb/CurseBreaker#43]
correct url: https://cdn.wowinterface.com/downloads/file25188/NDuiClassic-1.15.0.zip?157969209013

also https://wowinterface.com/downloads/file25188/NDuiClassic-1.15.0.zip is correct

https://wowinterface.com/downloads/file{id}/{name}-{version}.zip

   https://wowinterface.com/downloads/25188-NDuiClassic.zip 404

**Comment by AcidWeb** [comment]
No it is not. URL is pulled from WoWI API.

https://cdn.wowinterface.com/downloads/getfile.php?id=25188&d=1579692090&minion

**Comment by icaca** [comment]
can i print the http result body

**Comment by AcidWeb** [comment]
Sure if you run it from sources and edit the code.

**Comment by AcidWeb** [comment]
Also as I said already in previous ticket even if that will start to work you will not be able to install NDuiClassic with CurseBreaker - it not support addons that contain texture packs.

**Comment by icaca** [comment]
I tested several monolithic plugins, including atlas and Auctionator

I will check the source code, maybe the website is restricted, or adding refer information can solve it.
