### ISSUE TITLE
Anti-virus reports this as a virus.

### ISSUE THREAD

**Issue by Oz0n3** [AcidWeb/CurseBreaker#44]
Bitdefender reports this the latest version is infected with Gen:Variant.Mikey.108936

**Comment by AcidWeb** [comment]
Get better AV. This is common issue with binaries created by PyInstaller.

https://www.virustotal.com/gui/file/d53d508e6022c822f96c00324fbb1d2c2694171e6678a3202f377686b155a24e/detection
