### ISSUE TITLE
Unable to remove/update addons that have changed names

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#45]
see:
https://i.imgur.com/756oo0r.png

**Comment by AcidWeb** [comment]
Yeah this scenario is definitely not handled. 

Try to uninstall both, restart CB and install it again.

**Comment by tordenflesk** [comment]
I noticed that my example wasn't an addon that'd changed name, but the same one split in two by a comma for the update and uninstall actions.
Manually deleting the folder marks the addon as 'modified'

**Comment by AcidWeb** [comment]
Remove files manually and then remove both entries in CurseBreaker.json in WTF directory.
After that normal install should work.

I need to think how to handle this issue.

**Comment by AcidWeb** [comment]
OK. I think I know how to fix it permanently. I will fix it in next release.

**Comment by AcidWeb** [comment]
Could you describe application behavior when project is renamed?
