### ISSUE TITLE
WoWInterface and classic Addons

### ISSUE THREAD

**Issue by tanrak** [AcidWeb/CurseBreaker#46]
WoWInterface has as well as Curseforge two download buttons if an Addon exists for retail and classic (since when can I not say). An Example of this is [Lagbar](https://www.wowinterface.com/downloads/info12373-LagBar.html). It would be nice if Cursebreaker could handle this and not always download the retail version for classic.

**Comment by AcidWeb** [comment]
I know and I would love to implement that but WoWI API don't support it. Call simply return data only for retail.

**Comment by torkus** [comment]
You can get the list of supported game versions from the wowi *fileList.json* file. 

An entry might look like this for example:

```json
{    ...
    "UICompatibility": [
        {"version":"1.13.3","name":"WoW Classic Patch"},
        {"version":"8.3.0","name":"Visions of N'Zoth"}
    ]
    ...
}
```

my [pretty simple approach](https://github.com/ogri-la/wowman/blob/develop/src/wowman/wowinterface.clj#L128-L145) is:

> if "WoW Classic" found, addon supports classic. 
> if more found, addon supports both classic and retail
> if not found, or nil found, supports retail only

**Comment by AcidWeb** [comment]
That part is not an issue.

How you getting separate download links?

**Comment by torkus** [comment]
that's a good point. I just checked and I don't think I do!

addons that support one or the other are fine, but I'm not sure about those addons that support both. 

LagBar only supports classic according to the 'api'.

**Comment by AcidWeb** [comment]
And the same API return link to retail release.

Support for this "double" project was never implemented in Minion.

**Comment by torkus** [comment]
I've sent them a friendly email, maybe they'll get back to me.

**Comment by layday** [comment]
I hope you don't mind me chiming in here.  I think we might've discussed this before on the wowman bug tracker.  The `UICompatibility` field is not reliable, e.g. for LagBar it only lists Classic.  I might've considered scraping the URL if I could at least depend on the API response being accurate.

**Comment by AcidWeb** [comment]
Development of Minion 3 stopped and Minion 4 is apparently dead so I don't expect that API will be updated to handle this type of "double" projects.

**Comment by teelolws** [comment]
You could scrape the alt-text for the download links on the WoWI page? "WoW Retail" and "WoW Classic".

**Comment by AcidWeb** [comment]
This application by design don't scrape anything and use API only.
