### ISSUE TITLE
Request Log File and Auto Close

### ISSUE THREAD

**Issue by Kanegasi** [AcidWeb/CurseBreaker#47]
I would like to request an option to generate a log file for addon updates. Either a simple window dump or something like logging all updates and update suppressions.

In sync with this suggestion, an option for the window to immediately close instead of waiting for a key press.

**Comment by AcidWeb** [comment]
I agree that proper headless mode is missing.

For now dirty workaround is caliing CurseBreaker binary with `update` argument. That will start update that don't wait for keypress after finishing the job.

**Comment by AcidWeb** [comment]
Implementing this turned out to be more difficult than I thought.
As due to how binary is created it always open empty console window - even if there is no ouput.

**Comment by AcidWeb** [comment]
It is not perfect but it should be good enough.
