### ISSUE TITLE
Failed to parse addon data: not well-formed (invalid token): line 41, column 128

### ISSUE THREAD

**Issue by icaca** [AcidWeb/CurseBreaker#48]
Failed to parse addon data: not well-formed (invalid token): line 41, column 128

**Comment by AcidWeb** [comment]
And this is output of what command?

**Comment by icaca** [comment]
mac os
![image](https://user-images.githubusercontent.com/279229/74194805-f9521b80-4c94-11ea-8b17-fe3c17f65d61.png)

**Comment by AcidWeb** [comment]
Upload yours CurseBreaker.json from WTF directory.

**Comment by icaca** [comment]
[CurseBreaker.json.zip](https://github.com/AcidWeb/CurseBreaker/files/4183299/CurseBreaker.json.zip)

**Comment by AcidWeb** [comment]
Classic I presume? Your file is working correctly for me so I can only guess that CF or WoWI API have some issues in your location.

these pages open for you?
https://addons-ecs.forgesvc.net/api/v2/addon/15564
https://api.mmoui.com/v4/game/WOW/filedetails/23978.json

**Comment by icaca** [comment]
yes i can

**Comment by icaca** [comment]
![image](https://user-images.githubusercontent.com/279229/74261270-f52a0a80-4d35-11ea-882b-ebc9f94db8fc.png)

install, uninstall is ok

**Comment by icaca** [comment]
i remove the json file, and its ok now.
the new json file:

[CurseBreaker.json.zip](https://github.com/AcidWeb/CurseBreaker/files/4187249/CurseBreaker.json.zip)

**Comment by AcidWeb** [comment]
Not sure how that helped. But if it works...
