### ISSUE TITLE
 Failed to parse addon data: !!Loop Protection!! We have tried to solve 3 time(s) in a row.

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#49]
[CurseBreaker.json.txt](https://github.com/AcidWeb/CurseBreaker/files/4284342/CurseBreaker.json.txt)

**Comment by AcidWeb** [comment]
Problem is caused by fact that Cloudflare changed security a little. I will release update today to fix it.

**Comment by tordenflesk** [comment]
The error has returned today.

**Comment by AcidWeb** [comment]
We can only wait for cloudscraper update.

**Comment by tanrak** [comment]
Yesterday the error appeared again.

**Comment by AcidWeb** [comment]
I know. Still waiting for cloudscraper update.

**Comment by tanrak** [comment]
Ok. Thanks for the info.

**Comment by tanrak** [comment]
For your information. The error coming up again.

**Comment by AcidWeb** [comment]
CloudFlare changed something again.
