### ISSUE TITLE
Searches are not returning all results

### ISSUE THREAD

**Issue by alexboutros** [AcidWeb/CurseBreaker#5]
I am searching in CurseBreaker for an addon called "Mechagon Rare Share - MRS" and it's not showing up. I've tried "mechagon", "mechagon rare", "mechagon rare share", "MRS" and none of them get me the addon I'm looking for. Here's the URL of the addon: https://www.curseforge.com/wow/addons/mechagon-rare-share

**Comment by AcidWeb** [comment]
If you use that phrases in curseforge search page you also will not find that addon. Because it currently don't have any releases.
