### ISSUE TITLE
Failed to parse addon data: Cloudflare reCaptcha detected...

### ISSUE THREAD

**Issue by tanrak** [AcidWeb/CurseBreaker#51]
An unending drama with CloudFlare...

`Failed to parse addon data: Cloudflare reCaptcha detected, unfortunately you haven't loaded an anti reCaptcha provider correctly via the 'recaptcha' parameter.`

**Comment by AcidWeb** [comment]
I need to rethink my approach. As CF problems are piling up and too much depend on user location.

reCaptcha providers are paid services so using them is not an option.

**Comment by AcidWeb** [comment]
@tanrak Could you find exactly which addon cause this error?

**Comment by tanrak** [comment]
These two addons:
https://www.curseforge.com/wow/addons/auctionator-classicfix
https://www.curseforge.com/wow/addons/moonscarlets-chatscanner

**Comment by AcidWeb** [comment]
Thanks I will check it why they need to fallback to CloudFlare protected endpoints.

**Comment by AcidWeb** [comment]
Try now.

**Comment by tanrak** [comment]
Nope.

**Comment by AcidWeb** [comment]
Download https://storage.googleapis.com/cursebreaker/cfid.pickle.gz and upload it here.

**Comment by tanrak** [comment]
I do not understand the meaning of this action? But here is the file...
[cfid.pickle.gz](https://github.com/AcidWeb/CurseBreaker/files/4487214/cfid.pickle.gz)

**Comment by AcidWeb** [comment]
I wanted to be sure that you getting updated file.
Go to `WTF` directory and remove `CurseBreaker.cache` and try again.

**Comment by tanrak** [comment]
After remove `CurseBreaker.cache` install/update of the two affected addons works again.

**Comment by AcidWeb** [comment]
OK. As long user is not installing very new addon from CurseForge CloudFlare should not make any problems.

**Comment by tanrak** [comment]
Ok. Thanks for the info and your work.

**Comment by tordenflesk** [comment]
I'm getting this error as well. Deleting CurseBreaker.cache doesn't help.

**Comment by AcidWeb** [comment]
Delete cache and try again.

**Comment by tordenflesk** [comment]
Did that 3 times, no change.

**Comment by AcidWeb** [comment]
Yeah but I just pushed new version.

Problem is simple.

I need the project ID. Around 98% of them are easily obtainable. Rest of them are not popular projects or projects not marked as released and I need to use fallback endpoint that is secured by CloudFlare to get that ID.

In most of the cases that endpoint don't ask user to fill the captcha. But when user is flagged for captcha I simply can't do anything about it.

**Comment by AcidWeb** [comment]
I will add some local cache for project ID. So if only one CF secured query will be successful it will not require another one.

**Comment by AcidWeb** [comment]
Next release will try to migrate this issue a little.

**Comment by icaca** [comment]
─────────────────────────────────────────── CurseBreaker v3.5.1 ────────────────────────────────────────────

0/38 | ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ |
RuntimeError: Failed to parse addon data: Cloudflare reCaptcha detected, unfortunately you haven't loaded an
reCaptcha provider correctly via the 'recaptcha' parameter.

**Comment by AcidWeb** [comment]
Can't do anything with it. We need to wait for cloudscraper update.

Upload yours `CurseBreaker.json` from `WTF`.
