### ISSUE TITLE
Trojan detection

### ISSUE THREAD

**Issue by Earthling-Z4R0** [AcidWeb/CurseBreaker#54]
CurseBreaker.exe (0.3.1.10) is flagged for containing a trojan on virustotal.com.

Only one of the many engines is "detecting it" so I guess it's a false positive.
Just making you aware for what it's worth.

Cheers!

https://www.virustotal.com/gui/file/78bf2712f4f2fee6443b737911d1ffa27f00ba0ef5cb386de73311f84cc6a5db/detection

**Comment by AcidWeb** [comment]
Yep. False positive. Some garbage AV don't like Python binaries created by PyInstaller.
