### ISSUE TITLE
Errno 13 Permission denied

### ISSUE THREAD

**Issue by d3aths** [AcidWeb/CurseBreaker#55]
trying to install a few addons manually, keep getting permission denied error. cursebreaker is in the normal windows wow directory of C:/program files x86/world of warcraft.
have an admin windows account, tried to run cursebreaker as admin. any other options to fix this? folder permissions are definitely set to full control as well

**Comment by AcidWeb** [comment]
Interesting. You can't install any addon or some are working?

**Comment by AcidWeb** [comment]
I just tested installation in `Program Files` directory. For me CB correctly detect lack of permissions and ask for admin rights. After restarting with admin rights everything work correctly.

**Comment by d3aths** [comment]
just testing it now with random addons. the problematic addons were tu: 3 and tu: 79.
i originally had them and the import didn't pick them up, telling me to install manually.
so `install tu: 79` and `install tu: 3` were giving me the error whereas trying random tu: or cf: addons was installing fine.
trying the `import install tu: 3` command however gives a different output, 
![image](https://user-images.githubusercontent.com/16113944/82849212-f7ae1a00-9f4a-11ea-97a9-f998e3f0e034.png)
so i follow what the possible matches says and install the addonskins and project azilroka from the curseforge link instead, which executed without problems

**Comment by AcidWeb** [comment]
OK. So problem is with TukUI page integration not entire CurseBreaker. I will check it.

`import install tu:3` command don't exist. It is doing the same thing as `import`.

**Comment by AcidWeb** [comment]
I can't replicate this issue.

**Comment by d3aths** [comment]
i think the cause was that i had those two tukui addons before installing cursebreaker, and when importing all my addons failed to pick those two up, installing manually then gave an error. i tested downloading other addons i didnt previously have from tukui as well, and they installed fine.

**Comment by AcidWeb** [comment]
Import don't detect TukUI addons at all - that is not a bug. But what you saying makes sense - CB failed to overwrite already existing directory. I will try to replicate that.

Try to manually delete directories of that addons and then install them in CB.

**Comment by AcidWeb** [comment]
Also completely unrelated: AddonSkins are no longer updated on TukUI. You need to get it from CurseForge.

**Comment by AcidWeb** [comment]
OK. Got it. As expected overwriting the directories is failing. I will check it out.
