### ISSUE TITLE
Failed to parse addon data: project-2590

### ISSUE THREAD

**Issue by Erothas** [AcidWeb/CurseBreaker#57]
![image](https://user-images.githubusercontent.com/55455670/83503636-e87f1d00-a4b2-11ea-9c39-fdf4c66459df.png)
I have been using CurseBreaker for months without a single problem. I haven't installed or even changed any addon recently. This is what I got today though.

**Comment by AcidWeb** [comment]
Apparently one of your addons was deleted from the source. Open `CurseBreaker.json` in `WTF` directory and show me record around `project-2590` entry.

**Comment by Erothas** [comment]
![image](https://user-images.githubusercontent.com/55455670/83504243-cf2aa080-a4b3-11ea-802a-1dbb6647fd08.png)
I have not removed anything, but there you go :)

**Comment by AcidWeb** [comment]
You don't but project owner renamed it.

This should fix it: `uninstall BuyEmAll BfA`, `install cf:buyemall`.

**Comment by Erothas** [comment]
Oh, that fixed it. Thank you very much for the hasty response and help!
