### ISSUE TITLE
Classic Support for curseforge

### ISSUE THREAD

**Issue by TheRealYasri** [AcidWeb/CurseBreaker#6]
Hello, I have been looking for a way to manage addons for wow, when classic comes out. Your program is the best I have found(nice work by the way). It works great if the only version of a addon is for classic but if the dev posts modern and classic versions on the same page it will only download the modern one.

Not sure how you go about scraping the info, so here is some info that may help. When you 
look a the files tab on a addon there is a way to filter by modern/classic/all.

Show All
https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=
Show Modern
https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=1738749986%3A517
Show Classic
https://www.curseforge.com/wow/addons/deadly-boss-mods/files/all?filter-game-version=1738749986%3A67408

This seems to be common between any given addon.
/files/all?filter-game-version=
/files/all?filter-game-version=1738749986%3A67408
/files/all?filter-game-version=1738749986%3A517

So when given a link to install from like
https://www.curseforge.com/wow/addons/deadly-boss-mods/
It should be possible append the rest of it, depending on if you want classic/modern. With falling back to ALL, if modern/classic ones fails.

Thanks you for your time. Hope the above helps/makes sense.

**Comment by AcidWeb** [comment]
I'm planing to look on classic support when Curseforge stabilize support of it. Because currently it is WIP mess.

**Comment by TheRealYasri** [comment]
Yeah seems to be a mess on their end. Only found two official comments by curse for classic, but no current status.
https://twitter.com/CurseForge/status/1136020455544909824
https://twitch.uservoice.com/forums/915910-game-mods-curseforge/suggestions/37723903-will-you-add-classic-world-of-warcraft-addons-as-i

I have currently just went with making a bookmark for each addon like I posted above, sense it seems to be the only way to tell what the newest version of a addon is for classic. 

I was not sure how you parse out the data to install/update addons, so I thought I would post the only thing I could find that seems to be universal if you are just scrapping a webpage. So all you need is the addon name to make a link with the right text append on the end, to find the page to scrap from.

**Comment by AcidWeb** [comment]
API was updated I will release new version soon. As long there are separate release for live and classic then everything work correctly. If release file is tagged for both classic and live then API consider that file classic only.

**Comment by TheRealYasri** [comment]
Thanks for the update, seems to be working. If I find any bugs I will notify you.
