### ISSUE TITLE
Dev preference

### ISSUE THREAD

**Issue by Rubgrsch** [AcidWeb/CurseBreaker#60]
When CB updated to 3.3.0 and 3.3.1, all addons dev preferences reset to stable.

And if possible, please add a command/option to toggle all addon dev perferences, like 'toggle_all_dev'.

Cheers.

**Comment by AcidWeb** [comment]
Yeah there is a bug in config migration code.

But it is strange - it should reset to beta releases. Not to stable.

**Comment by Rubgrsch** [comment]
Yeah i use alpha since they dont have beta release 0.0
