### ISSUE TITLE
Just started app for the first time and got this error on update or status command

### ISSUE THREAD

**Issue by Blessvk** [AcidWeb/CurseBreaker#62]
UnboundLocalError: local variable 'exceptions'referenced before assignment

**Comment by AcidWeb** [comment]
You installed any addons using CB? Or used `import` command?

**Comment by AcidWeb** [comment]
OK. I replicated this issue. Problem is caused by empty list of installed addons. I will fix it in next release.

**Comment by Blessvk** [comment]
CB can't catch up already installed addons? (that was installed without CB running)

**Comment by AcidWeb** [comment]
Use `import` command.
