### ISSUE TITLE
set_wa_wow_account does not properly save account name

### ISSUE THREAD

**Issue by Actual** [AcidWeb/CurseBreaker#63]
Hi,

New install, addons updated, when trying to update weakauras via wa_update receive notification

"More than one WoW account detected.
Please use set_wa_wow_account command to set the correct account name."

executing `set_wa_wow_account <accountname>` seems to work, however re-running `wa_update` gives same error as above. I've tried from within an admin CMD and from admin Windows Terminal as well as running without elevation to no change.

**Comment by marett** [comment]
Same issue, have successfully installed/updated adds, however the `set_wa_wow_account <accountname>` does not seem to be registering/storing the supplied account name.

**Comment by AcidWeb** [comment]
I will check it out.
