### ISSUE TITLE
wa_update does not detect https://wago.io/14Sz-T-dm

### ISSUE THREAD

**Issue by kdurski** [AcidWeb/CurseBreaker#65]
Running `wa_update` does not detect "Horrific Visions" WA and consequently does not update it. However, the WeakAuras Companion app does detect and update it correctly.

**Comment by AcidWeb** [comment]
Please link the aura.

**Comment by AcidWeb** [comment]
OK I can replicate this issue. It is a bug.

**Comment by AcidWeb** [comment]
It will be fixed in next release.

**Comment by kdurski** [comment]
Great, thanks
