### ISSUE TITLE
OpenSSL Deprecation warning

### ISSUE THREAD

**Issue by Bak3y** [AcidWeb/CurseBreaker#66]
I'm seeing this warning when launching CurseBreaker:

`DEPRECATION: The OpenSSL being used by this python install (OpenSSL 1.0.2t  10 Sep 2019) does not meet the minimum supported version (>= OpenSSL 1.1.1) in order to support TLS 1.3 required by Cloudflare, You may encounter an unexpected reCaptcha or cloudflare 1020 blocks.`

The app works fine, though.

**Comment by AcidWeb** [comment]
How do you launch it?

**Comment by Bak3y** [comment]
I created an alias in zsh:

`❯ alias | grep cb
cb='cd "/Applications/World of Warcraft/_retail_" && ./CurseBreaker'`

**Comment by AcidWeb** [comment]
Interesting. It looks like macOS build environment might not be up-to-date.

**Comment by AcidWeb** [comment]
Apparently fixing it require switching macOS builder to Python 3.8. CurseBreaker supports 3.8 but PyInstaller don't.

**Comment by chromaerror** [comment]
> Apparently fixing it require switching macOS builder to Python 3.8. CurseBreaker supports 3.8 but PyInstaller don't.

There's an open pull request about PyInstaller being updated to support 3.8, so probably shouldn't take long anymore.
Here's a link to the PR: https://github.com/pyinstaller/pyinstaller/pull/4986

**Comment by AcidWeb** [comment]
I'm aware. But that PR have long way to go.

**Comment by alexchandel** [comment]
If you're feeling adventurous, compile it yourself.  The holdup is Windows crap.  The non-Windows 3.8 bits are fine.
