### ISSUE TITLE
Project Azilroka fails to update

### ISSUE THREAD

**Issue by jmsundar** [AcidWeb/CurseBreaker#67]
Latest version of projectazilroka on curseforge is 1.67, when I run install cf:projectazilroka it gives me version 1.65

```
CB> install cf:projectazilroka
1/1 | ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓ |
┌───────────┬─────────────────┬─────────┐
│  Status   │ Name            │ Version │
├───────────┼─────────────────┼─────────┤
│ Installed │ ProjectAzilroka │ 1.65    │
└───────────┴─────────────────┴─────────┘
```

![image](https://user-images.githubusercontent.com/29724673/85429751-ceca7600-b544-11ea-9f48-fb7018a82146.png)

**Comment by AcidWeb** [comment]
1.67 is classic only. Latest retail version is 1.65.

**Comment by deikun** [comment]
Use install tuc:8 instead
https://www.tukui.org/classic-addons.php?id=8
