### ISSUE TITLE
fails to update a weakaura

### ISSUE THREAD

**Issue by mrminus** [AcidWeb/CurseBreaker#68]
running "wa_update" finds an "outdated weakaura" ("quaking stop casting warning"), but will not update it. No clear command is available to update that wa. I did try to find the two-letter code for wago.io but was unsuccessful.  "Update" will not update the weakaura.

**Comment by AcidWeb** [comment]
This work the same as WeakAura Companion. You still need click update button for that aura in-game.

**Comment by mrminus** [comment]
I read your comment to be that CurseBreaker will not update a specific aura, but will only tell you that it is out of date. I need to use something else to actually do the update to the aura. Is that correct?

**Comment by AcidWeb** [comment]
No. It create the same payload as WeakAuras Companion. New aura is loaded there and need to be upgraded in-game.

**Comment by mrminus** [comment]
Ok. I see. I did not realize that this was possible. I am in-game now and see the update in the WeakAura addon now. Thanks.
