### ISSUE TITLE
Uninstall command does not support listed format

### ISSUE THREAD

**Issue by BuccoBruce** [AcidWeb/CurseBreaker#69]
When attempting to uninstall addons, the only format that is supported is the full URL.  Shortened URLs, IE "cf:bagnon" do not uninstall, which is listed as supported in the command output.  It is possible to use the addon name to uninstall, but these are case sensitive and do not match the same format.

![image](https://user-images.githubusercontent.com/7907576/85434000-34fdcb80-b53a-11ea-8a8b-e161d2c547e1.png)

**Comment by AcidWeb** [comment]
Yeah. Help is incorrect. I will fix it.

Also `uninstall` command support autocomplete.
