### ISSUE TITLE
Multiple characters appear when typing, adding one extra for every command entered

### ISSUE THREAD

**Issue by Jeremy7600** [AcidWeb/CurseBreaker#70]
When typing commands after the first command, the character is either echo'd back to the terminal or it is being repeated somehow. This happens in command prompt and the Microsoft Terminal under both powershell and Command Prompt. 
Each command entered causes the echo to increase. So the 2nd command the characters are doubled, the 3rd they are tripled, etc. Backspace plays the characters backwards. 

This shows the repeat after one command is entered:
![Capture](https://user-images.githubusercontent.com/62718826/85454628-bcf7cb80-b562-11ea-89c5-e31270e8a4b2.PNG)

This shows what happens for the next prompt. I typed "status" and backspaced 5 times to produce this result:
![extra characters](https://user-images.githubusercontent.com/62718826/85454630-bd906200-b562-11ea-8e65-715192c71547.PNG)

I can enter the commands and run them if I enter them correctly without typos, but if I have to backspace I have to start a new command from the prompt. 

Windows 10 Pro 1903

**Comment by AcidWeb** [comment]
I don't have slightest idea what can cause this.

**Comment by Jeremy7600** [comment]
It doesn't happen in other apps from the CLI. I used the Far File Manager 3 to launch CurseBreaker from the command line and got the same result. It only occurs within CurseBreaker and not other CLI apps as far as I can tell.

**Comment by AcidWeb** [comment]
I not found any way to replicate this and nobody else reported this issue. Unless somebody can shed some light on this issue I can't fix it.
