### ISSUE TITLE
Show number of weakauras outdated line

### ISSUE THREAD

**Issue by Shirozwei** [AcidWeb/CurseBreaker#75]
Hello 

How do I make cursebreaker show "The number of weakauras outdated: 0"
https://imgur.com/a/1kfSPXN

my cursebreaker:
https://imgur.com/a/LnEptTp

Also is there a way to turn off automatic updating

**Comment by AcidWeb** [comment]
Update your auras in-game. There is button next to outdated ones in WA list.

And no.
