### ISSUE TITLE
Would like a way to ingore certain addons from auto-update

### ISSUE THREAD

**Issue by deikun** [AcidWeb/CurseBreaker#77]
In the Twitch Client I would typically ignore certain addons like TSM, RaiderIO, and ElvUI (AddonSkins too) as they each use their own updater client. Twitch was known to overwrite newer versions of those, or modified versions as with TSM, with the latest (but now out of date) versions that CurseForge had.

Would it be possible to flag certain addons to be ignored by the auto-updater?

Or even at least implement updating ElvUI addons using a tukui.org as their installation source instead of CurseForge? Currently it seems you can install from tuk:xxx but it doesn't flag them as from tuk: and will only process updates from cf:.

**Comment by AcidWeb** [comment]
Simply don't add them to CurseBreaker (or remove them if import add them) and let other application do the work. They will not be re-added.

Second part don't have sense. It definitely update them from all sources.

**Comment by deikun** [comment]
Ahhh okay I see the first part now.

The second part is that it's not really clear what the source is for each addon. Is there any way to see that in the status?

**Comment by AcidWeb** [comment]
If you used `import` all addons were installed from CurseForge. If you want to use different source - `uninstall` them and `install`  them again using different URL.

**Comment by deikun** [comment]
Yeah that's what I did just to be safe. Thanks for the clarification and your replies. Love the application my friend. Cheers!
