### ISSUE TITLE
[Suggestion] Build instructions

### ISSUE THREAD

**Issue by aproctor** [AcidWeb/CurseBreaker#78]
Thanks a lot for this addon, with Overwolf coming in to take over CurseForge I really welcome an open source alternative.

I think it'd be helpful for people who are like me if they could build their own executable rather than download it.

I've never distributed python exe's and a little bit of searching and trying out a few solutions (py2exe, pyinstaller) I was hitting a few roadblocks with the project.

I ended up just running it without compilation, and hacking in a working directory change to my WoW folder instead, but I'd love to be able to stay up to date with the project.

**Comment by AcidWeb** [comment]
Build process is already in repo:
https://github.com/AcidWeb/CurseBreaker/blob/master/.github/workflows/build.yml

Path to WoW client can be overridden with `CURSEBREAKER_PATH ` enviroment variable as README states.
