### ISSUE TITLE
Feature Request: GitHub Release URL

### ISSUE THREAD

**Issue by Avyiel** [AcidWeb/CurseBreaker#79]
As per the title, I believe it would be great if support for GH Releases could be added. Some addons aren't on CF or WoWI because of licensing issues or stuff like that.

Downloading the latest release is as easy as using the following URL format. Versioning might be more of a challenge, though.

```
https://github.com/owner/repository/releases/latest/download/file.ext
```

If this has already been considered and dismissed, feel free to close! Just thought I'd suggest it.

**Comment by AcidWeb** [comment]
If addon is disallowed both on WoWI and Curse it should not exist as it is malicious and/or author don't give a damn about code licenses.

I'm not planing to add direct Github support. Look on #41 for details.

**Comment by Avyiel** [comment]
Not at all! I have a custom edit of an Addon or two that I'm not allowed to redistribute on CF or WoWI (even though the forking/editing is perfectly fine as per the license), and I just thought it would be cool if I could use CurseBreaker to handle downloading the latest releases I patch.

I skimmed #41 and #13 as you suggested, and I understand why this won't be a thing. Thank you regardless, great project!

**Comment by Avyiel** [comment]
Just saw the new release, thanks a lot!
