### ISSUE TITLE
Failed to parse addon page

### ISSUE THREAD

**Issue by alexboutros** [AcidWeb/CurseBreaker#8]
I've been getting this many addons lately. I'm using CurseBreaker with classic wow, and while most addons install fine some give me "Failed to parse addon page. Url is wrong or your source has some issues"

Latest addon I've been experiencing this with is https://www.curseforge.com/wow/addons/modernquestwatch
Also happens with random wowinterface addons such as https://www.wowinterface.com/downloads/info24980-QuestLogEx.html

**Comment by AcidWeb** [comment]
WoWI API return no data for addon 24980.

CurseForge API return information that Modern QuestWatch don't have any release. Not a suprise classic support on CF is simply broken.

Anyway this is nothing that I can fix.

**Comment by AcidWeb** [comment]
Apparently CF API will be fixed this week.
