### ISSUE TITLE
Unable to install AuroraClassic from Github

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#80]
CB> install https://github.com/siweia/AuroraClassic
RuntimeError: Failed to parse addon data: https://github.com/siweia/AuroraClassic
CB> install gh:siweia/AuroraClassic
RuntimeError: Failed to parse addon data: https://github.com/siweia/AuroraClassic

**Comment by AcidWeb** [comment]
Currently it support only manually created packages. I can digest raw repos.
