### ISSUE TITLE
toggle_dev global doesn't rotate between beta/alpha/stable

### ISSUE THREAD

**Issue by bsolar17** [AcidWeb/CurseBreaker#81]
Using the `toggle_dev global` command always switches the global state to beta, at least according to the command output.

```
CB> toggle_dev global                                                                               
All CurseForge addons are now switched to the beta channel.
CB> toggle_dev global                                                                               
All CurseForge addons are now switched to the beta channel.
CB> toggle_dev global                                                                               
All CurseForge addons are now switched to the beta channel.
CB>
```

I think subsequent invocations are supposed to switch between the 3 available states, so a second invocation should switch to alpha and a third back to stable.

**Comment by AcidWeb** [comment]
Upload here yours `CurseBreaker.json` from WTF directory.

**Comment by bsolar17** [comment]
This is the content of the file:

```
{
    "Addons": [],
    "Backup": {
        "Enabled": true,
        "Number": 7
    },
    "CFCacheCloudFlare": {},
    "CFCacheTimestamp": 0,
    "IgnoreClientVersion": {},
    "Version": "3.4.0",
    "WAAPIKey": "",
    "WAAccountName": "",
    "WACompanionVersion": 0,
    "WAUsername": ""
}
```

**Comment by AcidWeb** [comment]
You don't have any addons installed. That command change state of already installed ones not set the global default. I'm aware that is sub-optimal.

**Comment by bsolar17** [comment]
Ok so if I understand correctly I should first import my addons and then change the state.

**Comment by AcidWeb** [comment]
For now -  yeah. I will probably extend this feature in the future.

**Comment by bsolar17** [comment]
FYI I successfully imported my ~100 addons, set everything to alpha and updated everything again. All addons except TradeSkillMaster_AppHelper works flawlessly.

**Comment by AcidWeb** [comment]
I don't use TDM but I guess that TradeSkillMaster_AppHelper will be overwritten by their client anyway so maintaining it with CB don't have much sense.

**Comment by bsolar17** [comment]
Yes, just running the TSM Application again updated the addon files as TSM expects them: then the addon is recognized as "modfied" and as far as I understand it would not be updated anymore unless I force CurseBreaker to do it.

**Comment by AcidWeb** [comment]
Yes. You can also simply remove `TradeSkillMaster_AppHelper` from CB.
