### ISSUE TITLE
RuntimeError: Failed to parse addon data:

### ISSUE THREAD

**Issue by Xozat** [AcidWeb/CurseBreaker#82]
`RuntimeError: Failed to parse addon data: method-dungeon-tools
The project could be removed from CurseForge or renamed. Uninstall it (and reinstall if it still
exists) to fix this issue.`

MethodDungeonTools was renamed to MythicDungeonTools. How do I fix this error?

**Comment by allygator** [comment]
`uninstall mythic-dungeon-tools` and `install cf:mythic-dungeon-tools`

I dont have a reason, but this worked for me.

**Comment by Xozat** [comment]
That didn't work for me Allygator, thank you though. What I ended up doing to fix it was deleting "CurseBreaker.json" and "CurseBreaker.cache" then re-importing my addons to the program and updating.

**Comment by AcidWeb** [comment]
Proper solution was to `uninstall Method Dungeon Tools` and `install cf:mythic-dungeon-tools`. Both commands have autocomplete...
