### ISSUE TITLE
GitHub Releases: CurseBreaker is not detecting add-on version

### ISSUE THREAD

**Issue by Avyiel** [AcidWeb/CurseBreaker#84]
Once again, thanks for getting support for GH releases up. I did stumble upon an issue though. 

## Description
The add-on is installed correctly, but it seems version checking isn't working properly and I cannot update the add-on.

The add-on I'm trying to install is here: https://github.com/Avyiel/TinyWigs

## Repro steps
1. Install addon: `install gh:Avyiel/TinyWigs`
2. Check status:
![Screenshot 2020-07-01 at 17 40 13](https://user-images.githubusercontent.com/1761244/86263769-f0210700-bbc1-11ea-8656-082aefd255f9.png)
3. Try to update:
![Screenshot 2020-07-01 at 17 41 01](https://user-images.githubusercontent.com/1761244/86263859-09c24e80-bbc2-11ea-90df-42d7a8854ad4.png)
4. Try to reinstall:
![Screenshot 2020-07-01 at 17 41 23](https://user-images.githubusercontent.com/1761244/86263898-1646a700-bbc2-11ea-954e-846cc8168f66.png)

**Comment by AcidWeb** [comment]
Upload yours `CurseBreaker.json` from WTF directory.

**Comment by AcidWeb** [comment]
NVM. I replicated the issue.

**Comment by AcidWeb** [comment]
Uninstall it and install again after 3.4.2 update.

**Comment by Avyiel** [comment]
Just did as instructed, it's fixed now.

Damn, you are quick. Too bad I can't sponsor you twice, mate
