### ISSUE TITLE
[Request] search description, better output and more

### ISSUE THREAD

**Issue by gi2k15** [AcidWeb/CurseBreaker#87]
Hi, I've downloaded CB today and I'm really enjoying how easy this does its job. However, I want to suggest two additions:

1. Search also into descriptions. Right now, CB only looks for addons' names. It'd be nice to search on descriptions too, perhaps even categories (or tags). With that, searching "tooltip" would show better results.
2. If the above is implemented, maybe the output could be in a table, just like the one when you add several addons at once.
3. Speaking of adding several addons, autocomplete only works with install (and I guess with other commands too) untill the first addon. After you add the comma, it doesn't autocomplete anymore. It'd be awesome if this could be solved.

Right now, that's it. Thanks for the great program!

**EDIT:** forgot to mention another thing. Right now, CB can install some registries to open cf links. However, it doesn't offer the option to uninstall it.

**Comment by AcidWeb** [comment]
I use official CurseForge search and I don't plan to extend this feature.

Autocompletion - not sure if it can be solved. It is already too cpu heavy.

There is no usercase for uninstalling them. You overwrite Twitch associations or create associations that are not used by anything else.
