### ISSUE TITLE
Disable automatic update for specific addons

### ISSUE THREAD

**Issue by Krytos** [AcidWeb/CurseBreaker#89]
Would it be possible to add an auto update toggle similar to the toogle_dev function? The newest ElvUI update just destroyed my interface and I would rather not update it automatically anymore.

**Comment by Repooc** [comment]
I am certain it wasnt destroyed... You should come to the discord for any issues you feel was broken.  A good amount of changes were made and some defaults of some things were changed and if they were not changed from the previous default then yes those would change a bit

**Comment by AcidWeb** [comment]
Yeah I also highly doubt that update "destroyed" your interface.

Anyway I dislike idea of option that block the upgrades - addon authors want you to use newest version.
If you really want to do it I can only suggest this workaround: Open any file that belong to that addon and modify it. Add space or something. That will mark addon as modified and block normal updates.

**Comment by Krytos** [comment]
> I am certain it wasnt destroyed... You should come to the discord for any issues you feel was broken. A good amount of changes were made and some defaults of some things were changed and if they were not changed from the previous default then yes those would change a bit

Yeah, I guess all the complaint threads on their forums are all just bullshit as well, right? Maybe "destroyed" was a bit hyperbole but it took me a good half an hour to get my interface back to how it was.

**Comment by Krytos** [comment]
> Yeah I also highly doubt that update "destroyed" your interface.
> 
> Anyway I dislike idea of option that block the upgrades - addon authors want you to use newest version.
> If you really want to do it I can only suggest this workaround: Open any file that belong to that addon and modify it. Add space or something. That will mark addon as modified and block normal updates.

That is such a narrow view of the issue. So if an addon is great and does exactly what you want ti to but now the author decided that the addon should also do something totally unnecessary that you don't like, you are now simply fucked? How is it too much to ask to let your users be able to decide if they want to update an addon or not? Twitch allowed you to do this, same as the old curse client. 

It really should not be hard to add an option to toggle the auto update.

**Comment by AcidWeb** [comment]
Yes. It is a narrow view of the issue as I wasted hours of my life to help people who had issues with their UI and not admitted they running outdated version.

I don't appreciate your tone of your message but nonetheless I will add it later.

**Comment by Krytos** [comment]
I understand where you are coming from. I did not think about it from the point of view of a developer. I guess it must be very frustrating having to help people and try and fix a problem that only occured because they are not updating their addons. 

Thanks for re-opening the request however and thanks for your time. Your work is very much appreciated.
