### ISSUE TITLE
v2.2.0 missing characters in CMD, visible in CMDER/CONEMU

### ISSUE THREAD

**Issue by tordenflesk** [AcidWeb/CurseBreaker#9]
Left: CMDER, Right: CMD.exe
![](https://i.imgur.com/4GDiL4U.png)

**Comment by AcidWeb** [comment]
Both are terribly broken.

I can't replicate it. It is working correctly for me in both cmd and cmder.

**Comment by AcidWeb** [comment]
You run it from source?

**Comment by tordenflesk** [comment]
Nope. just ran cursebreaker.exe and let it auto-update.

**Comment by AcidWeb** [comment]
Binary version should start unmodified windows shell. No idea how you override it but version you starting have problems with parsing color codes and font don't have all characters to properly render tables.

**Comment by tordenflesk** [comment]
Apart from applying a version of the Monokai color scheme and picking 
"Raster Fonts" 6x8, cmd.exe hasn't been modified in any way.
picking Consolas or Lucida Console doesn't help.

this worked just fine in the previous version of CurseBreaker

-Espen

**Comment by AcidWeb** [comment]
And table was intact then? Intact lines like on screenshoot in readme?

**Comment by AcidWeb** [comment]
I think I found possible cause. I will give you binary to check in few hours.

**Comment by AcidWeb** [comment]
![image](https://user-images.githubusercontent.com/3713734/64172971-795a9680-ce56-11e9-855d-2aaad2821a4f.png)
OK. This is not fault of the font.

**Comment by AcidWeb** [comment]
![image](https://user-images.githubusercontent.com/3713734/64173101-d1919880-ce56-11e9-853e-09051a4fadd6.png)
Monokai color scheme is also not causing this issue.

**Comment by AcidWeb** [comment]
Are you using Windows 7?

**Comment by tordenflesk** [comment]
Yes

-Espen

**Comment by AcidWeb** [comment]
Well it is quite possible I broke Windows 7 support in latest release.

**Comment by AcidWeb** [comment]
Please try this version and provide screenshots:
https://ci.appveyor.com/api/buildjobs/1hgrikcnme3ymwr9/artifacts/dist%2FCurseBreaker.exe

**Comment by tordenflesk** [comment]
No change
Left: CMD, Right: Cmder
![](https://i.imgur.com/k11p14U.png)

**Comment by AcidWeb** [comment]
Well that version reverted changes made in 2.2.0.

Try this:
https://ci.appveyor.com/api/buildjobs/fgpvyco217f1gs39/artifacts/dist%2FCurseBreaker.exe

**Comment by tordenflesk** [comment]
No change.

**Comment by AcidWeb** [comment]
I will download Win7 VM and try to find some solution. But generally that is caused by fact that Win7 console is terribly outdated.

**Comment by AcidWeb** [comment]
I found the cause. I will release fix tomorrow.
