### ISSUE TITLE
Getting "Update suppressed" for some addons

### ISSUE THREAD

**Issue by frumpymoons** [AcidWeb/CurseBreaker#90]
I have RareScanner v8.5.1 installed and v8.5.2 is available on Curseforge (https://www.curseforge.com/wow/addons/rarescanner/files)
Attempting to update just says "Update suppressed". 

Same goes for The Undermine Journal.

Is this something on my end, curseforge or cursebreaker?

**Comment by AcidWeb** [comment]
That mean something modified the addon directory after last update (or you restored WTF backup) made by CurseBreaker. Use `force_update` command to override the lock.

**Comment by frumpymoons** [comment]
I use Resilio to sync my Interface folder between multiple devices. That probably explains it.
