### ISSUE TITLE
Error when starting cursebreaker

### ISSUE THREAD

**Issue by Smxdge** [AcidWeb/CurseBreaker#91]
![3lw5Ol8 1](https://user-images.githubusercontent.com/64716693/87185471-ce0d4000-c2b7-11ea-95de-93a08ea2cdb2.png)
Have been using Cursebreaker for a few weeks and this just popped up when I went to go update my addons.

**Comment by AcidWeb** [comment]
You got same error when you using binary version?

**Comment by Smxdge** [comment]
How would you recommend going about fixing it? not sure what could've caused it unfortunately

**Comment by AcidWeb** [comment]
First of all upload here your `CurseBreaker.json` from `WTF` directory.

**Comment by Smxdge** [comment]
[CurseBreaker.zip](https://github.com/AcidWeb/CurseBreaker/files/4904802/CurseBreaker.zip)
Had to zip it cause github doesnt support attaching .json

**Comment by AcidWeb** [comment]
Well this file is totally corrupted. Chest latest backups in `WTF-Backup` directory for one that contain text.

**Comment by Smxdge** [comment]
[CurseBreaker.zip](https://github.com/AcidWeb/CurseBreaker/files/4904826/CurseBreaker.zip)
This is the most recent backup I can find, has text so I'm assuming it's fine. Do I just throw this in my WTF folder and replace the old one or put the whole WTF folder in? My only guess as to what happened was, before I opened cursebreaker I update ElvUI through the TukUI client and I opened wow once I saw cursebreaker had errors. WoW was missing ElvUI completely so I'm assuming the update probably screwed things over?

**Comment by AcidWeb** [comment]
Yeah it is fine. **Replace only `CurseBreaker.json!**

No idea what caused this.

**Comment by Smxdge** [comment]
I may have opened cursebreaker while TukUI was updating my ElvUI. Maybe something happened there. Also this shouldnt effect my UI at all, right? basically overhauled it last night after the time .json file timestamp lol

**Comment by AcidWeb** [comment]
That is not connected. After restoring old `CurseBreaker.json` it might start to suppress updates for some addons if you updated them after that backup was made. You can fix that with `force_update` command.

**Comment by Smxdge** [comment]
That seemed to have fixed things. Thank you so much :)
