### ISSUE TITLE
Install older versions of addons?

### ISSUE THREAD

**Issue by Straky23** [AcidWeb/CurseBreaker#92]
Hello, 

this is not an issue but I just didn't know how to contact you directly without sending an email.

I just wanted to ask if it's possible to install older versions of addons through your cursebreaker app? For example, if I have issue with latest version of addon, do I need to manually download older version from curseforge or cursebreaker can do that?

**Comment by AcidWeb** [comment]
CB is not providing this feature and it will not provide this feature.
