### ISSUE TITLE
Status Column no longer filled since v3.5.0

### ISSUE THREAD

**Issue by cont1nuity** [AcidWeb/CurseBreaker#94]
The Status column does not show anymore after auto-update to 3.5.0 on Windows:
![image](https://user-images.githubusercontent.com/10164755/87286729-82e26f80-c4f9-11ea-945e-057d67c08412.png)

JSON: [CurseBreaker.zip](https://github.com/AcidWeb/CurseBreaker/files/4911448/CurseBreaker.zip)

**Comment by AcidWeb** [comment]
I already replicated this bug and it will be fixed soon.

**Comment by cont1nuity** [comment]
No rush needed for me. I see updates through the version coloring.

**Comment by cont1nuity** [comment]
Fix confirmed. Thank you!
