### ISSUE TITLE
Failed to parse addon data: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by eladsalad** [AcidWeb/CurseBreaker#95]
CB> install cf:world-quest-tracker
0/1 | ────────────────────────────────────────────────────────────────────────────────
RuntimeError: Failed to parse addon data: Expecting value: line 1 column 1 (char 0)

---

Using 'import install' or running the url_integration command then downloading from curse i only ever get this error.

**Comment by AcidWeb** [comment]
Is this link is working for you: https://addons-ecs.forgesvc.net/api/v2/addon/100610 ?
Do you maybe live in some country that filter the internet?

**Comment by eladsalad** [comment]
403 ERROR
The request could not be satisfied.
Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation. 

---
From Australia though so it is odd.

**Comment by AcidWeb** [comment]
Could you make a screenshot of entire error?
As you can see something is blocking access to CurseForge API.

**Comment by eladsalad** [comment]
![image](https://user-images.githubusercontent.com/67726859/87358202-ac0e0900-c5a8-11ea-93ee-d8be806a0b15.png)


---
I have temporarily changed my IP by using a tunneling service and now the API is accessible and the program works perfectly.

**Comment by AcidWeb** [comment]
Well can't do anything about it as it is not CloudFlare block.
