### ISSUE TITLE
Cursebreaker "Update Supressed" with Classic Addons

### ISSUE THREAD

**Issue by capSAR273** [AcidWeb/CurseBreaker#96]
I noticed that for updating certain classic WoW addons, cursebreaker will supress some updates. Is there a reason for this? I'm guessing it delays updates if they are super recent.

Love the app, its very useful now that Twitch is ditching addons in the future, just had this question.

![image](https://user-images.githubusercontent.com/5252505/87492366-6d179c00-c618-11ea-98cc-71b64915cd78.png)

**Comment by AcidWeb** [comment]
That mean that update is available but something modified the addon folder after they were installed by CB.
You can use `force_update` command to override the lock.

**Comment by capSAR273** [comment]
Cool, thank you! Is there a way to force_update all addons being used or only one by one?

**Comment by AcidWeb** [comment]
Nope. This should block should not be often that's why I rather let user confirm each one,.
