### ISSUE TITLE
Hard to search for WoW Interface addons

### ISSUE THREAD

**Issue by icbat** [AcidWeb/CurseBreaker#98]
Discovering addons via CurseForge is pretty straightforward and reasonable. Search works, and if you can guess at a name you can even find it via auto-complete sometimes:

![cf_search_sorta](https://user-images.githubusercontent.com/711905/87964733-44602e00-ca80-11ea-9989-2c167d75ddc1.PNG)

Discovering addons via WoW Interface is kinda painful. I wanted to get [Docking Station](https://www.wowinterface.com/downloads/info11831-DockingStationDisplay.html) but my first couple tries via CurseBreaker failed.

![search](https://user-images.githubusercontent.com/711905/87964304-a10f1900-ca7f-11ea-8ae9-ee3200387c70.PNG)

In part because install works from `ID-name`, which makes sense given their URLs, but makes it kind of hard to more organically find alternatives as you can with CurseForge.

![wowi](https://user-images.githubusercontent.com/711905/87964167-702ee400-ca7f-11ea-88d2-fde79d7fcb3a.PNG)

- Is there something to be done to wire in WoW Interface results into the search functionality? I can't seem to get it to pull back any WoWI results ever.
- To improve the user experience, is it reasonable to auto-complete the install box w/ addon names instead of `ID-name`? Maybe still show the ID, or have it at the end?

I'm interested in helping improve this experience with a PR if that's wanted.

**Comment by AcidWeb** [comment]
Search command is only searching on CurseForge. WoWI don't provide a API for that.

Removing ID from `wowi` slug would require create mapping: Project name -> Project ID. WoWI API don't provide means to generate such database directly. I could generate proper dataset on side of my backend but that solution have some issues.

Plus there are performance considerations. Auto-completion is already overloaded. Placing another set (as ID-NAME is staying) of WoWI addons might be straw that breaks camel's back.

**Comment by AcidWeb** [comment]
I will experiment with nested auto-completer in separate thread. That might provide enough performance boost to additionally extend the list.

**Comment by AcidWeb** [comment]
![image](https://user-images.githubusercontent.com/3713734/87972048-91ff8980-cac6-11ea-9d26-f0354cfa8e77.png)

Or try fuzzy search approach.

**Comment by icbat** [comment]
Excellent! Any of those options make a lot of sense and would answer this :) Thank you!
