### ISSUE TITLE
Less information on auto update

### ISSUE THREAD

**Issue by ArabCoders** [AcidWeb/CurseBreaker#99]
Hi, 

I think it's better to have when auto update for addon is run is to only show what has been updated instead of the whole list. including what updated.

if you have so many addons, it's hard to notice what has been updated, i can think of two ways to implement this for visual view.

1. show only what updated.
2. sort addons in a way which the updated addons shows on bottom of the list.

Thank you.

**Comment by AcidWeb** [comment]
Thanks for feedback. I'm not a fan of this solution but I will think about it.

**Comment by AcidWeb** [comment]
![image](https://user-images.githubusercontent.com/3713734/88286831-a96e8a80-ccf1-11ea-8d37-96f408b6c101.png)

**Comment by ArabCoders** [comment]
Thank you thats awesome.
